### PR TITLE
feat: Added an abstraction for logs and enabled long term storage in the CLI

### LINKED ISSUE #4413: Create an abstraction for a logs service so the UI and CLI can share it
### Summary 

There needs to be a way to make the UI / CLI share the code to fetch logs from different sources (pods / buckets).

This funcionality is currently working for the UI but not for `jx get build logs`.

The end goal is to have both the command the the UI show the same information when accessed regardless of build state.

The performance on `jx get build logs` should also be improved.

Lastly, the logs secrets masker should be applied to the logs on the CLI as well.

### PR DESCRIPTION
**Pull request by dgozalo**
Added an abstraction for logs and enabled long term storage in the CLI

feature: added changes to filtering

feature: fixed the lookup of pipeline activities

feature: renamed the logging file and fix after rebase

feature: finished refactor and added tests

feature: added tests

feature: added batch capabilities
Signed-off-by: Daniel Gozalo <dgozalo@cloudbees.com>

chore: lint and fmt

#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [X] Change is covered by existing or new tests.

#### Description
Added an abstraction layer on the logging so both the CLI and the UI can reuse the same logic.

This is done through the interface `LogWriter` which can be implemented by both to define how to 
deal with logs in different mediums.

The CLI's implementation of `LogWriter` is `CLILogWriter` and streams logs for running builds using `TailLogs`which calls Kubectl and single writes are done through the logger.

Also enabled the long term storage logs capabilities in the CLI. The logic has changed so it looks for `PipelineActivities` and their corresponding `PipelineRuns`. This was needed because we only used to let the user to see the logs of currently running builds instead of past builds which may have logs stored in buckets.

#### Which issue this PR fixes

fixes #4413

### CODE REVIEW

**Comment by hferentschik** [comment]
👍 for the intentions behind this.

**Comment by abayer** [comment]
How does this handle multi-stage pipelines? That is, a single `PipelineRun` with multiple pods?

**Comment by dgozalo** [comment]
> How does this handle multi-stage pipelines? That is, a single `PipelineRun` with multiple pods?

By iterating through the running building pods and validating that the labels match, you can show all the logs needed, ordered by creationTimestamp. this way you get the stages in order.

**Comment by abayer** [comment]
@dgozalo - cool, just making sure - I assumed it was doing the right thing, but figured it was quicker to ask than to try to figure out the call paths exactly. =)

**Pull request merged**
