### PR TITLE
fix: should be lowercase in commitstatuses

### PR DESCRIPTION
**Pull request by pmuir**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by ccojocar** [comment]
@pmuir Is it possible to close this PR?

**Comment by pmuir** [comment]
I'll write a custom unmarshaler to make it backwards compat - leave it open for now.

**Comment by Vlatombe** [comment]
Beware, I think this will trigger a similar issue to https://github.com/jenkins-x/jx/issues/2995 because `items` seems to be a specific case in openapi/swagger validation

**Comment by ccojocar** [comment]
@pmuir What's the deal with this fix? Are you plan it to merge it, or should we close it?

**Comment by ccojocar** [comment]
@pmuir I am going to close this PR since there hasn't been any progress since quite a while. Fell free to open another PR. Thanks

**Pull request closed without merging**
