### PR TITLE
Feature/delete gkecluster

### PR DESCRIPTION
**Pull request by DMEvanCT**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description
Having an arg for deletion of cluster is confusing. I put in an option instead as it makes it easier to understand for the end user. 

#### Special notes for the reviewer(s)
We may want to do the same things for eks / other Kubernetes options.

#### Which issue this PR fixes
N/A
fixes #

### CODE REVIEW

**Comment by DMEvanCT** [comment]
I can't see why lint failed can anyone tell me why or give me access to see

**Comment by hferentschik** [comment]
```
Showing logs for build jenkins-x-jx-pr-5897-lint-4 stage ci and container step-fmt
Gofmt errors in files:
./pkg/cluster/gke/gke.go
./pkg/cmd/deletecmd/delete_gke.go
./pkg/cloud/gke/gcloud.go
diff -u ./pkg/cluster/gke/gke.go.orig ./pkg/cluster/gke/gke.go
--- ./pkg/cluster/gke/gke.go.orig	2019-10-22 12:24:01.509682870 +0000
+++ ./pkg/cluster/gke/gke.go	2019-10-22 12:24:01.509682870 +0000
@@ -2,11 +2,11 @@
 
 import (
 	"fmt"
-	"os"
 	gcp "github.com/jenkins-x/**/pkg/cloud/gke"
 	"github.com/jenkins-x/**/pkg/cluster"
 	"github.com/jenkins-x/**/pkg/util"
 	"github.com/pkg/errors"
+	"os"
 )
 
 type gcloud struct {
@@ -80,8 +80,3 @@
 	labels := util.MapToKeyValues(labelMap)
```

I think the import order is wrong. 

Try running `make fmt` and `make importfmt` locally and then squash the changes.

**Comment by hferentschik** [comment]
In fact it would imo make sense to squash all of your committs and create a single commit with a conventional commit message format. That would also make the "Semantic Pull request" check pass :-)

**Comment by DMEvanCT** [comment]
@hferentschik this is the message I get when I run the make fmt

go: k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible: invalid pseudo-version: preceding tag (v2.0.0-alpha.0) not found
All Go files properly formatted

**Comment by macox** [comment]
> @hferentschik this is the message I get when I run the make fmt
> 
> go: k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible: invalid pseudo-version: preceding tag (v2.0.0-alpha.0) not found
> All Go files properly formatted

Are you using golang v1.13? try using 1.12...

**Pull request closed without merging**
