### PR TITLE
Service linking

### PR DESCRIPTION
**Pull request by angoothachap**
Service linking functionality

### CODE REVIEW

**Comment by jstrachan** [comment]
there was a test failure:
```

pkg/jx/cmd/step_link_services_test.go:55:35: not enough arguments in call to ConfigureTestOptionsWithResources

	have (*CommonOptions, []"github.com/jenkins-x/jx/vendor/k8s.io/apimachinery/pkg/runtime".Object, nil, *gits.GitCLI)

	want (*CommonOptions, []"github.com/jenkins-x/jx/vendor/k8s.io/apimachinery/pkg/runtime".Object, []"github.com/jenkins-x/jx/vendor/k8s.io/apimachinery/pkg/runtime".Object, gits.Gitter, helm.Helmer)
```
as there's a recent extra parameter been added. Lemme see if I can figure out the extra argument to pass...

**Comment by jstrachan** [comment]
think I've managed to add the extra parameter now - this was caused by a new refactor being done since you created your PR. Fingers crossed the CI pipeline goes green soon so we can merge this...

**Comment by jstrachan** [comment]
@angoothachap phew all green and merged now - many thanks!!!

**Comment by rawlingsj** [comment]
This is a great PR @angoothachap!

**Comment by angoothachap** [comment]
@jstrachan Yay! 

@rawlingsj thank you, not without @jstrachan's help :)

**Pull request merged**
