### PR TITLE
fix: broken link

### PR DESCRIPTION
**Pull request by shaowenchen**
#### Which issue this PR fixes

https://jenkins-x.io/documentation/ 404

### CODE REVIEW

**Comment by MarckK** [comment]
Thank you for your PRs, @shaowenchen :)

For the semantic PR checks, both the commit message and PR heading have to follow the semantic conventions. For this PR, it seems the commit needs to be amended to include a colon.

**Comment by MarckK** [comment]
Thank you for your PRs, @shaowenchen :)

For the semantic PR checks, both the commit message and PR heading have to follow the semantic conventions.

**Comment by shaowenchen** [comment]
> Thank you for your PRs, @shaowenchen :)
> 
> For the semantic PR checks, both the commit message and PR heading have to follow the semantic conventions. For this PR, it seems the commit needs to be amended to include a colon.

fixed

**Pull request merged**
