### PR TITLE
chore: Bump antham/chyle to 1.6.0

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

This is part of #6484's prep work - antham/chyle 1.4.0 (and 1.5.0) depend on an arbitrary commit in spf13/cobra, and that ends up resulting in breaking dependency resolution in go 1.13. I initially worked around this by adding an explicit `require` for spf13/cobra 0.0.5, but antham/chyle 1.6.0 passes all our tests and depends on spf13/cobra 0.0.5 explicitly, so it's a better fix.

I also did a `go mod tidy` while I was here.

#### Which issue this PR fixes

n/a

### CODE REVIEW

**Comment by hferentschik** [comment]
Did you run a `make generate` after `go mod tidy`? Otherwise, you might get a surprise that _go.mod_ changes during the generate task (long story). There is a `make tidy-deps` which takes care of both.

**Comment by abayer** [comment]
Oops, lemme do that.

**Comment by abayer** [comment]
@hferentschik Ok, ran `make tidy-deps` - let's see how this does.

**Pull request merged**
