### PR TITLE
Avoid keeping activities in memory for a long time before updating

### LINKED ISSUE #1890: Possible timing issue between jx promote and jx-resource jenkins plugin
### Summary 

Running a PR build for the jx project I got

```
 Created Pull Request: https://github.beescloud.com/****/environment-pr-1888-2-staging/pull/1
        
        Failed to update PipelineActivity: Operation cannot be fulfilled on pipelineactivities.jenkins.io "jenkins-x-tests-bdd-test-spring-1538663830-master-1": the object has been modified; please apply your changes to the latest version and try again
        error: Operation cannot be fulfilled on pipelineactivities.jenkins.io "jenkins-x-tests-bdd-test-spring-1538663830-master-1": the object has been modified; please apply your changes to the latest version and try again
```

### Steps to reproduce the behavior

Unknown

### PR DESCRIPTION
**Pull request by msvticket**
This is to avoid errors like
```
Failed to update PipelineActivity: Operation cannot be fulfilled on pipelineactivities.jenkins.io "jenkins-x-tests-bdd-test-spring-1538663830-master-1": the object has been modified; please apply your changes to the latest version and try again
        error: Operation cannot be fulfilled on pipelineactivities.jenkins.io "jenkins-x-tests-bdd-test-spring-1538663830-master-1": the object has been modified; please apply your changes to the latest version and try again
```

Fixes #1890

### CODE REVIEW

**Comment by msvticket** [comment]
Yeah. I whipped up this quick fix for the problem so it won't affect the developers in my organization. (Basically so they don't get a bad first impression of Jenkins-X.) I also thought I should share this for others in the same position.

I don't know if I can find the time to do a more proper fix.

**Comment by ccojocar** [comment]
I would postpone this for a proper fix. We have already quite some technical dept due to local fixes. Especially for this, I would prefer a generic solution.  

cc @jstrachan

**Comment by msvticket** [comment]
I don't really know what you mean with a generic solution. I don't think such a thing exists for all updates to k8s resources. But something more suitable than my first hack is certainly possible.

For updating PipelineActivity I'm now looking at using PATCH instead of UPDATE. But I don't know when I can be ready.

**Comment by msvticket** [comment]
Closing this pull request and creating new with fix using PATCH

**Pull request closed without merging**
