### PR TITLE
fix: add JSON schema validation for pipeline.yaml and jenkins-x.yml

### LINKED ISSUE #3728: Undefined fields in jenkins-x.yml or pipeline.yaml are silently ignored
### Summary 

Because we're using `yaml.Unmarshal` and not `yaml.UnmarshalStrict` (see #3544 for my first discussion on that front), fields in `jenkins-x.yml` or `pipeline.yaml` are silently ignored if they don't correspond to a field in the underlying structs. This means that you could have the wrong syntax but not know it, which is non-ideal.

### Steps to reproduce the behavior

Add a random field to `jenkins-x.yml`. Nothing fails.

### Expected behavior

There should be a validation failure, pointing out the field you added that isn't defined, with full qualification (`yaml.UnmarshalStrict` just gives you `key`, not `full.path.to.key`, so that's not good enough either).

### Actual behavior

No error, the unknown field is just ignored.

### Jx version

The output of `jx version` is:

```
jx                 2.0.0-dev+27e543059
jenkins x platform 0.0.3877
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.14.1
helm client        Client: v2.12.3+geecf22f
git                git version 2.20.1
Operating System   Ubuntu 18.04.1 LTS```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE

### Operating system / Environment

Doesn't really matter, but OS X and Ubuntu.

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

Also added `jx step syntax`:
- `jx step syntax schema` - generates JSON schema for either pipeline.yaml or jenkins-x.yml
- `jx step syntax validate buildpacks` - which validates against `jenkins-x-kubernetes` and `jenkins-x-classic` from the local clones.
- `jx step syntax validate pipeline` - validates jenkins-x.yml (or another context if specified)

Note that this depends on https://github.com/abayer/jsonschema, which
I'll try to get in a PR to the original (https://github.com/alecthomas/jsonschema).

#### Special notes for the reviewer(s)

/assign @dwnusbaum 
/assign @rawlingsj 
/assign @pmuir 
/assign @ccojocar 
/assign @warrenbailey 
/assign @hferentschik 
/hold

#### Which issue this PR fixes

fixes #3728

### CODE REVIEW

**Comment by abayer** [comment]
I still need to add tests for `jx step buildpack validate`, and I'm not sure if we actually want to use my fork (https://github.com/abayer/jsonschema) or wait til I can get a PR in to the original.

**Comment by abayer** [comment]
Oh, I also updated `jenkins-x*.yml` in this repo to be valid, and verified that all of our existing build packs are valid too.

**Comment by abayer** [comment]
...and ignore those first couple errors - I rebased before they could even kick off and they barfed as a result. =)

**Comment by rawlingsj** [comment]
@abayer just noticed you'd put this PR on hold, I've lgtm so if you're happy for it to merge just cancel the hold.

**Comment by abayer** [comment]
@rawlingsj - thanks, but I still want to add more tests and get a consensus on whether we want to use my fork of https://github.com/alecthomas/jsonschema. Oh, and whether we should be doing some kind of release note due to existing jenkins-x.yml files with invalid content failing once this goes live...

**Comment by abayer** [comment]
/assign @jstrachan 

fyi, this now has `jx step syntax` and subcommands for validation and schema generation. =)

**Comment by abayer** [comment]
aaaaand opened https://github.com/alecthomas/jsonschema/pull/32 to get the changes we need upstream.

**Comment by abayer** [comment]
Gonna take this off hold once either my PR upstream gets merged or we know it won't. =)

**Comment by abayer** [comment]
Ok, new PR to `jsonschema` up at https://github.com/alecthomas/jsonschema/pull/36 - the first thing the original PR did (keep from panicking on unnamed fields) got fixed in someone else's PR that got merged before mine, so the new PR just adds the ability to ignore types. Hopefully it'll get merged in the next couple days, I can switch to using the real version rather than my fork here, and this can go off hold.

**Comment by abayer** [comment]
/hold cancel

The PR we needed is merged, so this is good to go!

**Pull request merged**
