### PR TITLE
fix: a `jx step verify behavior` command to trigger the bdd tests

### PR DESCRIPTION
**Pull request by jstrachan**
so folks can easily run the BDD tests inside any Jenkins X installation

fixes https://github.com/jenkins-x/jx/issues/5454

### CODE REVIEW

**Comment by pmuir** [comment]
/hold 

I think we need to think through the name of this and its relationship to the `jx step bdd`

**Comment by jstrachan** [comment]
@pmuir I'm open to ideas on a better name.

BTW am hoping we can move away from `jx step bdd` really and just use `jx boot` / jx create cluster / jx install` to setup clusters when required - then run `jx bdd`

**Comment by pmuir** [comment]
Put some ideas in the slack thread

**Comment by pmuir** [comment]
Suggestion is to use `jx step verify behavior`

**Comment by jstrachan** [comment]
@pmuir renamed to `jx step verify behavior`

**Pull request merged**
