### PR TITLE
feat(updatebot) expose a flag to enable to DisableMaven functionality in import

### PR DESCRIPTION
**Pull request by garethjevans**

### CODE REVIEW

**Comment by garethjevans** [comment]
Should fix #2703, or at least provide a workaround when importing projects

**Comment by rawlingsj** [comment]
@garethjevans: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
serverless-jenkins | d647c4d8a2a3ad0f708c046f910b784be829757e | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
