### PR TITLE
fix: jx import does not respect --git-username and --git-api-token

### LINKED ISSUE #4752: jx import does not respect --git-username and --git-api-token
### Summary 
run "jx import --git-username='sonyafenge' --git-api-token='**************************'", still get question to input Git User Name and API Token.
### Steps to reproduce the behavior
1. install jenkins X static server
2. git clone project to local folder
3. run "cd ~/[localfolder]"
4. run "jx import --git-username='sonyafenge' --git-api-token='**************************'"
### Expected behavior
jx import without asking for git user name and git api token
### Actual behavior
```
WARNING: No username defined for the current Git server!
? Git user name:  [Use arrows to move, space to select, type to filter]
> sonyali01
  sonyafenge
```
after choose sonyafenge as git username, the message below popup and need confirm again:
```
? Git user name: sonyafenge
? GitHub username: (sonyafenge) 
```

```
To be able to create a repository on GitHub we need an API Token
Please click this URL and generate a token 
https://github.com/settings/tokens/new?scopes=repo,read:user,read:org,user:email,write:repo_hook,delete_repo

Then COPY the token and enter it below:

? API Token: 
```
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.472
jenkins x platform 2.0.768
Kubernetes cluster v1.13.2
kubectl            v1.14.0
helm client        Client: v2.11.0+g2e55dbe
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.5 build 18F132
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [X] Classic Jenkins

### Kubernetes cluster

Kubernetes cluster in AWS Ec2 and using Heptio quickstart on AWS created

### Operating system / Environment

Mac OS X 10.14.5 build 18F132

### PR DESCRIPTION
**Pull request by sonyafenge**
#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description
Run command line below and found --git-username and --git-api-token doesn't work:
"jx import --git-username='sonyafenge' --git-api-token='**************************'"

#### Special notes for the reviewer(s)
- updated 'pkg/cmd/importcmd/import.go':
        if options.GitRepositoryOptions.Username existing,  use this name to get userAuth; if not, then ask user to input.
        if options.GitRepositoryOptions.ApiToken existing, grant this ApiToken to userAuth;
- updated 'pkg/auth/auth_config.go':
       only request user input when userAuth.ApiToken == ""

#### Which issue this PR fixes

fixes #4752

### CODE REVIEW

**Comment by pmuir** [comment]
@ccojocar suggest you review this in light of your refactor

**Comment by ccojocar** [comment]
@pmuir I am stuck with the refactoring. Unfortunately, there are way too many conflicts to be able to rebase the branch.

**Pull request merged**
