### PR TITLE
chore: add a codecov target

### PR DESCRIPTION
**Pull request by pmuir**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by ccojocar** [comment]
Our coverage doesn't seem to be impressive.

**Comment by pmuir** [comment]
/hold

Definitely not ready to merge yet :-)

**Comment by pmuir** [comment]
> It would be nice to add a badge to the README with:
> 
> [Coverage Status](https://codecov.io/gh/jenkins-x/jx)

Will do!

**Pull request merged**
