### PR TITLE
fix: add env variables specified per step

### LINKED ISSUE #6845: env variables in overridden step are ignored
### Summary 
I 'm trying to add env variables in a specific step:

### Steps to reproduce the behavior
```
buildPack: gradle
pipelineConfig:
  pipelines:
    overrides:
      - stage: build # add -PnodeInstall to install npm
        name: gradle-build
        type: replace
        steps:
          - name: gradle-build
            env:
              - name: KEYCLOAK_AUTH_SERVER_URL
                value: https://auth.jx.<org>.com/auth
              - name: KEYCLOAK_USERNAME
                value: keycloak
              - name: KEYCLOAK_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: jenkins-x-keycloak-http
                    key: password
            command: ./gradlew clean build -Pprod -PnodeInstall --no-daemon
```

### Expected behavior
env variables should be added to the step's container

### Actual behavior
env variables missing

### Jx version

The output of `jx version` is:

```
2.0.1221
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Kubespray

### PR DESCRIPTION
**Pull request by yelhouti**
#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [X] Change is covered by existing or new tests.

#### Description
using env for specific task wasn't working (at least for overridden tasks), no the anv variables are added correctly

#### Which issue this PR fixes

fixes #6845

### CODE REVIEW

**Comment by abayer** [comment]
Thanks. Could you please add a test to https://github.com/jenkins-x/jx/blob/master/pkg/cmd/step/create/step_create_task_test.go like https://github.com/jenkins-x/jx/tree/master/pkg/cmd/step/create/test_data/step_create_task/override-steps? Or even just add an env to one of the non pull request overrides in https://github.com/jenkins-x/jx/blob/master/pkg/cmd/step/create/test_data/step_create_task/override-steps/jenkins-x.yml and update the tasks.yml for that test with the expected result.

**Comment by yelhouti** [comment]
@abayer thanks for guiding me on how to add the test, I should have read everything you have written before going at it would have saved some 30 min finding how tests work and the best candidate to override, this will teach me :smile:

**Pull request merged**
