### PR TITLE
fix: looking up vault URL when incluster

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by rawlingsj** [comment]
@abayer 
/hold

**Comment by abayer** [comment]
/hold cancel
/lgtm

I’d still like a better solution for the long term, but for the immediate, I can’t come up with something I’m more comfortable with than this, so hey. =)

**Comment by rawlingsj** [comment]
> I’d still like a better solution for the long term, but for the immediate, I can’t come up with something I’m more comfortable with than this, so hey. =)

@abayer thanks for following up with this while I was out, I apreciate it.  I agree with the above BTW.

**Pull request merged**
