### PR TITLE
 Using PATCH instead of PUT to update PipelineActivity 

### LINKED ISSUE #1890: Possible timing issue between jx promote and jx-resource jenkins plugin
### Summary 

Running a PR build for the jx project I got

```
 Created Pull Request: https://github.beescloud.com/****/environment-pr-1888-2-staging/pull/1
        
        Failed to update PipelineActivity: Operation cannot be fulfilled on pipelineactivities.jenkins.io "jenkins-x-tests-bdd-test-spring-1538663830-master-1": the object has been modified; please apply your changes to the latest version and try again
        error: Operation cannot be fulfilled on pipelineactivities.jenkins.io "jenkins-x-tests-bdd-test-spring-1538663830-master-1": the object has been modified; please apply your changes to the latest version and try again
```

### Steps to reproduce the behavior

Unknown

### PR DESCRIPTION
**Pull request by jtnord**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

subsumes #2110 where I resolved a merge conflict badly and do not have rights on deniedboardings repo to push the fix.  (appologies @msvticket)

This is to avoid http status 409 when other process has updated activity.
Also simplifying a bit by updating once in any case and not zero, one or two times depending on. The zero case didn't happen anyway as far as I could see.

Fixes #1890

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by pmuir** [comment]
What would be very useful would be to develop some helpers to make doing
patches easier and also to always use an exponential backoff.

**Comment by ccojocar** [comment]
@jtnord Any plans to complete this PR?

**Comment by jtnord** [comment]
No, this is not my pr as I said in the description

**Comment by ccojocar** [comment]
@jtnord Now it's yours since you started a separate PR. Next time try to push changes in the original PR instead of opening another PR if you don't intend to complete it.

@msvticket Do you mind having a look at the failed tests? Thanks

**Comment by jtnord** [comment]
I have no plans to work on this PR, my effort here was to clear up the mess I made for @msvticket when I made a bad merge conflict.

**Comment by jstrachan** [comment]
lets close this for now and we can re-create it again later from a clean branch?

**Pull request closed without merging**
