### PR TITLE
fix: Update go-gitlab to version 0.12.0 for v4 of the API

### LINKED ISSUE #3436: the jenkins-x can not create git repository
### Summary 
when I did the follow command:
`# jx install --provider=kubernetes`
in the end ,the error shows like this: 
`error: creating the environments: failed to create staging environment in namespace jx: creating environment git repository: creatakercanyon-staging due to: POST http://gitlab.xxx.com/api/v3/user/repos: 410  []
`

### Steps to reproduce the behavior
when I do the follow command:
$ jx install --provider=kubernetes
and enter my gitlab address, successfully installed jenkins-x，but can not create git repository with gitlab.xxx.com

image
image

I used fowllow command installed gitlab with kubernetes:
helm upgrade --install gitlab gitlab/gitlab \
  --timeout 600 \
  --namespace gitlab-ce \
  --set certmanager.install=false \
  --set global.hosts.domain=xxx.com \
  --set global.hosts.externalIP=192.168.15.141 \
  --set global.ingress.configureCertmanager=false \
  --set global.ingress.tls.enabled=false \
  --set global.hosts.https=false \
  --set global.edition=ce

### Expected behavior
jenkins-x can create repository  with gitlab

### Actual behavior
jenkins-x can not create repository  with gitlab

### Jx version
`# jx --version
1.3.1010`

The output of `jx version` is:
NAME               VERSION
jx                 1.3.1030
jenkins x platform 0.0.3636
Kubernetes cluster v1.13.4
kubectl            v1.13.4
helm client        v2.13.0+g79d0794
helm server        v2.13.0+g79d0794
git                git version 1.8.3.1
Operating System   CentOS Linux release 7.6.1810 (Core) 

COPY OUTPUT HERE
`error: creating the environments: failed to create staging environment in namespace jx: creating environment git repository: creating the repository: Failed to create repository /environment-takercanyon-staging due to: POST http://gitlab.xxx.com/api/v3/user/repos: 410  []``

### Jenkins type

Static Master Jenkins

### Kubernetes cluster

kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

the kubernetes is the Binary installation on Bare Metal

### Operating system / Environment

cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 

with xshell did the command.

Sorry For My Poor English.....

### LINKED ISSUE #5842: `jx boot`: `verify-jenkins-x-environment` step failing. Returning `404` when fetching the repository with a `GET` request
### Summary 

I'm using Serverless Jenkins X with Gitlab. I tried `jx boot` on two of the more recent versions of JX (2.0.875 and 2.0.861) and the `verify-jenkins-x-environment` step is failing. A `404` is being returned when attempting to fetch the repository with a `GET` request.

I've resorted to using `jx boot` with JX version 2.0.827 (which works) to install Jenkins X onto my cluster and then updating my JX version afterwards (to the latest version 2.0.875) to make use of the latest JX features.

P.S. Feel free to let me know if I'm mis-using `jx boot` and/or the `https://github.com/jenkins-x/jenkins-x-boot-config` repository

### Steps to reproduce the behavior

Prerequisite: `https://GITLAB_DOMAIN/USER/environment-test-cluster-dev.git` does not exist (or it has been deleted)

1. Fork the `https://github.com/jenkins-x/jenkins-x-boot-config` project into a Gitlab repo
2. `git clone https://GITLAB_DOMAIN/group/jenkins-x-boot-config`
3. Customise `jx-requirements.yml` file to something like this

```
# jenkins-x-boot-config/jx-requirements.yml

cluster:
  clusterName: test-cluster
  environmentGitOwner: USER
  gitKind: gitlab
  gitName: gitlab
  gitServer: https://GITLAB_DOMAIN
  project: jx-next-gen-tests
  provider: gke
  zone: europe-west2-b
gitops: true
environments:
- key: dev
- key: staging
- key: production
ingress:
  domain: DOMAIN # SET DOMAIN
  externalDNS: true # SET to true
  tls:
    email: ""
    enabled: false
    production: false
kaniko: true
secretStorage: vault
storage:
  logs:
    enabled: false
    url: ""
  reports:
    enabled: false
    url: ""
  repository:
    enabled: false
    url: ""
versionStream:
  ref: "master"
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: lighthouse # CHANGED prow to Lighthouse

```

#### JX Version where it is working as intended
```
NAME               VERSION
jx                 2.0.827
Kubernetes cluster v1.13.7-gke.24
kubectl            v1.16.1
helm client        Client: v2.13.1+g618447c
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

#### Logs

```
STEP: verify-jenkins-x-environment command: /bin/sh -c jx step verify env in dir: .

validating git repository for dev at URL https://GITLAB_DOMAIN/USER/environment-test-cluster-dev.git
creating environment dev git repository for URL: https://GITLAB_DOMAIN/USER/environment-test-cluster-dev.git to namespace jx
Username for 'https://GITLAB_DOMAIN': USER
Password for 'https://USER@GITLAB_DOMAIN': 
Username for 'https://GITLAB_DOMAIN': USER
Password for 'https://USER@GITLAB_DOMAIN': 
Username for 'https://GITLAB_DOMAIN': USER
Password for 'https://USER@GITLAB_DOMAIN': 
Duplicated Git repository https://GITLAB_DOMAIN/USER/jenkins-x-boot-config to https://GITLAB_DOMAIN/USER/environment-test-cluster-dev
Setting upstream to https://GITLAB_DOMAIN/USER/environment-test-cluster-dev
Created Pull Request: https://GITLAB_DOMAIN/USER/environment-test-cluster-dev/merge_requests/1
WARNING: Adding labels not supported on gitlab yet for repo USER/environment-test-cluster-dev issue 1 labels [jx/boot]
Added label jx/boot to Pull Request https://GITLAB_DOMAIN/USER/environment-test-cluster-dev/merge_requests/1
validating git repository for production at URL https://GITLAB_DOMAIN/USER/environment-test-cluster-production.git
creating environment production git repository for URL: https://GITLAB_DOMAIN/USER/environment-test-cluster-production.git to namespace jx-production
Using Git provider gitlab at https://GITLAB_DOMAIN
? Using Git user name: USER
? Using organisation: USER
Creating repository USER/environment-test-cluster-production
Git repository USER/environment-test-cluster-production already exists
Pushed Git repository to https://GITLAB_DOMAIN/USER/environment-test-cluster-production

validating git repository for staging at URL https://GITLAB_DOMAIN/USER/environment-test-cluster-staging.git
creating environment staging git repository for URL: https://GITLAB_DOMAIN/USER/environment-test-cluster-staging.git to namespace jx-staging
Using Git provider gitlab at https://GITLAB_DOMAIN
? Using Git user name: USER
? Using organisation: USER
Creating repository USER/environment-test-cluster-staging
Git repository USER/environment-test-cluster-staging already exists
Pushed Git repository to https://GITLAB_DOMAIN/USER/environment-test-cluster-staging

the git repositories for the environments look good

STEP: install-repositories command: /bin/sh -c jx step helm apply --boot --name repos in dir: repositories

...

```

#### JX Versions where it is not working as intended

```
NAME               VERSION
jx                 2.0.861
Kubernetes cluster v1.13.7-gke.24
kubectl            v1.16.1
helm client        Client: v2.13.1+g618447c
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

```
NAME               VERSION
jx                 2.0.875
Kubernetes cluster v1.13.7-gke.24
kubectl            v1.16.1
helm client        Client: v2.13.1+g618447c
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

#### Logs

```
$ jx boot

STEP: verify-jenkins-x-environment command: /bin/sh -c jx step verify env in dir: .

Validating git repository for dev environment at URL https://GITLAB_DOMAIN/USER/environment-test-cluster-dev.git
Username for 'https://GITLAB_DOMAIN': 
Password for 'https://USER@GITLAB_DOMAIN': 
error: creating remote for dev environment environment-test-cluster-dev: duplicating https://GITLAB_DOMAIN/USER/jenkins-x-boot-config to USER/environment-test-cluster-dev: getting repo for https://GITLAB_DOMAIN/USER/jenkins-x-boot-config: failed to get repository USER/jenkins-x-boot-config due to: GET https://GITLAB_DOMAIN/api/v3/repos/USER/jenkins-x-boot-config: 404  []
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step verify env' command in directory '.', output: ''

```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

I'm using a GKE cluster. I created it manually using the GCP web GUI.

### PR DESCRIPTION
**Pull request by TonyNoble**
fixes #3436

Signed-off-by: Tony Noble <tony.noble@gmail.com>

#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description
The version of go-gitlab only supports version 3 of the GitLab API, which was deprecated in v9 and removed completely in v11 (current is now v12). As a result, anyone with a vaguely up-to-date GitLab installation cannot use jenkins-x. This changes updates the module requirement to a version that supports v4 of the API

#### Which issue this PR fixes

fixes #5842

### CODE REVIEW

**Comment by hferentschik** [comment]
@TonyNoble thanks for the pull request. Looks good to me as well. Could you please also add the changes to go.sum to your commit? That's what breaking the lint task atm. We keep go.mod as well as go.sum under version control.

**Comment by TonyNoble** [comment]
@hferentschik - No problem, will do that this evening.  This process is a bit of a learning experience for me :) 
Do you need the go.sum change squashed into the existing commit?

**Comment by TonyNoble** [comment]
@hferentschik - Changes to go.sum now committed

**Comment by hferentschik** [comment]
@TonyNoble - sorry to bother you once more. Could I ask you to also run `make generate`? AFAICT this will add yet another line to `go.sum`. Something like:
```
github.com/stretchr/testify v1.4.0 h1:2E4SXV/wtOkTonXsotYi4li6zVWxYlZuYNCXe9XRJyk=
```

Seems your gitlab version upgrade triggers transitively another version upgrade for testify. Go modules mysteries. 

I just tried this locally and after this update to `go.sum` the lint task seems to pass.

**Comment by TonyNoble** [comment]
@hferentschik - no problem, will do that this evening.  Apologies for the faff, and thanks for your patience with this 👍

**Comment by TonyNoble** [comment]
@hferentschik - should add - I can't view the lint results through the github UI (not an organisation member).  Is there a reasonable way to run this locally?  I'm still working my way through documentation/process...

**Comment by hferentschik** [comment]
You can run `make lint`. You can also see what's exactly executed in the pipeline by looking at jenkins-x-lint.yml - https://github.com/jenkins-x/jx/blob/cb9cb1f1a30febcc3da802625dcdd463f00aef7f/jenkins-x-lint.yml#L28

**Comment by hferentschik** [comment]
Here is the log:

```
Generation complete
Code generation is out of date
go.sum
diff --git a/go.sum b/go.sum
index 4b9c78853..eb8f5e6be 100644
--- a/go.sum
+++ b/go.sum
@@ -712,6 +712,7 @@ github.com/stretchr/testify v1.2.1/go.mod h1:a8OnRcib4nhh0OaRAV+Yts87kKdq0PP7pXf
 github.com/stretchr/testify v1.2.2/go.mod h1:a8OnRcib4nhh0OaRAV+Yts87kKdq0PP7pXfy6kDkUVs=
 github.com/stretchr/testify v1.3.0 h1:TivCn/peBQ7UY8ooIcPgZFpTNSz0Q2U6UrFlUfqbe0Q=
 github.com/stretchr/testify v1.3.0/go.mod h1:M5WIy9Dh21IEIfnGCwXGc5bZfKNJtfHm1UVUgZn+9EI=
+github.com/stretchr/testify v1.4.0 h1:2E4SXV/wtOkTonXsotYi4li6zVWxYlZuYNCXe9XRJyk=
 github.com/stretchr/testify v1.4.0/go.mod h1:j7eGeouHqKxXV5pUuKE4zz7dFj8WfuZ+81PSLYec5m4=
 github.com/tektoncd/pipeline v0.5.1 h1:8722SzGr6TZyFL2D36RO16N5Llb1VL3hGWdnPYTgBXs=
 github.com/tektoncd/pipeline v0.5.1/go.mod h1:IZzJdiX9EqEMuUcgdnElozdYYRh0/ZRC+NKMLj1K3Yw=
make: *** [Makefile.codegen:81: verify-generation-complete] Error 1
FAILED make verify-generation-complete
```

**Comment by hferentschik** [comment]
What's happening is that `make generate` also add another version of testify to the go.sum file and then as part of the check whether generated resources are out of date (https://github.com/jenkins-x/jx/blob/78b81f1d9b2ebb58bc0f0481d8e323b07adbb3c7/Makefile.codegen#L79) it complains about go.sum (since thje rule just checks whether there are modified files). 

Hope that makes sense. A lot going on here ;-)

**Comment by TonyNoble** [comment]
Hi @hferentschik 

Thanks for all the pointers - hopefully we're somewhere near now :)

**Comment by hferentschik** [comment]
> Thanks for all the pointers - hopefully we're somewhere near now :)

No worries. It is a bit hard w/o being able to see the logs. I fully understand. Hopefully, we are soon in a position to have the build logs public.

**Comment by TonyNoble** [comment]
> 
> 
> > Thanks for all the pointers - hopefully we're somewhere near now :)
> 
> No worries. It is a bit hard w/o being able to see the logs. I fully understand. Hopefully, we are soon in a position to have the build logs public.

@hferentschik - that would be useful :)  I'm doing a fair amount of work trying to get jx boot working with gitlab / on-prem kubernetes at the moment, so there will likely be a few more of these.  Hopefully the next ones won't require so much to-and-fro...

**Comment by hoaitang** [comment]
Hi @TonyNoble , I am having the jx 2.0.1083 . run jx boot with gitlab. It failed 404 below:
** Am I using correct version or it is something else ** 
Thanks for your advise

Validating git repository for dev environment at URL https://gitlab..../environment-.-dev.git
error: handle dev environment repository: creating remote for dev environment environment-..-dev: duplicating https://github.com/jenkins-x/jenkins-x-boot-config to /environment-..-dev: getting repo for https://github.com/jenkins-x/jenkins-x-boot-config: GET https://gitlab...com/api/v4/users/jenkins-x/projects: 404 {message: 404 User Not Found}
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step verify env' command in directory '.', output: ''

**Comment by TonyNoble** [comment]
> 
> 
> Hi @TonyNoble , I am having the jx 2.0.1083 . run jx boot with gitlab. It failed 404 below:
> ** Am I using correct version or it is something else **
> Thanks for your advise
> 
> Validating git repository for dev environment at URL https://gitlab..../environment-.-dev.git
> error: handle dev environment repository: creating remote for dev environment environment-..-dev: duplicating https://github.com/jenkins-x/jenkins-x-boot-config to /environment-..-dev: getting repo for https://github.com/jenkins-x/jenkins-x-boot-config: GET https://gitlab...com/api/v4/users/jenkins-x/projects: 404 {message: 404 User Not Found}
> error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step verify env' command in directory '.', output: ''

Hi @hoaitang - I think the clue is in the URL it's trying to exercise.  It's trying to find all projects belonging to user 'jenkins-x' in gitlab.com  I think you need to look at setting the envirionmentGitOwner value under the 'cluster' group in your jx-requirements.yml file - set this to your GitLab user and you should be good.

**Pull request merged**
