### PR TITLE
fix: separating global flag options and install/create cluster flags

### PR DESCRIPTION
**Pull request by hferentschik**
fix for issue #4851

### CODE REVIEW

**Comment by hferentschik** [comment]
I am wondering where these options really should be available. So far they were available via the root.

```golang
func (o *CommonOptions) AddSharedInstallFlags(cmd *cobra.Command) {
	cmd.PersistentFlags().StringVarP(&o.ConfigFile, "config-file", "", "", "Configuration file used for installation")
	cmd.PersistentFlags().BoolVarP(&o.NoBrew, OptionNoBrew, "", false, "Disables brew package manager on MacOS when installing binary dependencies")
	cmd.PersistentFlags().BoolVarP(&o.InstallDependencies, OptionInstallDeps, "", false, "Enables automatic dependencies installation when required")
	cmd.PersistentFlags().BoolVarP(&o.SkipAuthSecretsMerge, OptionSkipAuthSecMerge, "", false, "Skips merging the secrets from local files with the secrets from Kubernetes cluster")

	o.Cmd = cmd
}
```

I think they are only relevant for install and create cluster, right? If so, one might as well remove this function and add the flags to `InstallOptions#AddInstallFlags`. WDYT?

**Comment by abayer** [comment]
Seems reasonable to me, but yeah, the potential ramifications make me wary of lgtm'ing it myself. =)

**Comment by hferentschik** [comment]
> Seems reasonable to me, but yeah, the potential ramifications make me wary of lgtm'ing it myself. =)

Right. So I am sure about the changes to the flags in the root command. What I am not so sure about is where except create/install I would need to add _no-brew_, _config-file_, etc. I was hoping to get some feedback from the people working in this area. Was the config file changes not @cagiti's baby?

**Comment by hferentschik** [comment]
or maybe it was @macox'es?

**Comment by hferentschik** [comment]
@macox, @ccojocar - do you fancy to have a look at this?

**Comment by macox** [comment]
@hferentschik I moved the config-file flag down in to common options on your request in this PR  https://github.com/jenkins-x/jx/pull/4308

**Comment by hferentschik** [comment]
> I moved the config-file flag down in to common options on your request in this PR #4308

I see. Might have been a misunderstanding or I was just not thinking straight. As it stands now, the `--config-file` option is available for all commands, even though it only applies for create cluster and install Jenkins-X. 

I could envision that the config file also allows to persist flags one always want to set (eg always set the _verbose_ flag), but for now we don't do that and I don't think that something like that becomes a high priority in the near future. 

I also don't just move the `--config-file` option, but all of the options under `AddCommonFlags`, since they are no really common to all commands. Common are _verbose_ and _batch_ imo.

**Comment by macox** [comment]
I'm happy with moving `--config-file` to install, some consensus on the others might be good though

**Comment by hferentschik** [comment]
@jenkins-x/core ^^

**Comment by hferentschik** [comment]
@garethjevans any take on this? ;-)

**Comment by hferentschik** [comment]
@pmuir falls into our CLI discussion today. Current behaviour around global flags is just wrong. This is an attempt to rectify this.

**Pull request merged**
