### PR TITLE
fix: Use temp JX_HOME and KUBECONFIG for integration tests

### LINKED ISSUE #3625: Integration tests are failing
### Summary 

The integration tests run by `make test-slow-integration` are failing. This failure also occurs on CI and lets the _integration_ status check fail. 

### Steps to reproduce the behavior

Run (multiple times if necessary):

```bash
$ make test-slow-integration
```

### Expected behavior

Tests pass

### Actual behavior

The test logs:
```
...
 FAIL: TestImportProjectNextGenPipeline (27.84s)
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/custom_jenkins from source test_data/import_projects/custom_jenkins
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/docker from source test_data/import_projects/docker
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/docker-helm from source test_data/import_projects/docker-helm
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/gradle_no_files from source test_data/import_projects/gradle_no_files
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/helm from source test_data/import_projects/helm
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/maven_camel from source test_data/import_projects/maven_camel
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/maven_custom_build_pack from source test_data/import_projects/maven_custom_build_pack
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/maven_no_files from source test_data/import_projects/maven_no_files
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/maven_old_jenkinsfile from source test_data/import_projects/maven_old_jenkinsfile
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/maven_old_jenkinsfile_with_git from source test_data/import_projects/maven_old_jenkinsfile_with_git
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-

...

FAIL	github.com/jenkins-x/jx/pkg/jx/cmd	338.772s
?   	github.com/jenkins-x/jx/pkg/jx/cmd/bdd	[no test files]
?   	github.com/jenkins-x/jx/pkg/jx/cmd/clients	[no test files]
?   	github.com/jenkins-x/jx/pkg/jx/cmd/clients/mocks	[no test files]
?   	github.com/jenkins-x/jx/pkg/jx/cmd/cmd_test_helpers	[no test files]
ok  	github.com/jenkins-x/jx/pkg/jx/cmd/opts	39.340s	coverage: 3.3% of statements
?   	github.com/jenkins-x/jx/pkg/jx/cmd/templates	[no test files]
?   	github.com/jenkins-x/jx/pkg/kserving	[no test files]
ok  	github.com/jenkins-x/jx/pkg/kube	1.653s	coverage: 31.0% of statements
ok  	github.com/jenkins-x/jx/pkg/kube/cluster	0.289s	coverage: 76.0% of statements
?   	github.com/jenkins-x/jx/pkg/kube/mocks	[no test files]
?   	github.com/jenkins-x/jx/pkg/kube/mocks/matchers	[no test files]
ok  	github.com/jenkins-x/jx/pkg/kube/pki	10.226s	coverage: 20.9% of statements
?   	github.com/jenkins-x/jx/pkg/kube/resources	[no test files]
?   	github.com/jenkins-x/jx/pkg/kube/resources/mocks	[no test files]
?   	github.com/jenkins-x/jx/pkg/kube/serviceaccount	[no test files]
?   	github.com/jenkins-x/jx/pkg/kube/services	[no test files]
ok  	github.com/jenkins-x/jx/pkg/kube/vault	0.547s	coverage: 57.6% of statements
?   	github.com/jenkins-x/jx/pkg/log	[no test files]
?   	github.com/jenkins-x/jx/pkg/maven	[no test files]
?   	github.com/jenkins-x/jx/pkg/nodes	[no test files]
ok  	github.com/jenkins-x/jx/pkg/packages	0.052s	coverage: 38.8% of statements
?   	github.com/jenkins-x/jx/pkg/pipeline_events	[no test files]
ok  	github.com/jenkins-x/jx/pkg/pipelinescheduler	0.201s	coverage: 43.4% of statements
ok  	github.com/jenkins-x/jx/pkg/pipelinescheduler/prow	0.225s	coverage: 89.7% of statements
?   	github.com/jenkins-x/jx/pkg/pipelinescheduler/testhelpers	[no test files]
ok  	github.com/jenkins-x/jx/pkg/prow	0.305s	coverage: 78.4% of statements
ok  	github.com/jenkins-x/jx/pkg/prow/config	0.248s	coverage: 9.6% of statements
ok  	github.com/jenkins-x/jx/pkg/quickstarts	0.215s	coverage: 18.4% of statements
ok  	github.com/jenkins-x/jx/pkg/reports	0.056s	coverage: 39.7% of statements
?   	github.com/jenkins-x/jx/pkg/spring	[no test files]
ok  	github.com/jenkins-x/jx/pkg/surveyutils	0.366s	coverage: 64.3% of statements
?   	github.com/jenkins-x/jx/pkg/table	[no test files]
ok  	github.com/jenkins-x/jx/pkg/tekton	0.323s	coverage: 38.9% of statements
ok  	github.com/jenkins-x/jx/pkg/tekton/syntax	0.254s	coverage: 89.7% of statements
?   	github.com/jenkins-x/jx/pkg/tekton/tekton_helpers_test	[no test files]
ok  	github.com/jenkins-x/jx/pkg/terraform	0.054s	coverage: 6.8% of statements
?   	github.com/jenkins-x/jx/pkg/testkube	[no test files]
?   	github.com/jenkins-x/jx/pkg/tests	[no test files]
ok  	github.com/jenkins-x/jx/pkg/users	0.522s	coverage: 43.6% of statements
ok  	github.com/jenkins-x/jx/pkg/util	10.208s	coverage: 25.2% of statements
ok  	github.com/jenkins-x/jx/pkg/util/json	0.178s	coverage: 72.7% of statements
?   	github.com/jenkins-x/jx/pkg/util/mocks	[no test files]
ok  	github.com/jenkins-x/jx/pkg/util/system	0.083s	coverage: 78.9% of statements
ok  	github.com/jenkins-x/jx/pkg/vault	0.178s	coverage: 4.3% of statements
?   	github.com/jenkins-x/jx/pkg/vault/mocks	[no test files]
?   	github.com/jenkins-x/jx/pkg/vault/mocks/matchers	[no test files]
ok  	github.com/jenkins-x/jx/pkg/version	0.053s	coverage: 53.0% of statements
?   	github.com/jenkins-x/jx/pkg/workflow	[no test files]
make: *** [test-slow-integration] Error 1

```

Full log [here](https://gist.github.com/hferentschik/c1d22ad7f58ee4a2310a06f39c6ebbe2).

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

This requires deparallelizing all integration tests, since otherwise
they could result in the env vars getting unset by one test while
another test is still running. Ideally, we'd refactor
`util.ConfigDir()` and `util.KubeConfigFile()` to allow overriding
from a set variable rather than just using the environment, but I
haven't done that yet. =)

Also, might not be a bad thing to switch from leaving `JX_HOME` and
`KUBECONFIG` unset at the end of the test to instead revert to the
original value, whatever that was - if this overall approach looks
good to everyone, I'll try to go rewrite things to do that before I
take this off hold.

#### Special notes for the reviewer(s)

Relates to #3627 - that'd be a cleaner fix for the original issue of `TestImportProjects` and `TestImportProjectNextGenPipeline` failing, and should probably be done anyway, but the underlying problem of tests (mainly `TestInstallGitOps`) writing to files in `JX_HOME` in the first place. 

This is worth doing regardless of #3627 because you currently end up with your `JX_HOME` messed up if you run the integration tests locally, which is...undesirable. Side effects are bad.

/assign @hferentschik 
/assign @jstrachan 
/assign @dwnusbaum 
/assign @pmuir 

#### Which issue this PR fixes

fixes #3625

### CODE REVIEW

**Comment by abayer** [comment]
/hold

Putting on hold for full review and so I can run the integration tests like 10-15 times to make sure this actually, y'know, works.

**Comment by jstrachan** [comment]
@abayer this is AWESOME! Thank you so much!!!

**Comment by abayer** [comment]
@jstrachan - thanks. =) This pissed me off so damned much that I think I just pulled a 12 hour day to get it working - so many things I had to test to make sure it did the right thing and figure out why things didn't work etc...oy.

**Comment by abayer** [comment]
Ha, guess it doesn’t work! I’ll dig into it tomorrow.

**Comment by abayer** [comment]
There we go! Still gonna kick a few more integration runs to be sure.

/test integration

**Comment by abayer** [comment]
auuuuuugh it failed again with the original problem. What the heck.

**Comment by abayer** [comment]
Just pulled in #3627 as well.

**Comment by abayer** [comment]
Running a few more test runs to be sure...

/test integration

**Comment by abayer** [comment]
Ok, I'm feeling good about this, so...

/hold cancel

**Pull request merged**
