### PR TITLE
Adding tests to the feature: hiearchical config for prow

### PR DESCRIPTION
**Pull request by dgozalo**
#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [X] Change is covered by existing or new tests.

#### Description
Tests for the Prow config model

#### Special notes for the reviewer(s)
Closed the other PR, it did something weird after a rebase.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by pmuir** [comment]
Is this ready now?

**Comment by dgozalo** [comment]
> Is this ready now?

Yes. It should have all covered until more functionality is added.

**Comment by pmuir** [comment]
/lgtm

Let's merge this and then if there are test issues we'll discover them as we go

**Pull request merged**
