### PR TITLE
fix: lets generate a PR on the dev environment when we import a project

### PR DESCRIPTION
**Pull request by jstrachan**
so that if folks re-create the cluster and re-run boot the SourceRepository
gets recreated

### CODE REVIEW

**Comment by abayer** [comment]
@jstrachan - ok, might be worth adding something in the BDD tests to verify the PR creation/merge, maybe?

**Comment by jstrachan** [comment]
lemme add a bdd test that after the tests have completed (if gitops is enabled) we delete all the `SourceRepository` resources, re-run the dev pipeline and verify the SR's are all back again

**Comment by abayer** [comment]
Thanks!

**Comment by abayer** [comment]
Probably should add a `test-single-import` to `jx/bdd/boot-vault/ci.sh`, like this from versions:

https://github.com/jenkins-x/jenkins-x-versions/blob/master/jx/bdd/boot-lh/ci.sh#L47-L48

https://github.com/jenkins-x/jenkins-x-versions/blob/master/jx/bdd/boot-lh/ci.sh#L65

**Pull request merged**
