### PR TITLE
fix(boot): fix --dir flag

### LINKED ISSUE #6756: jx boot fails with --dir flag
### Summary 
jx boot fails with --dir flag
### Steps to reproduce the behavior
- `jx boot` to clone the repo
- switch directory
- `run jx boot --dir <used directory>`
### Expected behavior
it should work
### Actual behavior
No Jenkins X pipeline file <folder>/jenkinsx/jenkins-x-boot-config/jenkins-x.yml or no jx boot requirements file jx-requirements.yml found. You are not running this command from inside a Jenkins X Boot git clone
### Jx version

The output of `jx version` is:

```
jx                 2.0.1192
Kubernetes cluster v1.15.2
kubectl            v1.17.0
git                2.21.1
Operating System   "Fedora release 30 (Thirty)"
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Baremetal installed using kubespray
### Operating system / Environment

Operating System   "Fedora release 30 (Thirty)"

### PR DESCRIPTION
**Pull request by yelhouti**
fix(boot): fix --dir flag

use the dir flag to check for jenkins-x.yml file

#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [X] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #6756

### CODE REVIEW

**Comment by hferentschik** [comment]
@yelhouti, thanks for the pull request. Could you provide a bit more context on what this change is about? What is the bug and how does it manifest itself and how does this PR change the behaviour? 
Would be great if you could do that on the issue tracker, thanks.

**Comment by yelhouti** [comment]
@hferentschik sure, the issue tracker is github's right?

**Comment by hferentschik** [comment]
> sure, the issue tracker is github's right?

yes

**Comment by yelhouti** [comment]
@hferentschik is it possible to have access to the test results on your dashboard. I get:
Failed to authenticate: github: user "yelhouti" not in required orgs or teams
 Maybe you could grant readonly for everyone or just the author of the PR if possible. Thanks.
working on tests locally in the meantime.

**Comment by abayer** [comment]
@yelhouti - sorry, we're still working on making sure we're scrubbing secrets well enough. For what it's worth, the `bdd` failure should be gone in the rerun I just kicked off, and the `lint` failure you can reproduce locally by running `make lint` - in this case, it's a go formatting issue, which you can fix by running `make fmt`.

**Comment by yelhouti** [comment]
@abayer yes the lint i figured: was watching this https://www.quora.com/Why-does-Go-go-fmt-uses-tabs-instead-of-whitespaces XD
updating my PR. I hope the bss passes :)

**Comment by hferentschik** [comment]
@yelhouti, thanks for creating the issue and clarifying things. Much appreciated.

**Pull request merged**
