### PR TITLE
refactor(auth config): create the building blocks for refactoring the current auth config (updated data model, readers and writers)

### PR DESCRIPTION
**Pull request by ccojocar**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

Implements some building blocks for refactoring the current auth config, such as:
- Updates the config data model to reflect the current type of users and servers
- Implements readers for getting the config from a local file, environment variables and Kubernetes secrets
- Implements writers to store the config into a local file or Kubernetes secrets
- Tests which cover the added functionality

Also it implements  a fix for Git providers when created in the cluster with pipeline user 
and adds tests for git provider creation.

#### Special notes for the reviewer(s)

The Git provider fix is in the last commit.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by i0n** [comment]
@ccojocar Looks like you may need to rebase mate

**Comment by ccojocar** [comment]
Thanks @i0n! It is rebased now.

**Comment by rawlingsj** [comment]
This is great @ccojocar , I've put on hold as I'm doing some manual testing creating clusters with prow enabled to verify things like the pipeline user and ensuring the bot get's added to new quickstart repos as collaborator etc.

One question ATM before testing different combinations, will this support folks existing `gitAuth.yaml` files or will folks need to delete it before creating new clusters, new installs or upgrade platforms?

**Comment by romainverduci** [comment]
Here is a sonar report of the code from this PR, can help improving the code and checking coverage: http://35.197.235.56:9000/dashboard?id=jx

**Comment by rawlingsj** [comment]
> If you see some more issues please point it out, I will try to temporary fix them.

Ok cool.  I guess my main interest is when I can use this PR to start testing the create cluster flows and ensure the pipeline user stuff hangs together.  ATM prow based installs are suffering hence my desire for this and happy to help out with testing etc.

**Comment by rawlingsj** [comment]
> If you see some more issues please point it out, I will try to temporary fix them.

> Ok cool. I guess my main interest is when I can use this PR to start testing the create cluster flows and ensure the pipeline user stuff hangs together. ATM prow based installs are suffering hence my desire for this and happy to help out with testing etc.

But if that's coming in a different PR to this one that's totally fine too, just expressing my interest :)

**Comment by ccojocar** [comment]
> But if that's coming in a different PR to this one that's totally fine too, just expressing my interest :)
 
I am more interested to check if this PR is not introducing any regressions. Other fixes, I can send  them in a different PR.

**Pull request merged**
