### PR TITLE
Resolved issue with jenkins x posting web hook to gitlab

### PR DESCRIPTION
**Pull request by obaroikoh**

### CODE REVIEW

**Comment by rawlingsj** [comment]
@obaroikoh awesome - thanks!  Will wait for CI to pass and will merge.

**Comment by rawlingsj** [comment]
CI failed with 
```
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO15VENDOREXPERIMENT=1 go build -ldflags " -X github.com/jenkins-x/jx/pkg/version.Version=1.0.1 -X github.com/jenkins-x/jx/pkg/version.Revision='94bfd08' -X github.com/jenkins-x/jx/pkg/version.Branch='HEAD' -X github.com/jenkins-x/jx/pkg/version.BuildDate='20180720-10:49:04' -X github.com/jenkins-x/jx/pkg/version.GoVersion='1.10.3'" -o build/linux/jx cmd/jx/jx.go
pkg/gits/gitlab.go:10:2: cannot find package "github.com/xanzy/go-gitlab" in any of:
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/xanzy/go-gitlab (vendor tree)
	/usr/local/go/src/github.com/xanzy/go-gitlab (from $GOROOT)
	/home/jenkins/go/src/github.com/xanzy/go-gitlab (from $GOPATH)
```

We need to update dep.  I can do that here though...

**Comment by obaroikoh** [comment]
Oh okay. Awesome.

**Comment by rawlingsj** [comment]
Shame looks like there's a test failure 
```
--- FAIL: TestGitlabProviderSuite (0.01s)

	gitlab_test.go:99: Escape encoded: testperson%252Ftest-project

	gitlab_test.go:100: Escape unencoded: testperson%2Ftest-project

    --- FAIL: TestGitlabProviderSuite/TestGetRepository (0.00s)

    	require.go:765: 

    			Error Trace:	gitlab_test.go:139

    			Error:      	Expected nil, but got: &errors.errorString{s:"http:/api/v4/projects/testperson%2Ftest-project"}

    			Test:       	TestGitlabProviderSuite/TestGetRepository

```

**Comment by ccojocar** [comment]
Closing this in favour of #1514.

**Pull request closed without merging**
