### PR TITLE
fix: Updating github.com/gfleury/go-bitbucket-v1 

### LINKED ISSUE #2682: jx install fails with SIGSEGV after creating default environments
### Summary 
Installing Jenkins X on a minikube kubernetes cluster with bitbucket server as git server. After helm chard deploys succesfully, segmentation violation encountered after printing `Creating default staging and production environments`.

### Steps to reproduce the behavior
1. Using minikube version 0.32.0
1. Create cluster with `minikube start --vm-driver kvm2 --cpus 8 --memory 24576 --disk-size 40g`
1. Deploy Bitbucket server to minikube cluser using manifests at https://github.com/wfhartford/bitbucket-kubernetes
1. Edit `/etc/hosts` file so that `jx.minikube.local` names are mapped to minikube host.
1. Install Jenkins X with command line:
```
jx install --provider=kubernetes --on-premise --git-provider-url=http://bitbucket-http.bitbucket --git-provider-kind=bitbucketserver --git-api-token=[redacted] --git-username=jenkins --domain=minikube.local
```
1. Accept default options for prompts
1. Wait for all pods to come up.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.728
jenkins x platform 0.0.3193
Kubernetes cluster v1.12.4
kubectl            v1.13.1
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.17.1
Operating System   Linux Mint 19.1 Tessa
```

### Kubernetes cluster

Minikube: `minikube start --vm-driver kvm2 --cpus 8 --memory 24576 --disk-size 40g`

### Operating system / Environment

Linux Mint 19.1

### Expected behavior
The `jx install` command completes successfully.

### Actual behavior
Output of `jx install`:
```
Namespace jx created 
 Using helmBinary helm with feature flag: none
Context "minikube" modified.
Storing the kubernetes provider kubernetes in the TeamSettings
Git configured for user: Wesley Hartford and email wesley@ze.com
Using helm2
Configuring tiller
Tiller Deployment is running in namespace kube-system
nginx ingress controller already enabled
Lets set up a Git user name and API token to be able to perform CI/CD

? Do you wish to use jenkins as the local Git user for http://bitbucket-http.bitbucket server: (Y/? Do you wish to use jenkins as the local Git user for http://bitbucket-http.bitbucket server: Yes
Select the CI/CD pipelines Git server and user
? Do you wish to use http://bitbucket-http.bitbucket as the pipelines Git server: Yes
? Do you wish to use jenkins as the pipelines Git user for http://bitbucket-http.bitbucket server:? Do you wish to use jenkins as the pipelines Git user for http://bitbucket-http.bitbucket server: Yes
Setting the pipelines Git server http://bitbucket-http.bitbucket and user name jenkins.
Saving the Git authentication configurationCurrent configuration dir: /home/wesley/.jx
options.Flags.CloudEnvRepository: https://github.com/jenkins-x/cloud-environments
options.Flags.LocalCloudEnvironment: false
Cloning the Jenkins X cloud environments repo to /home/wesley/.jx/cloud-environments
? A local Jenkins X cloud environments repository already exists, recreate with latest? Yes
Current configuration dir: /home/wesley/.jx
options.Flags.CloudEnvRepository: https://github.com/jenkins-x/cloud-environments
options.Flags.LocalCloudEnvironment: false
Cloning the Jenkins X cloud environments repo to /home/wesley/.jx/cloud-environments
Enumerating objects: 1289, done.
Total 1289 (delta 0), reused 0 (delta 0), pack-reused 1289
No default password set, generating a random one
Generated helm values /home/wesley/.jx/extraValues.yaml
Creating Secret jx-install-config in namespace jx
Installing Jenkins X platform helm chart from: /home/wesley/.jx/cloud-environments/env-kubernetes
? Select Jenkins installation type: Static Master Jenkins
Waiting for tiller pod to be ready, service account name is tiller, namespace is jx, tiller namespace is kube-system
Waiting for cluster role binding to be defined, named tiller-role-binding in namespace jx
 tiller cluster role defined: cluster-admin in namespace jx
tiller pod running
? Pick workload build pack:  Kubernetes Workloads: Automated CI+CD with GitOps Promotion
Setting the team build pack to kubernetes-workloads repo: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git ref: master
Installing jx into namespace jx
Adding values file /home/wesley/.jx/cloud-environments/env-kubernetes/myvalues.yaml
Adding values file /home/wesley/.jx/adminSecrets.yaml
Adding values file /home/wesley/.jx/extraValues.yaml
Adding values file /home/wesley/.jx/cloud-environments/env-kubernetes/secrets.yaml
Upgrading Chart 'upgrade --namespace jx --install --timeout 6000 --version 0.0.3193 --values /home/wesley/.jx/cloud-environments/env-kubernetes/myvalues.yaml --values /home/wesley/.jx/adminSecrets.yaml --values /home/wesley/.jx/extraValues.yaml --values /home/wesley/.jx/cloud-environments/env-kubernetes/secrets.yaml jenkins-x jenkins-x/jenkins-x-platform'
waiting for install to be ready, if this is the first time then it will take a while to download images
Jenkins X deployments ready in namespace jx


	********************************************************

	     NOTE: Your admin password is: [redacted]

	********************************************************

	
Getting Jenkins API Token
Created user admin API Token for Jenkins server jenkins.jx.minikube.local at http://jenkins.jx.minikube.local
Updating Jenkins with new external URL details http://jenkins.jx.minikube.local
Creating default staging and production environments
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x11a3fa0]

goroutine 1 [running]:
github.com/gfleury/go-bitbucket-v1.NewBitbucketAPIResponse(0x0, 0xc000b23a00, 0x0, 0x2f78060)
	/home/jenkins/go/pkg/mod/github.com/gfleury/go-bitbucket-v1@v0.0.0-20181102191809-4910839b609e/api_response.go:319 +0x50
github.com/gfleury/go-bitbucket-v1.(*DefaultApiService).GetProjects(0xc0009a7928, 0xc0010614c8, 0x0, 0x0, 0x0)
	/home/jenkins/go/pkg/mod/github.com/gfleury/go-bitbucket-v1@v0.0.0-20181102191809-4910839b609e/default_api.go:5378 +0x6ae
github.com/jenkins-x/jx/pkg/gits.(*BitbucketServerProvider).ListOrganisations(0xc0010872b0, 0x0, 0x0, 0x0, 0x1, 0xc000a43090)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/gits/bitbucket_server.go:148 +0x321
github.com/jenkins-x/jx/pkg/gits.GetOrganizations(0x7f55a9192f40, 0xc0010872b0, 0xc000546e70, 0x7, 0xc0010872b0, 0xc0010872b0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/gits/provider.go:280 +0x6f
github.com/jenkins-x/jx/pkg/jx/cmd.(*InstallOptions).buildGitRepositoryOptionsForEnvironments(0xc0002b3900, 0x35, 0x2b8d759, 0x2)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/install.go:1209 +0x2b2
github.com/jenkins-x/jx/pkg/jx/cmd.(*InstallOptions).createEnvironments(0xc0002b3900, 0x2b8d759, 0x2, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/install.go:2028 +0x17b
github.com/jenkins-x/jx/pkg/jx/cmd.(*InstallOptions).Run(0xc0002b3900, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/install.go:560 +0xd45
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdInstall.func1(0xc000331400, 0xc00057ea80, 0x0, 0x7)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/install.go:254 +0x70
github.com/spf13/cobra.(*Command).execute(0xc000331400, 0xc00057e9a0, 0x7, 0x7, 0xc000331400, 0xc00057e9a0)
	/home/jenkins/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0xc00080c000, 0x0, 0x0, 0x0)
	/home/jenkins/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xc00080c000, 0xc0004d34a0, 0x2f85ea0)
	/home/jenkins/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc0007a9f88, 0xc0000c2058)
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:17 +0xed
main.main()
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x22
```

### PR DESCRIPTION
**Pull request by gfleury**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description
Updating github.com/gfleury/go-bitbucket-v1 and fix #2682

#### Special notes for the reviewer(s)
Cherrypicking 40be834a789b2a44a3159350cc31a7e917f71184 into master allows you to reproduce the error with the test. The second commit updates the broken lib and some changes on structures. 

#### Which issue this PR fixes

fixes #2682

### CODE REVIEW

**Comment by hferentschik** [comment]
@gfleury thanks for the pull request.  Could you maybe squash the commits and use a commit message using the conventional commits format? We are enforcing this format since we use the commit message metadata to create changelogs.

See also https://jenkins-x.io/docs/contributing/code/#the-commit-message

**Comment by hferentschik** [comment]
BTW, you want to check in your `go.sum` as well.

**Comment by abayer** [comment]
@gfleury - more specifically, the commit message should start with, in this case, `fix: ...`, and the commit [needs to be signed off](https://jenkins-x.io/docs/contributing/code/#signoff). Thanks for the contribution, and thanks for your work on go-bitbucket!

**Pull request merged**
