### PR TITLE
fix: Docker auth use prompted secret

### LINKED ISSUE #7286: jx create docker auth doesn't use prompted secret
### Summary 

In the `jx create docker auth` command : 
If you specify a secret on the command line, it will be used.
If you don't, it prompts a value but it's not used.

### Steps to reproduce the behavior

- Run `jx create docker auth --host="xxx" --user="xxx"`
- It will prompt a secret but the value will never be used.

### Expected behavior

It uses the prompted value to create the secret.

### Actual behavior

It uses an empty value.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.1.45
Kubernetes cluster v1.17.4
kubectl            v1.13.2
helm client        2.12.2
git                2.17.1
Operating System   Ubuntu 18.04.4 LTS
```

### Kubernetes cluster

On premise

### Operating system / Environment

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

### PR DESCRIPTION
**Pull request by AntoineFr**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

If you specify a secret on the command line, it will be used.
If you don't, it prompts a value but it was not used.

#### Which issue this PR fixes

fixes #7286 
Related to #7203

### CODE REVIEW

**Comment by hferentschik** [comment]
@AntoineFr, thanks for the pull request. Much appreciated. Could you maybe rework your commit message using the conventional commit message format? We are enforcing this format since we use the commit message to, amongst other things,  create changelogs - see https://jenkins-x.io/community/code/#the-commit-message. Thanks.

**Comment by AntoineFr** [comment]
> @AntoineFr, thanks for the pull request. Much appreciated. Could you maybe rework your commit message using the conventional commit message format? We are enforcing this format since we use the commit message to, amongst other things, create changelogs - see https://jenkins-x.io/community/code/#the-commit-message. Thanks.

@hferentschik it should be better :)

**Pull request merged**
