### PR TITLE
Add missing calls to t.Parallel() in unit tests

### PR DESCRIPTION
**Pull request by waigani**
Use Codelingo to automatically add missing calls to t.Parallel following the
JX guidelines in CONTRIBUTING.MD.

This patch was generated by running the Codelingo Rewrite Flow over the "parallel-in-tests" Tenet:
https://github.com/codelingo/codelingo/blob/master/tenets/codelingo/jenkinsx/parallel-in-tests/codelingo.yaml. Note: the same Tenet can be used to automate PR reviews and generate guideline docs.

### CODE REVIEW

**Comment by ccojocar** [comment]
@i0n Please could you have a look at this PR?

**Comment by ccojocar** [comment]
@waigani There are a number of unit tests which are failing when run in parallel. I think, we tried in the past to parallelise  them but sill some work is required on `jx` side in order to get all of them green when executed in parallel. I will past here the failed tests:

```
--- FAIL: TestListRepos (0.08s)
    helm_cli_test.go:136: 
        	Error Trace:	helm_cli_test.go:136
        	Error:      	Not equal: 
        	            	expected: 3
        	            	actual  : 0
        	Test:       	TestListRepos
        	Messages:   	should list the same number of repos
FAIL
coverage: 33.7% of statements
FAIL	github.com/jenkins-x/jx/pkg/helm	0.731s
```

```
Environment binding doesn't exist for role ColourInfo , creating it.
Error: Command failed  noSuchCommand 
Error: Command failed  echo foo
--- FAIL: TestNonVerboseOutput (0.00s)
    common_commands_test.go:57: 
        	Error Trace:	common_commands_test.go:57
        	Error:      	Received unexpected error:
        	            	exec: "echo": executable file not found in $PATH
        	Test:       	TestNonVerboseOutput
        	Messages:   	Should not error
Error: Command failed  echo foo
replacing placeholders in directory /tmp/test-replace-placeholders651736843
app name: bar, git server: github.com, org: foo, Docker registry org: registry-org
Error: Command failed  echo foo
--- FAIL: TestExecuteCommand (0.00s)
    common_commands_test.go:17: 
        	Error Trace:	common_commands_test.go:17
        	Error:      	Expected nil, but got: &exec.Error{Name:"echo", Err:(*errors.errorString)(0xc0000966c0)}
        	Test:       	TestExecuteCommand
Generated split repos in: /tmp/test_split_monorepo689940341
Generated file ColourInfo
Generated file ColourInfo
Generated file ColourInfo
Generated file ColourInfo
--- FAIL: TestVerboseOutput (0.01s)
    common_commands_test.go:47: 
        	Error Trace:	common_commands_test.go:47
        	Error:      	Received unexpected error:
        	            	exec: "echo": executable file not found in $PATH
        	Test:       	TestVerboseOutput
        	Messages:   	Should not error
    common_commands_test.go:48: 
        	Error Trace:	common_commands_test.go:48
        	Error:      	Not equal: 
        	            	expected: "foo\r"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-foo
        	            	+
        	Test:       	TestVerboseOutput
Job already exists in Jenkins at 
Jenkins X checks passed for Cluster(): 1 nodes, memory 0% of 10G, cpu 0% of 10. Jenkins is running at http://jenkins.testorama.com
Tag v1.2.3 created and pushed to remote origin
```

You can execute the failed tests locally with:
`make test-slow-integration`

**Comment by ccojocar** [comment]
@michaelneale I got the point that the code was generated. The only thing what I am saying is that we have to fix the failed tests to run in parallel or run them sequentially until they are fixed.  

I'll try to have a look to them today. Maybe I can fix them.

**Comment by michaelneale** [comment]
@ccojocar gotcha - yes would be nice if it can work parallel

**Comment by ccojocar** [comment]
@waigani @michaelneale  I have done some work in order to get the tests running in parallel but we still have a number of issues which needs to be fixed:
- mocking framework seems to have a race condition when executed in parallel: https://github.com/petergtz/pegomock/blob/9750219ad78bfad9ba455ed537b518397a675228/dsl.go#L366 cc @i0n 
- there are some tests which calls the `os.Setenv` at OS level. It seems that they reset each other configuration when executed in parallel 
- There are also tests randomly failing in different palace

I think for now, we should close this PR and enable the parallel tests gradually, otherwise we will introduce some instability which it will make merging PRs difficult. 

cc @jstrachan @rawlingsj

**Comment by waigani** [comment]
@ccojocar where can I see the test output? I'd be happy to narrow down the subset of tests that do pass.

**Comment by ccojocar** [comment]
@waigani We build this repository with `prow/serverless Jenkins` which does not have a public UI/Dashboard at the moment. We use internally KubeCD (https://www.cloudbees.com/cloudbees-kube-cd) to visualize the results.

**Comment by ccojocar** [comment]
@waigani You can always run locally the test with `make test && make test-slow-intergration`.  You should see the errors.

**Comment by waigani** [comment]
@ccojocar I commented out two more calls to t.Parallel() and the rest are passing, see below. So that's 6 units out of 67 that we couldn't add t.Parallel() to.

This is also assuming the integration tests you're hitting are not intermittent (running tests several times locally I didn't hit them).

```
 (codelingo-autofix-parallel) jesse@zoe:~/go/src/github.com/waigani/jx$ time make test
?   	github.com/jenkins-x/jx/cmd/ip	[no test files]
?   	github.com/jenkins-x/jx/cmd/jx	[no test files]
?   	github.com/jenkins-x/jx/cmd/jx/app	[no test files]
?   	github.com/jenkins-x/jx/pkg/addon	[no test files]
?   	github.com/jenkins-x/jx/pkg/apis/jenkins.io	[no test files]
?   	github.com/jenkins-x/jx/pkg/apis/jenkins.io/v1	[no test files]
ok  	github.com/jenkins-x/jx/pkg/auth	0.005s	coverage: 24.2% of statements
ok  	github.com/jenkins-x/jx/pkg/binaries	0.011s	coverage: 55.6% of statements
ok  	github.com/jenkins-x/jx/pkg/builds	0.053s	coverage: 77.0% of statements
?   	github.com/jenkins-x/jx/pkg/chats	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/clientset/versioned	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/clientset/versioned/fake	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/clientset/versioned/scheme	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/clientset/versioned/typed/jenkins.io/v1	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/clientset/versioned/typed/jenkins.io/v1/fake	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/informers/externalversions	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/informers/externalversions/internalinterfaces	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/informers/externalversions/jenkins.io	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/informers/externalversions/jenkins.io/v1	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/listers/jenkins.io/v1	[no test files]
?   	github.com/jenkins-x/jx/pkg/cloud/aks	[no test files]
ok  	github.com/jenkins-x/jx/pkg/cloud/amazon	0.058s	coverage: 10.4% of statements
ok  	github.com/jenkins-x/jx/pkg/cloud/gke	0.030s	coverage: 0.4% of statements
?   	github.com/jenkins-x/jx/pkg/cloud/iks	[no test files]
?   	github.com/jenkins-x/jx/pkg/cloud/oke	[no test files]
ok  	github.com/jenkins-x/jx/pkg/config	0.029s	coverage: 32.3% of statements
ok  	github.com/jenkins-x/jx/pkg/cve	0.021s	coverage: 0.0% of statements
?   	github.com/jenkins-x/jx/pkg/draft	[no test files]
?   	github.com/jenkins-x/jx/pkg/extensions	[no test files]
ok  	github.com/jenkins-x/jx/pkg/gits	0.109s	coverage: 2.3% of statements
?   	github.com/jenkins-x/jx/pkg/gits/mocks	[no test files]
ok  	github.com/jenkins-x/jx/pkg/helm	0.054s	coverage: 34.5% of statements
?   	github.com/jenkins-x/jx/pkg/helm/mocks	[no test files]
?   	github.com/jenkins-x/jx/pkg/issues	[no test files]
?   	github.com/jenkins-x/jx/pkg/jenkins	[no test files]
ok  	github.com/jenkins-x/jx/pkg/jx/cmd	16.472s	coverage: 5.2% of statements
?   	github.com/jenkins-x/jx/pkg/jx/cmd/certmanager	[no test files]
?   	github.com/jenkins-x/jx/pkg/jx/cmd/mocks	[no test files]
?   	github.com/jenkins-x/jx/pkg/jx/cmd/mocks/matchers	[no test files]
?   	github.com/jenkins-x/jx/pkg/jx/cmd/templates	[no test files]
ok  	github.com/jenkins-x/jx/pkg/kube	0.068s	coverage: 26.0% of statements
?   	github.com/jenkins-x/jx/pkg/kube/mocks	[no test files]
?   	github.com/jenkins-x/jx/pkg/log	[no test files]
?   	github.com/jenkins-x/jx/pkg/maven	[no test files]
?   	github.com/jenkins-x/jx/pkg/nodes	[no test files]
?   	github.com/jenkins-x/jx/pkg/pipeline_events	[no test files]
ok  	github.com/jenkins-x/jx/pkg/prow	0.073s	coverage: 79.8% of statements
ok  	github.com/jenkins-x/jx/pkg/quickstarts	0.052s	coverage: 18.4% of statements
ok  	github.com/jenkins-x/jx/pkg/reports	0.010s	coverage: 39.7% of statements
?   	github.com/jenkins-x/jx/pkg/spring	[no test files]
?   	github.com/jenkins-x/jx/pkg/table	[no test files]
?   	github.com/jenkins-x/jx/pkg/terraform	[no test files]
?   	github.com/jenkins-x/jx/pkg/testkube	[no test files]
?   	github.com/jenkins-x/jx/pkg/tests	[no test files]
ok  	github.com/jenkins-x/jx/pkg/util	1.426s	coverage: 21.0% of statements
?   	github.com/jenkins-x/jx/pkg/util/mocks	[no test files]
ok  	github.com/jenkins-x/jx/pkg/version	0.011s	coverage: 40.0% of statements
?   	github.com/jenkins-x/jx/pkg/workflow	[no test files]

real	0m44.543s
user	1m0.869s
sys	0m7.752s
```

```
(codelingo-autofix-parallel) jesse@zoe:~/go/src/github.com/waigani/jx$ time make test-slow-integration
?   	github.com/jenkins-x/jx/cmd/ip	[no test files]
?   	github.com/jenkins-x/jx/cmd/jx	[no test files]
?   	github.com/jenkins-x/jx/cmd/jx/app	[no test files]
?   	github.com/jenkins-x/jx/pkg/addon	[no test files]
?   	github.com/jenkins-x/jx/pkg/apis/jenkins.io	[no test files]
?   	github.com/jenkins-x/jx/pkg/apis/jenkins.io/v1	[no test files]
ok  	github.com/jenkins-x/jx/pkg/auth	0.038s	coverage: 24.2% of statements
ok  	github.com/jenkins-x/jx/pkg/binaries	0.010s	coverage: 55.6% of statements
ok  	github.com/jenkins-x/jx/pkg/builds	0.058s	coverage: 77.0% of statements
?   	github.com/jenkins-x/jx/pkg/chats	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/clientset/versioned	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/clientset/versioned/fake	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/clientset/versioned/scheme	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/clientset/versioned/typed/jenkins.io/v1	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/clientset/versioned/typed/jenkins.io/v1/fake	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/informers/externalversions	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/informers/externalversions/internalinterfaces	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/informers/externalversions/jenkins.io	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/informers/externalversions/jenkins.io/v1	[no test files]
?   	github.com/jenkins-x/jx/pkg/client/listers/jenkins.io/v1	[no test files]
?   	github.com/jenkins-x/jx/pkg/cloud/aks	[no test files]
ok  	github.com/jenkins-x/jx/pkg/cloud/amazon	0.017s	coverage: 10.4% of statements
ok  	github.com/jenkins-x/jx/pkg/cloud/gke	0.020s	coverage: 0.4% of statements
?   	github.com/jenkins-x/jx/pkg/cloud/iks	[no test files]
?   	github.com/jenkins-x/jx/pkg/cloud/oke	[no test files]
ok  	github.com/jenkins-x/jx/pkg/config	0.038s	coverage: 32.3% of statements
ok  	github.com/jenkins-x/jx/pkg/cve	0.025s	coverage: 43.0% of statements
?   	github.com/jenkins-x/jx/pkg/draft	[no test files]
?   	github.com/jenkins-x/jx/pkg/extensions	[no test files]
ok  	github.com/jenkins-x/jx/pkg/gits	60.144s	coverage: 22.3% of statements
?   	github.com/jenkins-x/jx/pkg/gits/mocks	[no test files]
ok  	github.com/jenkins-x/jx/pkg/helm	0.052s	coverage: 34.5% of statements
?   	github.com/jenkins-x/jx/pkg/helm/mocks	[no test files]
?   	github.com/jenkins-x/jx/pkg/issues	[no test files]
?   	github.com/jenkins-x/jx/pkg/jenkins	[no test files]
ok  	github.com/jenkins-x/jx/pkg/jx/cmd	151.273s	coverage: 9.9% of statements
?   	github.com/jenkins-x/jx/pkg/jx/cmd/certmanager	[no test files]
?   	github.com/jenkins-x/jx/pkg/jx/cmd/mocks	[no test files]
?   	github.com/jenkins-x/jx/pkg/jx/cmd/mocks/matchers	[no test files]
?   	github.com/jenkins-x/jx/pkg/jx/cmd/templates	[no test files]
ok  	github.com/jenkins-x/jx/pkg/kube	0.165s	coverage: 27.7% of statements
?   	github.com/jenkins-x/jx/pkg/kube/mocks	[no test files]
?   	github.com/jenkins-x/jx/pkg/log	[no test files]
?   	github.com/jenkins-x/jx/pkg/maven	[no test files]
?   	github.com/jenkins-x/jx/pkg/nodes	[no test files]
?   	github.com/jenkins-x/jx/pkg/pipeline_events	[no test files]
ok  	github.com/jenkins-x/jx/pkg/prow	0.059s	coverage: 79.8% of statements
ok  	github.com/jenkins-x/jx/pkg/quickstarts	0.008s	coverage: 18.4% of statements
ok  	github.com/jenkins-x/jx/pkg/reports	0.003s	coverage: 39.7% of statements
?   	github.com/jenkins-x/jx/pkg/spring	[no test files]
?   	github.com/jenkins-x/jx/pkg/table	[no test files]
?   	github.com/jenkins-x/jx/pkg/terraform	[no test files]
?   	github.com/jenkins-x/jx/pkg/testkube	[no test files]
?   	github.com/jenkins-x/jx/pkg/tests	[no test files]
ok  	github.com/jenkins-x/jx/pkg/util	1.468s	coverage: 21.0% of statements
?   	github.com/jenkins-x/jx/pkg/util/mocks	[no test files]
ok  	github.com/jenkins-x/jx/pkg/version	0.002s	coverage: 40.0% of statements
?   	github.com/jenkins-x/jx/pkg/workflow	[no test files]

real	2m52.475s
user	0m56.677s
sys	0m7.219s
```

**Comment by ccojocar** [comment]
Closing this PR since has a lots of conflicts in the meantime. We can try to add the missing Parallel calls in a new PR. Thanks

**Pull request closed without merging**
