### PR TITLE
fix: skip waitForGitOps on PR if --no-merge

### LINKED ISSUE #5081: Promoting with `--no-merge` will fail the build
### Summary 
Having a `jx promote -b --no-merge --env production --timeout 1h` will cause the build to fail after the defined timeout. Likely to be stuck at `waitForGitOpsPullRequest`. 

### Steps to reproduce the behavior
I have a build pipeline that promotes to both `staging` and `production` but will not merge on `production` as it has prow to wait for team members to review with `approve` and `lgtm` labels before proceeding to merge.

### Expected behavior
Should skip `waitForGitOpsPullRequest` if `--no-merge` is defined.

### Jx version

The output of `jx version` is:

```
jx                 2.0.561
jenkins x platform 2.0.942
Kubernetes cluster v1.12.9
kubectl            v1.15.0
helm client        Client: v2.14.1+g5270352
git                2.19.1
Operating System   Mac OS X 10.14 build 18A391
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

AWS + KOPS

### PR DESCRIPTION
**Pull request by cpwc**
Signed-off-by: Wei Cheng <calvinpohwc@gmail.com>

#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description
Not very familiar with the whole `promote` flow. Would love to get some feedback if I am doing the correct thing to skip `waitForGitOps` if `NoMergePullRequest` is `true`.

If I am in the right direction will proceed to add in suitable test cases.

#### Which issue this PR fixes

fixes #5081

### CODE REVIEW

**Comment by pmuir** [comment]
/hold
See my comment on the issue
/ok-to-test

**Comment by cpwc** [comment]
Closing as `--no-poll` already gave the same behaviour we are looking for. @pmuir suggested we should update the docs to make a note to specify both `--no-merge` and `--no-poll` if `--no-merge` is used.

/close

**Pull request closed without merging**
