### PR TITLE
fix: boot upgrade cloning using GitHub apps

### LINKED ISSUE #6276: Upgrade boot fails with GitHub Apps enabled
### Summary 

When GitHub App is enabled `jx upgrade boot` is failing as it attempts to clone the dev environment repo using the pipeline bot user personal access token, rather than the GitHub App token.

### PR DESCRIPTION
**Pull request by macox**
Signed-off-by: Mark Cox <markcox20@hotmail.com>

#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

`jx upgrade boot` is failing to clone dev env repository when using GitHub apps. This change determines if GitHub App is enabled and configured so that the appropriate token can be used.

If no GitHub App owner is found then the auth flow continues as before.

fixes #6276

### CODE REVIEW

**Comment by hferentschik** [comment]
> jx upgrade boot is failing to clone when using github apps

Could you provide more context? How does this fail with GitHub App and what does this fix change? Does that have any effect on non GitHub App use?

**Comment by macox** [comment]
> > jx upgrade boot is failing to clone when using github apps
> 
> Could you provide more context? How does this fail with GitHub App and what does this fix change? Does that have any effect on non GitHub App use?

yes will do, it's a WIP at the moment as I'm testing non GitHub App use before providing more context

**Pull request merged**
