### PR TITLE
jx get preview --current should print the url

### PR DESCRIPTION
**Pull request by heroic**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description
`jx get preview --current` currently logs the url. We should print it so that it's easy for scripts to capture the output.

### CODE REVIEW

**Comment by pmuir** [comment]
@heroic needs conflicts resolving

**Comment by heroic** [comment]
> @heroic needs conflicts resolving

done!

**Pull request merged**
