### PR TITLE
fix: support add an app from git repository

### PR DESCRIPTION
**Pull request by nodece**
Signed-off-by: Zixuan Liu <nodeces@gmail.com>

#### Description

The feature supports add an app from git respository.

example:
```
jx add app https://github.com/jenkins-x-apps/jx-app-kubeless.git
```

### CODE REVIEW

**Comment by nodece** [comment]
@rawlingsj because I don't have access permission, so I can't get the test details, could you provides the test details?

**Comment by rawlingsj** [comment]
@nodece sure thing, here is the unit test failure:
```
        pull_request_op_test.go:661: 
            	Error Trace:	pull_request_op_test.go:661
            	Error:      	[]string(nil) does not contain "1.0.0"
            	Test:       	TestCreateChartChangeFilesFn/from-chart-sources
        files.go:27: 
            	Error Trace:	files.go:27
            	            				pull_request_op_test.go:662
            	Error:      	Should be true
            	Test:       	TestCreateChartChangeFilesFn/from-chart-sources
            	Messages:   	The file /tmp/524835426/charts/acme/roadrunner.yml does not contain text: version: 1.0.1
        pull_request_op_test.go:663: 
            	Error Trace:	pull_request_op_test.go:663
            	Error:      	Not equal: 
            	            	expected: "https://fake.git/acme/roadrunner"
            	            	actual  : ""
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1 +1 @@
            	            	-https://fake.git/acme/roadrunner
            	            	+
            	Test:       	TestCreateChartChangeFilesFn/from-chart-sources
FAIL
```

**Comment by nodece** [comment]
@rawlingsj okay, I updated my code.

**Comment by nodece** [comment]
It looks like a network failure.

**Pull request merged**
