### PR TITLE
use Jenkins X image for git merges now that it has been released fixe…

### PR DESCRIPTION
**Pull request by rawlingsj**
…s #4131

Signed-off-by: rawlingsj <rawlingsj80@gmail.com>

### CODE REVIEW

**Comment by hferentschik** [comment]
-10% code coverage due to this change? That does not seem right, or?

**Comment by hferentschik** [comment]
@rawlingsj, step_create_task_test.go will need updating. The tests assert against fully generated Tekton CRDs leading to failures like this:

```
=== FAIL: pkg/jx/cmd/step/create TestGenerateTektonCRDs/js_build_pack (0.04s)
    --- FAIL: TestGenerateTektonCRDs/js_build_pack (0.04s)
        step_create_task_test.go:376: Generated Tasks did not match expected: 
            {*v1alpha1.TaskList}.Items[0].Spec.Steps[0].Image:
                -: "rawlingsj/builder-jx:wip34"
                +: "gcr.io/jenkinsxio/builder-jx:0.1.477"
```

All the test data files will need updating.

**Comment by abayer** [comment]
@hferentschik @rawlingsj - just pushed fixed `tasks.yml`s to @rawlingsj's branch.

**Comment by hferentschik** [comment]
this PR also needs a rebase now

**Comment by abayer** [comment]
I’ll fix that up today.

**Pull request merged**
