### PR TITLE
feat: use the docker image that we just built as step image in pipelines

### PR DESCRIPTION
**Pull request by fiunchinho**
#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [X] Change is covered by existing or new tests.

#### Description
When running e2e tests, Instead of copying the jx binary with the PR changes into an old jx docker image, use the docker image build and pushed by the pipeline.

#### Special notes for the reviewer(s)
I've also replaced the references to Docker Hub registry with Google Cloud Registry.

### CODE REVIEW

**Comment by abayer** [comment]
Error pushing:
```
error pushing image: failed to push to destination gcr.io/jenkinsxio/jx:covered-0.0.0-SNAPSHOT-PR-4598-4: no token in bearer response:
{"errors":[{"code":"DENIED","message":"Token exchange failed for project 'jenkinsxio'. Caller does not have permission 'storage.buckets.get'. To configure permissions, follow instructions at: https://cloud.google.com/container-registry/docs/access-control"}]}
```

**Comment by fiunchinho** [comment]
Something like that @abayer ? I've splitted it into two stages.

**Comment by abayer** [comment]
@fiunchinho Exactly! You can put the `environment` and `options.containerOptions` on the `pipeline` rather than on the individual stages, btw, to avoid duplication.

Anyway, now the builds are still failing, but they're not hanging, so that's a positive. =)

**Comment by pmuir** [comment]
/lgtm

Very nice

**Pull request merged**
