### PR TITLE
feat: add option to customise preview timeout

### LINKED ISSUE #3530: jx preview ignores --timeout
### Summary 
doing a `jx preview` fails if deployment takes more than 300secs even if `--timeout` is provided on the CLI
### Steps to reproduce the behavior

- setup jx
- create or import a project
- in the generated Jenkinsfile in the preview section add `--timeout N` to the `jx preview` command where N > 300s
- create a pull request which triggers a preview build and make sure your successful deployment takes longer than 300s
- notice that the preview build fails even though the deployed resources turned ready in k8s within the given timeout

### Expected behavior
`jx preview` honors the given `--timeout` parameter
### Actual behavior
`jx preview` does not honor the given `--timeout` parameter.
there is a hardcoded `-1` in [preview.go](https://github.com/jenkins-x/jx/blob/969da09727dce0b48954d4d5d10d078f299915a0/pkg/jx/cmd/preview.go#L461) which instructs helm to use the default timeout which is 300s
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.1062
jenkins x platform 0.0.3673
Kubernetes cluster v1.11.7-gke.12
kubectl            v1.11.7-dispatcher
helm client        v2.10.0+g9ad53aa
helm server        v2.12.2+g7d2b0c7
git                git version 2.11.0
Operating System   Debian GNU/Linux 9.8 (stretch)
```

### Jenkins type

- [ x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster
GKE created with `jx create cluster`

### Operating system / Environment
 Debian GNU/Linux 9.8 running in Google Cloud Shell

### PR DESCRIPTION
**Pull request by shteou**
#### Description
This allows the user to specify how long they wish to wait for a
preview application to become healthy, which was previously
hardcoded to 5 minutes

#### Special notes for the reviewer(s)

I've not overloaded the --timeout parameter as per the below issue.
The --timeout param doesn't seem to be a part of the jx preview command.
(I've no idea where that's being picked up from)

Instead, I've used a more precise timeout name specific to the portion of
the preview command it affects.

If you think it's worth adding a unit test for this functionality, any pointers
would be welcome.

#### Which issue this PR fixes

fixes #3530

### CODE REVIEW

**Comment by hferentschik** [comment]
Can this failure be caused by this change:

```
=== CONT  TestCreateGitProviderFromURLForGitHubApp
    provider_githubapp_test.go:97: 
        	Error Trace:	provider_githubapp_test.go:97
        	Error:      	An error is expected but got nil.
        	Test:       	TestCreateGitProviderFromURLForGitHubApp
        	Messages:   	should fail to create provider for owner doesNotExist
    provider_githubapp_test.go:98: 
        	Error Trace:	provider_githubapp_test.go:98
        	Error:      	Expected nil, but got: &gits.GitHubProvider{Username:"test", Client:(*github.Client)(0xc00040f180), Context:(*context.emptyCtx)(0xc000042100), Server:auth.AuthServer{URL:"https://github.com", Users:[]*auth.UserAuth{(*auth.UserAuth)(0xc0003d4690), (*auth.UserAuth)(0xc0003d46e0), (*auth.UserAuth)(0xc0003d4730)}, Name:"gh", Kind:"github", CurrentUser:"owner1"}, User:auth.UserAuth{Username:"test", ApiToken:"test", BearerToken:"", Password:"", GithubAppOwner:""}, Git:(*gits_test.MockGitter)(0xc0001561a8)}
        	Test:       	TestCreateGitProviderFromURLForGitHubApp
        	Messages:   	created provider should be nil for owner doesNotExist
```

**Comment by abayer** [comment]
@hferentschik - I saw it show up on #6188 as well, so I think it's something recently added that's flaky.

**Pull request merged**
