### PR TITLE
Ignore flagger canary auxiliary deployments from get apps

### PR DESCRIPTION
**Pull request by carlossg**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

Flagger creates new deployments to manage canaries and they get printed in `jx get apps`

    ```
    $ jx get apps
    APPLICATION                  STAGING PODS URL                                                 PRODUCTION PODS URL
    croc-hunter-jenkinsx         0.0.126 1/1  https://croc-hunter-jenkinsx.jx-staging.example.com 0.0.126         http://croc-hunter-jenkinsx.jx-production.example.com
    croc-hunter-jenkinsx-primary
    ```

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by carlossg** [comment]
error looks unrelated

```
Created Pull Request: ColourInfo
Delete app via Pull Request 
.Error: Command failed  noSuchCommand 
```

**Comment by jstrachan** [comment]
@carlossg I wonder if you could rebase please? we disabled a flaky test which is currently failing

**Comment by pmuir** [comment]
/test
/hold
Holding PRs as we have a big refactor to get in first

**Comment by pmuir** [comment]
/lgtm
/test this
Last build worked I think

**Comment by pmuir** [comment]
Looks like generation needs running

**Comment by carlossg** [comment]
the diff in the build log just shows a bunch of formatting differences, and I did run `make generate`

**Comment by carlossg** [comment]
build is passing now, needs approval

**Pull request merged**
