### PR TITLE
feat: list pods instead of namespaces to avoid needing a cluster-wide permission

### LINKED ISSUE #7060: Modify the way the code checks that the user is connected to a cluster
### Summary 
Right now, the code attempts to list all the namespaces to check that the user is connected to a cluster.

This is not possible when you booting with limited permissions as this needs a cluster wide permission.

In Openshift, the user that will be booting could have very limited permissions and not be able to list namespaces other than the ones created by Jenkins X.

### Steps to reproduce the behavior
Create an Openshift cluster, create an user with very limited permissions (no cluster-wide permissions) and attempt to run `jx boot`.

### Expected behavior
It should correctly check that the user is connected to an Openshift cluster.

### Actual behavior
It fails because the user doesn't have any cluster-wide permissions can't and list namespaces at a cluster scope.

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### PR DESCRIPTION
**Pull request by dgozalo**
#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [X] Change is covered by existing or new tests.

#### Description
Listing namespaces requires a `clusterrole`. It will fail for clusters with tight permission restrictions, so we should list a resource that is local to a namespace.

#### Which issue this PR fixes

fixes #7060

### CODE REVIEW

**Comment by hferentschik** [comment]
@dgozalo - what's the state on this one? Is this still wip?

**Comment by dgozalo** [comment]
> @dgozalo - what's the state on this one? Is this still wip?

It should be ready to go now.

**Comment by hferentschik** [comment]
> It should be ready to go now.

@dgozalo do you want to take the 'wip' off?

**Pull request merged**
