### PR TITLE
Feat: add app from local path

### PR DESCRIPTION
**Pull request by pmuir**
Support for `jx add app /path/to/chart`

#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by rawlingsj** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **pmuir**

If they are not already assigned, you can assign the PR to them by writing `/assign @pmuir` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=jenkins-x%2Fjx).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/jenkins-x/jx/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jstrachan** [comment]
looks like this fails a test...
```
--- FAIL: TestUpgradeAppForGitOps (0.15s)
    upgrade_apps_test.go:57: 
        	Error Trace:	upgrade_apps_test.go:57
        	Error:      	Received unexpected error:
        	            	open /tmp/jx-helm-fetch-5bd7c1aa-37d8-4f28-9a9c-0ac8dfc4af20-114734014/5bd7c1aa-37d8-4f28-9a9c-0ac8dfc4af20/Chart.yaml: no such file or directory
        	            	error loading chart from /tmp/jx-helm-fetch-5bd7c1aa-37d8-4f28-9a9c-0ac8dfc4af20-114734014/5bd7c1aa-37d8-4f28-9a9c-0ac8dfc4af20
        	            	github.com/jenkins-x/jx/pkg/apps.(*InstallOptions).createInterrogateChartFn.func1
        	            		/workspace/pkg/apps/install.go:243
        	            	github.com/jenkins-x/jx/pkg/apps.(*GitOpsOptions).UpgradeApp.func2
        	            		/workspace/pkg/apps/gitops.go:75
```

**Comment by pmuir** [comment]
Ah yeah, tests are worth it!

**Comment by ccojocar** [comment]
@pmuir Please could you rebase this? Thanks

**Comment by rawlingsj** [comment]
while we move releases to new infra
/hold
/override serverless-jenkins

**Comment by ccojocar** [comment]
@pmuir This PR needs a rebase. Thanks!

**Comment by pmuir** [comment]
@ccojocar Haha, I had forgotten entirely about this PR - I just found it!

**Pull request merged**
