### PR TITLE
fix: looking up vault URL when incluster

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by abayer** [comment]
fyi - `boot-vault` failure smells legit:

```
panic: running ** get quickstarts, output was Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
error: failed to load quickstarts: wait for vault to be initialized and unsealed: reading vault health: Get http://**-vault-pr-5625-5-boo:8200/v1/sys/health?drsecondarycode=299&performancestandbycode=299&sealedcode=299&standbycode=299&uninitcode=299: dial tcp: lookup **-vault-pr-5625-5-boo on 10.15.240.10:53: no such host
: exit status 1

goroutine 1 [running]:
github.com/jenkins-x/bdd-**/test/suite/quickstart.AllQuickstartsTest(0xdf8475800, 0xc000503f68, 0x1606f25)
	/tmp/jenkins-x/bdd-**/test/suite/quickstart/helpers.go:34 +0x2bc
github.com/jenkins-x/bdd-**/test/suite/quickstart.init.ializers()
	/tmp/jenkins-x/bdd-**/test/suite/quickstart/helpers.go:24 +0x22
FAIL	github.com/jenkins-x/bdd-**/test/suite/quickstart	603.217s
make: *** [test-quickstart-golang-http] Error 1
```

It got past `boot`, but...

**Comment by rawlingsj** [comment]
damn - wonder if the jx version being used there isn't the latest that was built as part of the PR

**Comment by rawlingsj** [comment]
an extra commit has gone into this PR which I'll remove but want to check first if the boot-vault test passes
/hold

**Comment by rawlingsj** [comment]
closing in favour of working on https://github.com/jenkins-x/jx/pull/5630

**Pull request closed without merging**
