### PR TITLE
s/http://chartmuseum.jenkins-x.io/https://storage.googleapis.com/char…

### LINKED ISSUE #3828: https instead of http for chartmuseum.jenkins-x.io
### Steps to reproduce the behaviour
jx install
### Expected behaviour

to install the dependencies

### Actual behavior

Jenkins fails to install the dependencies

### Jx version
jx                 2.0.71

The output of `jx version` is:

NAME               VERSION
jx                 2.0.71
Kubernetes cluster v1.12.6-eks-d69f1b
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.17.2
Operating System   "Amazon Linux release 2 (Karoo)"

```
retrying after error:failed to run 'helm repo add jenkins-x http://chartmuseum.jenkins-x.io' command in directory '', output: 'Error: Looks like "http://chartmuseum.jenkins-x.io" is not a valid chart repository or cannot be reached: Failed to fetch http://chartmuseum.jenkins-x.io/index.yaml : 403 Forbidden'```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster
EKS
### Operating system / Environment

Amazon Linux

------

Would be possible to have an option for https not only http for the Sources?

On my environment We are behind a Firewall and We are only allowed https connections to the outside which can be very limiting.

I have been reading through the parameters but I am not sure whether I can change that behaviour as the URL seems hard-coded

Many thanks

### PR DESCRIPTION
**Pull request by rawlingsj**
…tmuseum.jenkins-x.io

fixes #3828

Signed-off-by: rawlingsj <rawlingsj80@gmail.com>

### CODE REVIEW

**Comment by rawlingsj** [comment]
hmm . - just seen the failure of the integration test..
```
=== FAIL: pkg/gits TestCreateGitProviderFromURL/create_BitbucketServer_provider_in_interactive_mode (0.01s)
    --- FAIL: TestCreateGitProviderFromURL/create_BitbucketServer_provider_in_interactive_mode (0.01s)
        console_wrapper.go:65: 
            	Error Trace:	console_wrapper.go:65
            	            				provider_test.go:615
            	            				asm_amd64.s:1337
            	Error:      	Received unexpected error:
            	            	write |1: broken pipe
            	Test:       	TestCreateGitProviderFromURL/create_BitbucketServer_provider_in_interactive_mode
            	Messages:   	Expected EOF. Got " "
```
seems a random failure, would love to catch all these in stackdriver and count how many times we get these random issues so we can prioritise them.
/test integration

**Comment by garethjevans** [comment]
@rawlingsj that is a flaky test, it seems to fail quite often - no idea why

**Comment by rawlingsj** [comment]
ah ok - wonder if we can figure out an automated way to grok flaky tests using stackdriver?

**Comment by rawlingsj** [comment]
or any other way?  not sure.

**Pull request merged**
