### PR TITLE
chore: Remove installation type from the issue template

### LINKED ISSUE #7109: Remove the "Jenkins type" section from the issue template
### Summary 

The issue template still displays a section asking for the installation type. Moving forward, the installation type should assume Tekton unless on older versions.

I am wondering if we should update the template to remove the section? 

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### PR DESCRIPTION
**Pull request by dorrab**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description
Remove installation type section from the issue template

#### Which issue this PR fixes

fixes #7109

### CODE REVIEW

**Comment by cagiti** [comment]
I'm not sure this is a good idea yet, people may still be raising issues for classic jenkins and we won't be aware of that

**Comment by abayer** [comment]
@dorrab - can you change your commit message and the PR title to start with `chore: ` to make the semantic pull request check happy?

**Pull request merged**
