### PR TITLE
feat: make step boot vault use the version stream defined in jx-requirements.yaml

### LINKED ISSUE #5660: jx boot upgrade: Vault operator uses existing version stream from team settings
## Summary

During the build pipeline for the PR created by the upgrade process the vault operator fails as version stream ref in the team settings is updated after the vault operator is updated.

## Acceptance Criteria
- When upgrading in a boot pipeline the version stream ref should be updated in the team settings before the vault operator is update.

### PR DESCRIPTION
**Pull request by dgozalo**
Signed-off-by: Daniel Gozalo <dgozalo@cloudbees.com>

#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [X] Change is covered by existing or new tests.

#### Description
Right now we are using the versions repo and ref defined in the team settings in the `dev` environment CRD.

We need to use the VersionsResolver created from the current `jx-requirements.yaml` instead so we can boot using the new version when upgrading the cluster. 

#### Which issue this PR fixes

fixes #5660

### CODE REVIEW

**Comment by abayer** [comment]
Looks very similar to #5741? cc @macox and @ccojocar as well

**Comment by ccojocar** [comment]
I am not sure if there is something more in the PR. I approved the  #5741.

**Comment by dgozalo** [comment]
Modified the code to include Mark's change, added the update to the versions ref in `TeamSettings`.

**Pull request merged**
