### PR TITLE
The urltemplate can be empty

### PR DESCRIPTION
**Pull request by sboardwell**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

The `urltemplate` option should not be required to have a non-empty value.

#### Special notes for the reviewer(s)

cc: @jstrachan and @amuniz 

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by rawlingsj** [comment]
the integration test failure is..
```
setting the dev namespace to: jx
--- FAIL: TestUpgradeAppForGitOps (0.00s)
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 793 [running]:
testing.tRunner.func1(0xc002060400)
	/usr/local/go/src/testing/testing.go:792 +0x387
panic(0x2f79e00, 0x6516420)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/petergtz/pegomock.(*mockedMethod).removeLastInvocation(...)
	/home/jenkins/go/pkg/mod/github.com/petergtz/pegomock@v0.0.0-20181206220228-b113d17a7e81/dsl.go:281
github.com/petergtz/pegomock.When(0xc00211cb90, 0x1, 0x1, 0x0)
	/home/jenkins/go/pkg/mod/github.com/petergtz/pegomock@v0.0.0-20181206220228-b113d17a7e81/dsl.go:401 +0x2b3
github.com/jenkins-x/jx/pkg/jx/cmd/cmd_test_helpers.CreateAppTestOptions(0xc002060401, 0xc002060400, 0x4180c18)
	/workspace/workspace/pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go:169 +0xa87
github.com/jenkins-x/jx/pkg/jx/cmd_test.TestUpgradeAppForGitOps(0xc002060400)
	/workspace/workspace/pkg/jx/cmd/upgrade_apps_test.go:28 +0x5
```
we run `make test-slow-integration` in this CI pipeline

**Comment by rawlingsj** [comment]
Though no idea why your change should cause that error

**Comment by sboardwell** [comment]
Can I do anything here?

**Comment by rawlingsj** [comment]
It's odd, let's re trigger before digging any further,
/test integration

**Comment by sboardwell** [comment]
Can I help here in any way?

**Comment by jstrachan** [comment]
@sboardwell looks like we're hitting flaky bdd tests due to our infrastructure - will try get it merged ASAP

**Comment by sboardwell** [comment]
@jstrachan, ok, no worries. No stress, happy to help fix my faux pas if I can 😉

**Comment by sboardwell** [comment]
That was a bit of a mission @rawlingsj 👍

**Pull request merged**
