### PR TITLE
Added external versions support to packages

### PR DESCRIPTION
**Pull request by hekonsek**
Packages installation method now tries to read version from jenkins-x-version before falling back to "the latest from GitHub".

### CODE REVIEW

**Comment by jstrachan** [comment]
@hekonsek we will fix up CI failure error messages on PRs soon I hope btw!  But in the meantime I wonder if you could run `make fmt` and commit + push the code? Pipelines fail if the code isn't go formatted correctly

**Comment by jstrachan** [comment]
I wish we had a bot to do that automatically btw!

**Comment by hekonsek** [comment]
Sure, done. :)

**Comment by jstrachan** [comment]
@hekonsek sorry this is taking so long - any chance you can rebase & push please - we had a broken pipeline when you submitted the PR

**Comment by hekonsek** [comment]
@jstrachan  Rebase done. :)

**Pull request merged**
