### PR TITLE
fix: import GitLab repos with subgroups

### PR DESCRIPTION
**Pull request by Goodsmileduck**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description
allows import repos created inside subgroups in Gitlab
for example: https://gitlab.com/good-backend/subgroup/test-project

about subgroups: https://gitlab.com/help/user/group/subgroups/index

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by Goodsmileduck** [comment]
hmm, so how to see what is failing there?

**Comment by dwnusbaum** [comment]
@Goodsmileduck if you have a local cluster, you should be able to [run the tests yourself locally](https://jenkins-x.io/contribute/development/), not sure how to give you access to the demo UI here. The integration test failure was this:

```
    git_url_test.go:70: 
        	Error Trace:	git_url_test.go:70
        	Error:      	Not equal: 
        	            	expected: "foo"
        	            	actual  : "1"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-foo
        	            	+1
        	Test:       	TestParseGitURL
        	Messages:   	Name does not match for input https://bitbucketserver.com/projects/myproject/repos/foo/pull-requests/1
```

**Comment by Goodsmileduck** [comment]
got it @dwnusbaum . Thanks

**Comment by Goodsmileduck** [comment]
Guys can you tell me where tests fails?

**Comment by ccojocar** [comment]
There is a lint warning;
```
Code generation is out of date
pkg/gits/git_url.go
diff --git a/pkg/gits/git_url.go b/pkg/gits/git_url.go
index 0bfa278fa..9b6c912ff 100644
--- a/pkg/gits/git_url.go
+++ b/pkg/gits/git_url.go
@@ -3,8 +3,8 @@ package gits
 import (
        "fmt"
        "net/url"
-       "strings"
        "regexp"
+       "strings"

        "github.com/jenkins-x/jx/pkg/util"
 )
make: *** [verify-generation-complete] Error 1
Makefile.codegen:62: recipe for target 'verify-generation-complete' failed
FAILED make verify-generation-complete
RUN make generate-docs
Generating HTML docs for Kubernetes ClientsCode generation is out of date
pkg/gits/git_url.go
diff --git a/pkg/gits/git_url.go b/pkg/gits/git_url.go
index 0bfa278fa..9b6c912ff 100644
--- a/pkg/gits/git_url.go
+++ b/pkg/gits/git_url.go
@@ -3,8 +3,8 @@ package gits
 import (
        "fmt"
        "net/url"
-       "strings"
        "regexp"
+       "strings"

        "github.com/jenkins-x/jx/pkg/util"
 )
make: *** [verify-generation-complete] Error 1
Makefile.codegen:62: recipe for target 'verify-generation-complete' failed
FAILED make verify-generation-complete
RUN make generate-docs
Generating HTML docs for Kubernetes Clients
```

Please could you fix it? Thanks!

**Comment by ccojocar** [comment]
It seems that the BDD tests fail consistently with:

```
• Failure [1516.429 seconds]
create spring

/home/jenkins/go/jenkins-x/bdd-**/test/spring/**_create_spring.go:20
  Given valid parameters
  /home/jenkins/go/jenkins-x/bdd-**/test/spring/**_create_spring.go:34
    when running ** create spring
    /home/jenkins/go/jenkins-x/bdd-**/test/spring/**_create_spring.go:35
      creates a spring application and promotes it to staging
       [It]
      /home/jenkins/go/jenkins-x/bdd-**/test/spring/**_create_spring.go:36

      preview environment visible at a URL
      Unexpected error:
          <*errors.errorString | 0xc00054e1e0>: {
              s: "No Preview Application URL found",
          }
          No Preview Application URL found
      occurred

      /home/jenkins/go/jenkins-x/bdd-**/test/helpers/test.go:283
```

I think is not related to you change, but maybe please can you try to rebase the PR just in case?  Thanks!

**Comment by ccojocar** [comment]
@warrenbailey Please could you also fix the semantic PR? Your commits do not have a semantic PR prefix. Thanks!

**Comment by ccojocar** [comment]
@Goodsmileduck Any chance to get this fixed? Thanks!

**Comment by Goodsmileduck** [comment]
Hi, sorry was in a trip with very limited internet, will try to push changes today.

**Comment by Goodsmileduck** [comment]
@ccojocar hey, check it out now =)

**Comment by ccojocar** [comment]
@Goodsmileduck Thanks for fixing it!

**Pull request merged**
