### PR TITLE
[wip] fix(bdd): DO NOT MERGE Temp changes to ci for bdd testing

### PR DESCRIPTION
**Pull request by wbrefvem**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

### CODE REVIEW

**Comment by hferentschik** [comment]
@wbrefvem just wondering whether you still need this?

**Comment by wbrefvem** [comment]
@hferentschik At least until Cosmin's vault changes that fix our git auth issues, yes. I need to be able to validate my changes to the BDD tests. Although it occurs to me that the work @abayer has been doing may eliminate the need for this.

**Comment by hferentschik** [comment]
>  At least until Cosmin's vault changes that fix our git auth issues, yes. I need to be able to validate my changes to the BDD tests.

np

**Comment by ccojocar** [comment]
@wbrefvem Do you still need this PR? Can we close it? Thanks!

**Comment by hferentschik** [comment]
@wbrefvem closing this PR for now. If you still need it just create a new one or re-open.

**Pull request closed without merging**
