### PR TITLE
fix: remove usage of deprecated apiVersions

### LINKED ISSUE #7251: Remove deprecated K8s api versions
### Summary 
In some places in the code base, we use deprecated apis to query the kubernetes cluster for information about deployments. For example
```
d, err := client.ExtensionsV1beta1().Deployments(namespace).Get(name, options)
```
This would not work for kubernetes 1.16+. They should be changed. 
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
The newer apiVersions are available since Kubernetes 1.10, so this can be done safely.
Related to #6957

### PR DESCRIPTION
**Pull request by ankitm123**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description
In some places in the code base, we were querying the wrong apiVersions, this PR removes those.

#### Which issue this PR fixes

fixes #7251 

/assign @hferentschik

### CODE REVIEW

**Comment by ankitm123** [comment]
@hferentschik can you post the logs of the failed tests?

**Comment by hferentschik** [comment]
sure. here is the relevant part from the tekton context:

```
Showing logs for build [32m******************/bdd-spring-1590658996/master #1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-**-promote[0m
WARNING: prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/**/issues/2410
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Promoting app bdd-spring-1590658996 version 0.0.1 to namespace **-staging
Created Pull Request: https://github.com/******************/environment-pr-7252-8-tekton-gkebdd-staging/pull/1
Added label updatebot to Pull Request https://github.com/******************/environment-pr-7252-8-tekton-gkebdd-staging/pull/1
got git provider status pending from PR https://github.com/*************-test/environment-pr-7252-8-tekton-gkebdd-staging/pull/1
got git provider status pending from PR https://github.com/******************/environment-pr-7252-8-tekton-gkebdd-staging/pull/1
got git provider status pending from PR https://github.com/*************-test/environment-pr-7252-8-tekton-gkebdd-staging/pull/1
got git provider status pending from PR https://github.com/******************/environment-pr-7252-8-tekton-gkebdd-staging/pull/1
got git provider status pending from PR https://github.com/*************-test/environment-pr-7252-8-tekton-gkebdd-staging/pull/1
Pull Request https://github.com/******************/environment-pr-7252-8-tekton-gkebdd-staging/pull/1 is merged at sha 98acf2cfca1f6c2515b9e90002396f9afd2e128a
Pull Request merged but we are not waiting for the update pipeline to complete!
WARNING: Could not find the service URL in namespace **-staging for names bdd-spring-1590658996, **-bdd-spring-1590658996, **-staging-bdd-spring-1590658996
      [1mRUNNER:[0mExecution completed with exit code 0
[1mSTEP[0m: retrying ** get activities --filter *************-test/bdd-spring-1590658996/master with exponential backoff to ensure it completes
[1mSTEP[0m: calling ** get activities --filter ******************/bdd-spring-1590658996/master
      [1mRUNNER:[0mAbout to execute ** get activities --filter ******************/bdd-spring-1590658996/master in /tmp/bdd-277924745 with timeout 5m0s expecting exit code 0
      [1mRUNNER:[0mExecution completed with exit code 0
      [1mRUNNER:[0mAbout to execute ** get activities --filter ******************/bdd-spring-1590658996/master in /tmp/bdd-277924745 with timeout 5m0s expecting exit code 0
      [1mRUNNER:[0mExecution completed with exit code 0
[1mSTEP[0m: finding the activity for ******************/bdd-spring-1590658996/master #1 in map[******************/bdd-spring-1590658996/master #1:0xc000776060 ******************/bdd-spring-1590658996/master #2:0xc0007761e0]

[91m[1m• Failure [411.031 seconds][0m
create spring

[90m/tmp/jenkins-x/bdd-**/test/suite/spring/**_create_spring.go:20[0m
  Given valid parameters
  [90m/tmp/jenkins-x/bdd-**/test/suite/spring/**_create_spring.go:34[0m
    when running ** create spring
    [90m/tmp/jenkins-x/bdd-**/test/suite/spring/**_create_spring.go:35[0m
      [91m[1mcreates a spring application and promotes it to staging
       [It][0m
      [90m/tmp/jenkins-x/bdd-**/test/suite/spring/**_create_spring.go:36[0m

      [91mshould be one activity but found 2 having run ** get activities --filter *************-test/bdd-spring-1590658996/master --build 1; activities map[*************-test/bdd-spring-1590658996/master #1:0xc000776060 *************-test/bdd-spring-1590658996/master #2:0xc0007761e0]
      Expected
          <map[string]*parsers.Activity | len:2>: {
              "******************/bdd-spring-1590658996/master #1": {
                  JobName: "******************/bdd-spring-1590658996/master #1",
                  BuildNumber: 0,
                  StartedAgo: "6m11s",
                  Duration: "5m50s",
                  Status: "Succeeded Version: 0.0.1",
                  Stages: [
                      {
                          Name: "meta pipeline",
                          StartedAgo: "6m11s",
                          Duration: "1m20s",
                          Status: "Succeeded",
                          Steps: [
                              {
                                  Name: "Credential Initializer K5vvl",
                                  StartedAgo: "6m11s",
                                  Duration: "0s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Working Dir Initializer Wffvz",
                                  StartedAgo: "6m11s",
                                  Duration: "2s",
                                  Status: "Succeeded",
                              },
                              {Name: "Place Tools", StartedAgo: "6m9s", Duration: "1s", Status: "Succeeded"},
                              {
                                  Name: "Git Source Meta Jenkins X Bot Test Bdd Spr Qsx95 Qkhqk",
                                  StartedAgo: "6m8s",
                                  Duration: "8s",
                                  Status: "Succeeded https://github.com/******************/bdd-spring-1590658996.git",
                              },
                              {Name: "Git Merge", StartedAgo: "6m0s", Duration: "0s", Status: "Succeeded"},
                              {
                                  Name: "Merge Pull Refs",
                                  StartedAgo: "6m0s",
                                  Duration: "1s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Create Effective Pipeline",
                                  StartedAgo: "5m59s",
                                  Duration: "7s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Create Tekton Crds",
                                  StartedAgo: "5m52s",
                                  Duration: "1m1s",
                                  Status: "Succeeded",
                              },
                          ],
                      },
                      {
                          Name: "from build pack",
                          StartedAgo: "4m49s",
                          Duration: "4m28s",
                          Status: "Succeeded",
                          Steps: [
                              {
                                  Name: "Credential Initializer Jnk4j",
                                  StartedAgo: "4m49s",
                                  Duration: "0s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Working Dir Initializer Ftdxz",
                                  StartedAgo: "4m49s",
                                  Duration: "2s",
                                  Status: "Succeeded",
                              },
                              {Name: "Place Tools", StartedAgo: "4m47s", Duration: "1s", Status: "Succeeded"},
                              {
                                  Name: "Git Source Jenkins X Bot Test Bdd Spring 1 P7p9b Vhqqn",
                                  StartedAgo: "4m46s",
                                  Duration: "18s",
                                  Status: "Succeeded https://github.com/******************/bdd-spring-1590658996.git",
                              },
                              {Name: "Git Merge", StartedAgo: "4m28s", Duration: "1s", Status: "Succeeded"},
                              {
                                  Name: "Setup Jx Git Credentials",
                                  StartedAgo: "4m27s",
                                  Duration: "0s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Build Mvn Deploy",
                                  StartedAgo: "4m27s",
                                  Duration: "1m6s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Build Skaffold Version",
                                  StartedAgo: "3m21s",
                                  Duration: "1s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Build Container Build",
                                  StartedAgo: "3m20s",
                                  Duration: "26s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Build Post Build",
                                  StartedAgo: "2m54s",
                                  Duration: "0s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Promote Changelog",
                                  StartedAgo: "2m54s",
                                  Duration: "6s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Promote Helm Release",
                                  StartedAgo: "2m48s",
                                  Duration: "6s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Promote Jx Promote",
                                  StartedAgo: "2m42s",
                                  Duration: "2m21s",
                                  Status: "Succeeded",
                              },
                          ],
                      },
                      {
                          Name: "Promote: staging",
                          StartedAgo: "2m31s",
                          Duration: "2m10s",
                          Status: "Succeeded",
                          Steps: [
                              {
                                  Name: "PullRequest",
                                  StartedAgo: "2m31s",
                                  Duration: "2m8s",
                                  Status: "Succeeded  PullRequest: https://github.com/******************/environment-pr-7252-8-tekton-gkebdd-staging/pull/1 Merge SHA: 98acf2cfca1f6c2515b9e90002396f9afd2e128a",
                              },
                              {Name: "Update", StartedAgo: "23s", Duration: "2s", Status: "Succeeded"},
                          ],
                      },
                  ],
              },
              "*************-test/bdd-spring-1590658996/master #2": {
                  JobName: "******************/bdd-spring-1590658996/master #2",
                  BuildNumber: 0,
                  StartedAgo: "",
                  Duration: "4m51s",
                  Status: "Running Version: 0.0.2",
                  Stages: [
                      {
                          Name: "meta pipeline",
                          StartedAgo: "4m51s",
                          Duration: "1m0s",
                          Status: "Succeeded",
                          Steps: [
                              {
                                  Name: "Credential Initializer Xpxl5",
                                  StartedAgo: "4m51s",
                                  Duration: "0s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Working Dir Initializer V4lt5",
                                  StartedAgo: "4m51s",
                                  Duration: "1s",
                                  Status: "Succeeded",
                              },
                              {Name: "Place Tools", StartedAgo: "4m50s", Duration: "1s", Status: "Succeeded"},
                              {
                                  Name: "Git Source Meta Jenkins X Bot Test Bdd Spr Rjgbl K8v67",
                                  StartedAgo: "4m49s",
                                  Duration: "9s",
                                  Status: "Succeeded https://github.com/*************-test/bdd-spring-1590658996.git",
                              },
                              {Name: "Git Merge", StartedAgo: "4m40s", Duration: "1s", Status: "Succeeded"},
                              {
                                  Name: "Merge Pull Refs",
                                  StartedAgo: "4m39s",
                                  Duration: "1s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Create Effective Pipeline",
                                  StartedAgo: "4m38s",
                                  Duration: "8s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Create Tekton Crds",
                                  StartedAgo: "4m30s",
                                  Duration: "39s",
                                  Status: "Succeeded",
                              },
                          ],
                      },
                      {
                          Name: "from build pack",
                          StartedAgo: "",
                          Duration: "3m49s",
                          Status: "Running",
                          Steps: [
                              {
                                  Name: "Credential Initializer Gqnlt",
                                  StartedAgo: "3m49s",
                                  Duration: "0s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Working Dir Initializer R468l",
                                  StartedAgo: "3m49s",
                                  Duration: "1s",
                                  Status: "Succeeded",
                              },
                              {Name: "Place Tools", StartedAgo: "3m48s", Duration: "1s", Status: "Succeeded"},
                              {
                                  Name: "Git Source Jenkins X Bot Test Bdd Spring 1 Bk75d Zs5cc",
                                  StartedAgo: "3m47s",
                                  Duration: "17s",
                                  Status: "Succeeded https://github.com/******************/bdd-spring-1590658996.git",
                              },
                              {Name: "Git Merge", StartedAgo: "3m30s", Duration: "1s", Status: "Succeeded"},
                              {
                                  Name: "Setup Jx Git Credentials",
                                  StartedAgo: "3m29s",
                                  Duration: "1s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Build Mvn Deploy",
                                  StartedAgo: "3m28s",
                                  Duration: "42s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Build Skaffold Version",
                                  StartedAgo: "2m46s",
                                  Duration: "1s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Build Container Build",
                                  StartedAgo: "2m45s",
                                  Duration: "25s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Build Post Build",
                                  StartedAgo: "2m20s",
                                  Duration: "1s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Promote Changelog",
                                  StartedAgo: "2m19s",
                                  Duration: "5s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Promote Helm Release",
                                  StartedAgo: "2m14s",
                                  Duration: "6s",
                                  Status: "Succeeded",
                              },
                              {
                                  Name: "Promote Jx Promote",
                                  StartedAgo: "",
                                  Duration: "2m8s",
                                  Status: "Running",
                              },
                          ],
                      },
                      {
                          Name: "Promote: staging",
                          StartedAgo: "",
                          Duration: "1m56s",
                          Status: "Running",
                          Steps: [
                              {
                                  Name: "PullRequest",
                                  StartedAgo: "",
                                  Duration: "1m56s",
                                  Status: "Running  PullRequest: https://github.com/******************/environment-pr-7252-8-tekton-gkebdd-staging/pull/2",
                              },
                          ],
                      },
                  ],
              },
          }
      to have length 1[0m

      /tmp/jenkins-x/bdd-**/test/helpers/test.go:871
[90m------------------------------[0m


[91m[1mSummarizing 1 Failure:[0m

[91m[1m[Fail] [0m[90mcreate spring
 [0m[0mGiven valid parameters [0m[90mwhen running ** create spring [0m[91m[1m[It] creates a spring application and promotes it to staging
 [0m
[37m/tmp/jenkins-x/bdd-**/test/helpers/test.go:871[0m

[1m[91mRan 1 of 1 Specs in 411.342 seconds[0m
[1m[91mFAIL![0m -- [32m[1m0 Passed[0m | [91m[1m1 Failed[0m | [33m[1m0 Pending[0m | [36m[1m0 Skipped[0m
--- FAIL: TestSuite (411.34s)
FAIL
FAIL	github.com/jenkins-x/bdd-**/test/suite/spring	411.409s
FAIL
make: *** [test-create-spring] Error 1

Running kubectl get pods

NAME                                                                       READY   STATUS      RESTARTS   AGE
crier-6c4944b868-g8zhb                                                     1/1     Running     0          14m
deck-7f5c64b45d-sx78n                                                      1/1     Running     0          14m
deck-7f5c64b45d-x986c                                                      1/1     Running     0          14m
hook-647f968ffb-622cr                                                      1/1     Running     0          14m
hook-647f968ffb-bs9vc                                                      1/1     Running     0          14m
horologium-9fdcd6b57-sqwnt                                                 1/1     Running     0          14m
******************-bdd-spring-1-bk75d-2-from-build-pack-mvwrv-pod-1e07b9   1/10    Running     0          3m50s
******************-bdd-spring-1-p7p9b-1-from-build-pack-z28gz-pod-f834ef   0/10    Completed   0          4m50s
*************-test-environment-4s4**-1-from-build-pack-slvfv-pod-d67461    0/3     Completed   0          89s
******************-environment-8kktm-1-from-build-pack-dxnsj-pod-773ac1    0/4     Completed   0          8m26s
******************-environment-kv2z4-1-from-build-pack-gs4lp-pod-a3b709    0/3     Completed   0          2m3s
*************-test-environment-nw866-1-from-build-pack-2d9nq-pod-7fb8b2    0/4     Completed   0          8m48s
jenkins-x-chartmuseum-d87cbb789-fbxmd                                      1/1     Running     0          14m
jenkins-x-controllerbuild-66ff5c9767-7jlxj                                 1/1     Running     0          14m
jenkins-x-controllerrole-844bd89896-pgpcc                                  1/1     Running     0          14m
jenkins-x-heapster-6c8b894c48-vghp5                                        2/2     Running     0          12m
jenkins-x-nexus-b69b7745b-5tn8z                                            1/1     Running     0          14m
meta-******************-bdd-spr-qsx95-1-meta-pipeline-m8j4v-pod-fde01b     0/5     Completed   0          6m11s
meta-*************-test-bdd-spr-rjgbl-2-meta-pipeline-97bnr-pod-0fb9f1     0/5     Completed   0          4m52s
meta-******************-environ-2zmlg-1-meta-pipeline-vf5bd-pod-d5ab56     0/5     Completed   0          9m25s
meta-******************-environ-dcwbn-1-meta-pipeline-httqx-pod-b41921     0/5     Completed   0          115s
meta-*************-test-environ-j5xfs-1-meta-pipeline-9htfg-pod-f84055     0/5     Completed   0          9m17s
meta-******************-environ-srdhs-1-meta-pipeline-jzqwh-pod-ba8159     0/5     Completed   0          2m30s
pipeline-7dff794486-ml7lm                                                  1/1     Running     0          14m
pipelinerunner-6546498458-dbsnw                                            1/1     Running     0          14m
plank-7dd44fdb89-smlr6                                                     1/1     Running     0          14m
sinker-77866d679b-q5gjp                                                    1/1     Running     0          14m
tekton-pipelines-controller-88c7cd9d5-vzt77                                1/1     Running     0          14m
tekton-pipelines-webhook-7664dff68b-vwndv                                  1/1     Running     0          14m
tide-6bcf8f9f7f-n5mw7                                                      1/1     Running     0          14m

Running kubectl get env dev -oyaml

apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: "2020-05-28T09:34:11Z"
  generation: 6
  labels:
    env: dev
    team: **
  name: dev
  namespace: **
  resourceVersion: "2829"
  selfLink: /apis/jenkins.io/v1/namespaces/**/environments/dev
  uid: 6328f6ee-a0c6-11ea-8670-42010af000ad
spec:
  kind: Development
  label: Development
  namespace: **
  previewGitInfo:
    user: {}
  promotionStrategy: Never
  source: {}
  teamSettings:
    appsRepository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
    buildPackRef: master
    buildPackUrl: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git
    defaultScheduler:
      kind: ""
      name: ""
    dockerRegistryOrg: *************3
    envOrganisation: ******************
    gitServer: https://github.com
    helmTemplate: true
    importMode: YAML
    kubeProvider: gke
    pipelineUsername: ******************
    promotionEngine: Prow
    prowConfig: Legacy
    prowEngine: Tekton
    quickstartLocations:
    - excludes:
      - WIP-*
      gitKind: github
      gitUrl: https://github.com
      includes:
      - '*'
      owner: jenkins-x-quickstarts
    useGitOps: true
    versionStreamRef: master
    versionStreamUrl: https://github.com/jenkins-x/jenkins-x-versions.git
  webHookEngine: Prow
status: {}

Running ** status -b

Jenkins X checks passed for Cluster(gke_*************3_europe-west1-c_pr-7252-8-tekton-gkebdd): 3 nodes, memory 21% of 17331476Ki, cpu 66% of 5790m.

Running ** version -b

NAME               VERSION
**                 0.0.0-SNAPSHOT-PR-7252-8
jenkins x platform 2.0.2245
Kubernetes cluster v1.14.10-gke.36
kubectl            v1.13.2
helm client        2.12.2
git                2.21.1
Operating System   Unknown Linux distribution Linux version 4.14.138+ (chrome-bot@chromeos-ci-legacy-us-central1-b-x32-129-1lxw) (gcc version 4.9.x 20150123 (prerelease) (4.9.2_cos_gg_4.9.2-r200-ac6128e0a17a52f011797f33ac3e7d6273a9368d_4.9.2-r200)) #1 SMP Tue Sep 3 02:58:08 PDT 2019


verifying packages

WARNING: ** version 2.1.46 is available in the version stream. You are using 0.0.0-SNAPSHOT-PR-7252-8. We highly recommend you upgrade to it.
WARNING: To upgrade to this new version use: ** upgrade cli

Running ** get env -b

NAME       LABEL       KIND        PROMOTE NAMESPACE     ORDER CLUSTER SOURCE                                                                                   REF PR
dev        Development Development Never   **            0                                                                                                          
staging    Staging     Permanent   Auto    **-staging    100           https://github.com/******************/environment-pr-7252-8-tekton-gkebdd-staging.git        
production Production  Permanent   Manual  **-production 200           https://github.com/******************/environment-pr-7252-8-tekton-gkebdd-production.git     

Running ** get activities -b

STEP                                                                        STARTED AGO DURATION STATUS
******************/bdd-spring-1590658996/master #1                                6m16s    5m50s Succeeded Version: 0.0.1
  meta pipeline                                                                   6m16s    1m20s Succeeded 
    Credential Initializer K5vvl                                                  6m16s       0s Succeeded 
    Working Dir Initializer Wffvz                                                 6m16s       2s Succeeded 
    Place Tools                                                                   6m14s       1s Succeeded 
    Git Source Meta Jenkins X Bot Test Bdd Spr Qsx95 Qkhqk                        6m13s       8s Succeeded https://github.com/******************/bdd-spring-1590658996.git
    Git Merge                                                                      6m5s       0s Succeeded 
    Merge Pull Refs                                                                6m5s       1s Succeeded 
    Create Effective Pipeline                                                      6m4s       7s Succeeded 
    Create Tekton Crds                                                            5m57s     1m1s Succeeded 
  from build pack                                                                 4m54s    4m28s Succeeded 
    Credential Initializer Jnk4j                                                  4m54s       0s Succeeded 
    Working Dir Initializer Ftdxz                                                 4m54s       2s Succeeded 
    Place Tools                                                                   4m52s       1s Succeeded 
    Git Source Jenkins X Bot Test Bdd Spring 1 P7p9b Vhqqn                        4m51s      18s Succeeded https://github.com/******************/bdd-spring-1590658996.git
    Git Merge                                                                     4m33s       1s Succeeded 
    Setup Jx Git Credentials                                                      4m32s       0s Succeeded 
    Build Mvn Deploy                                                              4m32s     1m6s Succeeded 
    Build Skaffold Version                                                        3m26s       1s Succeeded 
    Build Container Build                                                         3m25s      26s Succeeded 
    Build Post Build                                                              2m59s       0s Succeeded 
    Promote Changelog                                                             2m59s       6s Succeeded 
    Promote Helm Release                                                          2m53s       6s Succeeded 
    Promote Jx Promote                                                            2m47s    2m21s Succeeded 
  Promote: staging                                                                2m36s    2m10s Succeeded 
    PullRequest                                                                   2m36s     2m8s Succeeded  PullRequest: https://github.com/******************/environment-pr-7252-8-tekton-gkebdd-staging/pull/1 Merge SHA: 98acf2cfca1f6c2515b9e90002396f9afd2e128a
    Update                                                                          28s       2s Succeeded 
******************/bdd-spring-1590658996/master #2                                4m56s          Running Version: 0.0.2
  meta pipeline                                                                   4m56s     1m0s Succeeded 
    Credential Initializer Xpxl5                                                  4m56s       0s Succeeded 
    Working Dir Initializer V4lt5                                                 4m56s       1s Succeeded 
    Place Tools                                                                   4m55s       1s Succeeded 
    Git Source Meta Jenkins X Bot Test Bdd Spr Rjgbl K8v67                        4m54s       9s Succeeded https://github.com/******************/bdd-spring-1590658996.git
    Git Merge                                                                     4m45s       1s Succeeded 
    Merge Pull Refs                                                               4m44s       1s Succeeded 
    Create Effective Pipeline                                                     4m43s       8s Succeeded 
    Create Tekton Crds                                                            4m35s      39s Succeeded 
  from build pack                                                                 3m54s          Running 
    Credential Initializer Gqnlt                                                  3m54s       0s Succeeded 
    Working Dir Initializer R468l                                                 3m54s       1s Succeeded 
    Place Tools                                                                   3m53s       1s Succeeded 
    Git Source Jenkins X Bot Test Bdd Spring 1 Bk75d Zs5cc                        3m52s      17s Succeeded https://github.com/******************/bdd-spring-1590658996.git
    Git Merge                                                                     3m35s       1s Succeeded 
    Setup Jx Git Credentials                                                      3m34s       1s Succeeded 
    Build Mvn Deploy                                                              3m33s      42s Succeeded 
    Build Skaffold Version                                                        2m51s       1s Succeeded 
    Build Container Build                                                         2m50s      25s Succeeded 
    Build Post Build                                                              2m25s       1s Succeeded 
    Promote Changelog                                                             2m24s       5s Succeeded 
    Promote Helm Release                                                          2m19s       6s Succeeded 
    Promote Jx Promote                                                            2m13s          Running 
  Promote: staging                                                                 2m1s          Running 
    PullRequest                                                                    2m1s          Running  PullRequest: https://github.com/******************/environment-pr-7252-8-tekton-gkebdd-staging/pull/2
******************/environment-pr-7252-8-tekton-gkebdd-production/master #1       9m20s    2m35s Succeeded 
  meta pipeline                                                                   9m20s      48s Succeeded 
    Credential Initializer Kg8sf                                                  9m20s       0s Succeeded 
    Working Dir Initializer Vrwm8                                                 9m20s       3s Succeeded 
    Place Tools                                                                   9m17s       1s Succeeded 
    Git Source Meta Jenkins X Bot Test Environ J5xfs Xg9jb                        9m16s      25s Succeeded https://github.com/******************/environment-pr-7252-8-tekton-gkebdd-production.git
    Git Merge                                                                     8m51s       1s Succeeded 
    Merge Pull Refs                                                               8m50s       0s Succeeded 
    Create Effective Pipeline                                                     8m50s      10s Succeeded 
    Create Tekton Crds                                                            8m40s       8s Succeeded 
  from build pack                                                                 8m26s    1m41s Succeeded 
    Credential Initializer C8vjs                                                  8m26s       0s Succeeded 
    Working Dir Initializer Nznw2                                                 8m26s       1s Succeeded 
    Place Tools                                                                   8m25s       1s Succeeded 
    Git Source Jenkins X Bot Test Environment 8kktm 886qq                         8m24s      10s Succeeded https://github.com/*************-test/environment-pr-7252-8-tekton-gkebdd-production.git
    Git Merge                                                                     8m14s       0s Succeeded 
    Setup Jx Git Credentials                                                      8m14s       1s Succeeded 
    Build Helm Apply                                                              8m13s    1m28s Succeeded 
******************/environment-pr-7252-8-tekton-gkebdd-staging/master #1          9m28s    2m41s Succeeded 
  meta pipeline                                                                   9m28s      34s Succeeded 
    Credential Initializer Mbjfn                                                  9m28s       0s Succeeded 
    Working Dir Initializer Dcpnj                                                 9m28s       2s Succeeded 
    Place Tools                                                                   9m26s       2s Succeeded 
    Git Source Meta Jenkins X Bot Test Environ 2zmlg Wf9p2                        9m24s       7s Succeeded https://github.com/******************/environment-pr-7252-8-tekton-gkebdd-staging.git
    Git Merge                                                                     9m17s       1s Succeeded 
    Merge Pull Refs                                                               9m16s       0s Succeeded 
    Create Effective Pipeline                                                     9m16s      14s Succeeded 
    Create Tekton Crds                                                             9m2s       8s Succeeded 
  from build pack                                                                 8m50s     2m3s Succeeded 
    Credential Initializer Qwwft                                                  8m50s       0s Succeeded 
    Working Dir Initializer 8jvw7                                                 8m50s       1s Succeeded 
    Place Tools                                                                   8m49s       2s Succeeded 
    Git Source Jenkins X Bot Test Environment Nw866 Zhzcs                         8m47s      31s Succeeded https://github.com/*************-test/environment-pr-7252-8-tekton-gkebdd-staging.git
    Git Merge                                                                     8m16s       1s Succeeded 
    Setup Jx Git Credentials                                                      8m15s       1s Succeeded 
    Build Helm Apply                                                              8m14s    1m27s Succeeded 
*************-test/environment-pr-7252-8-tekton-gkebdd-staging/PR-1 #1            2m34s    1m26s Succeeded 
  meta pipeline                                                                   2m34s      25s Succeeded 
    Credential Initializer Zmb7n                                                  2m34s       0s Succeeded 
    Working Dir Initializer 6zsrm                                                 2m34s       1s Succeeded 
    Place Tools                                                                   2m33s       1s Succeeded 
    Git Source Meta Jenkins X Bot Test Environ Srdhs 8q6lm                        2m32s       6s Succeeded https://github.com/*************-test/environment-pr-7252-8-tekton-gkebdd-staging.git
    Git Merge                                                                     2m26s       3s Succeeded 
    Merge Pull Refs                                                               2m23s       2s Succeeded 
    Create Effective Pipeline                                                     2m21s       9s Succeeded 
    Create Tekton Crds                                                            2m12s       3s Succeeded 
  from build pack                                                                  2m7s      59s Succeeded 
    Credential Initializer 8pp5n                                                   2m7s       0s Succeeded 
    Working Dir Initializer Bsnzf                                                  2m7s       1s Succeeded 
    Place Tools                                                                    2m6s       1s Succeeded 
    Git Source Jenkins X Bot Test Environment Kv2z4 82pcn                          2m5s       5s Succeeded https://github.com/******************/environment-pr-7252-8-tekton-gkebdd-staging.git
    Git Merge                                                                      2m0s       2s Succeeded 
    Build Helm Build                                                              1m58s      50s Succeeded 
*************-test/environment-pr-7252-8-tekton-gkebdd-staging/PR-2 #1            1m59s    1m22s Succeeded 
  meta pipeline                                                                   1m59s      24s Succeeded 
    Credential Initializer W6fvf                                                  1m59s       0s Succeeded 
    Working Dir Initializer Qm6vg                                                 1m59s       1s Succeeded 
    Place Tools                                                                   1m58s       1s Succeeded 
    Git Source Meta Jenkins X Bot Test Environ Dcwbn D29p4                        1m57s       5s Succeeded https://github.com/******************/environment-pr-7252-8-tekton-gkebdd-staging.git
    Git Merge                                                                     1m52s       3s Succeeded 
    Merge Pull Refs                                                               1m49s       1s Succeeded 
    Create Effective Pipeline                                                     1m48s       9s Succeeded 
    Create Tekton Crds                                                            1m39s       4s Succeeded 
  from build pack                                                                 1m34s      57s Succeeded 
    Credential Initializer 9ksdf                                                  1m34s       0s Succeeded 
    Working Dir Initializer Zbpw6                                                 1m34s       1s Succeeded 
    Place Tools                                                                   1m33s       1s Succeeded 
    Git Source Jenkins X Bot Test Environment 4s4** Rq99r                         1m32s       7s Succeeded https://github.com/******************/environment-pr-7252-8-tekton-gkebdd-staging.git
    Git Merge                                                                     1m25s       2s Succeeded 
    Build Helm Build                                                              1m23s      46s Succeeded 

Running ** get application -b

APPLICATION

Running ** get preview -b

PULL REQUEST NAMESPACE APPLICATION

Running ** open

NAME                  URL
deck                  http://deck.**.146.148.30.118.nip.io
hook                  http://hook.**.146.148.30.118.nip.io
jenkins-x-chartmuseum http://chartmuseum.**.146.148.30.118.nip.io
nexus                 http://nexus.**.146.148.30.118.nip.io
tide                  http://tide.**.146.148.30.118.nip.io
WARNING: Failed to perform tests on cluster pr-7252-8-tekton-gkebdd: failed to run 'make test-upgrade-ingress test-create-spring test-import-golang-http-from-jenkins-x-yml test-app-lifecycle' command in directory '/tmp/jenkins-x/bdd-**', output: ''
error: failed to run 'make test-upgrade-ingress test-create-spring test-import-golang-http-from-jenkins-x-yml test-app-lifecycle' command in directory '/tmp/jenkins-x/bdd-**', output: ''
[31m
Pipeline failed on stage 'e2e-tests' : container 'step-tekton-e2e-tests'. The execution of the pipeline has stopped.[0m
```

not really sure what's going on tbh.

**Comment by hferentschik** [comment]
@abayer usually has a better hand with making sense of these types of errors. I am a bit at loss atm.

**Comment by abayer** [comment]
That smells transient. I bet it works on rerun.

**Pull request merged**
