### PR TITLE
fix: add InstallOnly to InstallChartOptions and add checks before fetchChat

### PR DESCRIPTION
**Pull request by nodece**
Signed-off-by: Zixuan Liu <nodeces@gmail.com>

issues: #7475

### CODE REVIEW

**Comment by ankitm123** [comment]
@nodece create an issue and link this PR to it. Probably a better idea to put more context in the issue than PR description.

**Comment by nodece** [comment]
I created issues: #7475

**Comment by jstrachan** [comment]
@nodece here's the unit test failure; am not 100% sure why your changes break things though. Does `make test` work locally for you?

``` 
ok  	github.com/jenkins-x/**/v2/pkg/cmd/step/git/credentials	0.090s
ok  	github.com/jenkins-x/**/v2/pkg/cmd/step/helm	8.643s
?   	github.com/jenkins-x/**/v2/pkg/cmd/step/post	[no test files]
?   	github.com/jenkins-x/**/v2/pkg/cmd/step/pr	[no test files]
ok  	github.com/jenkins-x/**/v2/pkg/cmd/step/report	0.105s
?   	github.com/jenkins-x/**/v2/pkg/cmd/step/restore	[no test files]
ok  	github.com/jenkins-x/**/v2/pkg/cmd/step/scheduler	1.236s
--- FAIL: TestCreateCanonicalPipeline (0.02s)
    --- FAIL: TestCreateCanonicalPipeline/js_build_pack_with_yaml (0.02s)
        step_syntax_effective_test.go:960: Generated canonical pipeline does not match expected:
              &config.ProjectConfig{
              	... // 7 identical fields
              	BuildPackGitURL:  "",
              	BuildPackGitURef: "",
              	PipelineConfig: &jenkinsfile.PipelineConfig{
              		... // 2 identical fields
              		Env:         []v1.EnvVar{{Name: "DOCKER_REGISTRY", Value: "gcr.io"}},
              		Environment: "",
              		Pipelines: jenkinsfile.Pipelines{
              			PullRequest: &jenkinsfile.PipelineLifecycles{
              				... // 4 identical fields
              				PostBuild: nil,
              				Promote:   nil,
              				Pipeline: &syntax.ParsedPipeline{
              					Agent:   nil,
              					Env:     []v1.EnvVar{{Name: "DOCKER_REGISTRY", Value: "gcr.io"}},
              					Options: &syntax.RootOptions{ContainerOptions: &v1.Container{Env: []v1.EnvVar{{Name: "DOCKER_CONFIG", Value: "/home/jenkins/.docker/"}, {Name: "DOCKER_REGISTRY", Value: "gcr.io"}, {Name: "GIT_AUTHOR_EMAIL", Value: "jenkins-x@googlegroups.com"}, {Name: "GIT_AUTHOR_NAME", Value: "*************"}, {Name: "GIT_COMMITTER_EMAIL", Value: "jenkins-x@googlegroups.com"}, {Name: "GIT_COMMITTER_NAME", Value: "*************"}, {Name: "JENKINS_URL", Value: "http://jenkins:8080"}, {Name: "TILLER_NAMESPACE", Value: "kube-system"}, {Name: "XDG_CONFIG_HOME", Value: "/home/jenkins"}}, Resources: v1.ResourceRequirements{...}, VolumeMounts: []v1.VolumeMount{{Name: "workspace-volume", MountPath: "/home/jenkins"}, {Name: "docker-daemon", MountPath: "/var/run/docker.sock"}, {Name: "volume-0", MountPath: "/home/jenkins/.docker"}}, SecurityContext: &v1.SecurityContext{Privileged: &true}}, Volumes: []*v1.Volume{&{Name: "workspace-volume", VolumeSource: v1.VolumeSource{EmptyDir: &v1.EmptyDirVolumeSource{}}}, &{Name: "docker-daemon", VolumeSource: v1.VolumeSource{HostPath: &v1.HostPathVolumeSource{Path: "/var/run/docker.sock"}}}, &{Name: "volume-0", VolumeSource: v1.VolumeSource{Secret: &v1.SecretVolumeSource{SecretName: "jenkins-docker-cfg"}}}}},
              					Stages: []syntax.Stage{
              						{
              							... // 2 identical fields
              							Env:     nil,
              							Options: nil,
              							Steps: []syntax.Step{
              								{Name: "build-npm-install", Command: "npm install", Dir: "/workspace/source", Image: "nodejs"},
              								{Name: "build-step3", Command: "CI=true DISPLAY=:99 npm test", Dir: "/workspace/source", Image: "nodejs"},
              								{
              									Name:    "build-container-build",
              									Command: "/kaniko/executor",
              									Arguments: []string{
              										... // 2 identical elements
              										"--context=/workspace/source",
              										"--dockerfile=/workspace/source/Dockerfile",
              										strings.Join({
              											"--destination=gcr.io/",
            - 											"abayer",
            + 											"jenkins-x-infra",
              											"/js-test-repo:${inputs.params.version}",
              										}, ""),
              										"--cache-repo=gcr.io//cache",
              									},
              									Dir:  "/workspace/source",
              									Step: "",
              									... // 11 identical fields
              								},
              								{Name: "postbuild-post-build", Command: "** step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION", Dir: "/workspace/source", Image: "nodejs"},
              								{Name: "promote-make-preview", Command: "make preview", Dir: "/workspace/source/charts/preview", Image: "nodejs"},
              								{Name: "promote-**-preview", Command: "** preview --app $APP_NAME --dir ../..", Dir: "/workspace/source/charts/preview", Image: "nodejs"},
              							},
              							Stages:   nil,
              							Parallel: nil,
              							... // 3 identical fields
              						},
              					},
              					Post:        nil,
              					WorkingDir:  nil,
              					Environment: nil,
              				},
              			},
              			Release: &jenkinsfile.PipelineLifecycles{
              				... // 4 identical fields
              				PostBuild: nil,
              				Promote:   nil,
              				Pipeline: &syntax.ParsedPipeline{
              					Agent:   nil,
              					Env:     []v1.EnvVar{{Name: "DOCKER_REGISTRY", Value: "gcr.io"}},
              					Options: &syntax.RootOptions{ContainerOptions: &v1.Container{Env: []v1.EnvVar{{Name: "DOCKER_CONFIG", Value: "/home/jenkins/.docker/"}, {Name: "DOCKER_REGISTRY", Value: "gcr.io"}, {Name: "GIT_AUTHOR_EMAIL", Value: "jenkins-x@googlegroups.com"}, {Name: "GIT_AUTHOR_NAME", Value: "*************"}, {Name: "GIT_COMMITTER_EMAIL", Value: "jenkins-x@googlegroups.com"}, {Name: "GIT_COMMITTER_NAME", Value: "*************"}, {Name: "JENKINS_URL", Value: "http://jenkins:8080"}, {Name: "TILLER_NAMESPACE", Value: "kube-system"}, {Name: "XDG_CONFIG_HOME", Value: "/home/jenkins"}}, Resources: v1.ResourceRequirements{...}, VolumeMounts: []v1.VolumeMount{{Name: "workspace-volume", MountPath: "/home/jenkins"}, {Name: "docker-daemon", MountPath: "/var/run/docker.sock"}, {Name: "volume-0", MountPath: "/home/jenkins/.docker"}}, SecurityContext: &v1.SecurityContext{Privileged: &true}}, Volumes: []*v1.Volume{&{Name: "workspace-volume", VolumeSource: v1.VolumeSource{EmptyDir: &v1.EmptyDirVolumeSource{}}}, &{Name: "docker-daemon", VolumeSource: v1.VolumeSource{HostPath: &v1.HostPathVolumeSource{Path: "/var/run/docker.sock"}}}, &{Name: "volume-0", VolumeSource: v1.VolumeSource{Secret: &v1.SecretVolumeSource{SecretName: "jenkins-docker-cfg"}}}}},
              					Stages: []syntax.Stage{
              						{
              							... // 2 identical fields
              							Env:     nil,
              							Options: nil,
              							Steps: []syntax.Step{
              								{Name: "setup-**-git-credentials", Command: "** step git credentials", Dir: "/workspace/source", Image: "nodejs"},
              								{Name: "build-npm-install", Command: "npm install", Dir: "/workspace/source", Image: "nodejs"},
              								{Name: "build-npm-test", Command: "CI=true DISPLAY=:99 npm test", Dir: "/workspace/source", Image: "nodejs"},
              								{
              									Name:    "build-container-build",
              									Command: "/kaniko/executor",
              									Arguments: []string{
              										... // 2 identical elements
              										"--context=/workspace/source",
              										"--dockerfile=/workspace/source/Dockerfile",
              										strings.Join({
              											"--destination=gcr.io/",
            - 											"abayer",
            + 											"jenkins-x-infra",
              											"/js-test-repo:${inputs.params.version}",
              										}, ""),
              										"--cache-repo=gcr.io//cache",
              									},
              									Dir:  "/workspace/source",
              									Step: "",
              									... // 11 identical fields
              								},
              								{Name: "build-post-build", Command: "** step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:${VERSION}", Dir: "/workspace/source", Image: "nodejs"},
              								{Name: "promote-changelog", Command: "** step changelog --batch-mode --version v${VERSION}", Dir: "/workspace/source/charts/js-test-repo", Image: "nodejs"},
              								... // 2 identical elements
              							},
              							Stages:   nil,
              							Parallel: nil,
              							... // 3 identical fields
              						},
              					},
              					Post:        nil,
              					WorkingDir:  nil,
              					Environment: nil,
              				},
              			},
              			Feature: nil,
              			Post:    &jenkinsfile.PipelineLifecycle{Steps: []*syntax.Step{}, PreSteps: []*syntax.Step{}},
              			... // 2 identical fields
              		},
              		ContainerOptions: nil,
              	},
              	NoReleasePrepare:    false,
              	DockerRegistryHost:  "",
              	DockerRegistryOwner: "",
              }
FAIL
```

**Comment by nodece** [comment]
@jstrachan `TestCreateCanonicalPipeline` is work on my locally.

**Comment by nodece** [comment]
Who can provide the test log?

**Pull request merged**
