### PR TITLE
fix: make helm templates skip applying an empty chart

### PR DESCRIPTION
**Pull request by ccojocar**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by pmuir** [comment]
Yep, that broke something!

**Comment by ccojocar** [comment]
I am looking into them to check if they can be fixed.

**Comment by ccojocar** [comment]
@pmuir @jstrachan I think this solution to skip the empty charts installation does not quite work to solve the issue in boot. There are some empty charts such as https://github.com/jenkins-x/jenkins-x-boot-config/tree/master/systems/jxing which needs to be installed. They just reference other charts.

**Pull request merged**
