### PR TITLE
Add support for cluster-issuer when exposing services

### PR DESCRIPTION
**Pull request by heroic**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

### CODE REVIEW

**Comment by jstrachan** [comment]
looks like a build error 
```
pkg/kube/ingress.go:82:89: undefined: tls
```

**Comment by jstrachan** [comment]
@heroic looks like you need to run `make fmt` and the push again please

**Comment by wenzlaff** [comment]
Are there any docs on how to use this new feature? I created a ClusterIssuer with the name letsencrypt-prod in namespace cert-manager but jx is still creating Issuers during "jx upgrade ingress".

`Certificate issuer letsencrypt-prod does not exist. Creating...`

**Comment by heroic** [comment]
@wenzlaff you need to add "clusterissuer" to your ingress-config configmap,
and set it to true.

**Comment by wenzlaff** [comment]
@heroic Thanks for your hint, but even after setting the clusterissuer=true, the same happens:

`? Using config values {me@example.com k8s.example.com letsencrypt-prod true Ingress  true}, ok? Yes

Looking for "cert-manager" deployment in namespace "cert-manager"...
Deleting ingress jx/chartmuseum
Deleting ingress jx/docker-registry
Deleting ingress jx/jenkins
Deleting ingress jx/monocular
Deleting ingress jx/nexus
Expecting certificates: [jx/tls-jenkins jx/tls-monocular jx/tls-chartmuseum jx/tls-docker-registry jx/tls-nexus]
Ready Cert: cert-manager/cert-manager-webhook-ca
Ready Cert: cert-manager/cert-manager-webhook-webhook-tls
Certificate issuer letsencrypt-prod does not exist. Creating...`

**Comment by wenzlaff** [comment]
Just wanted to let you know that the ClusterIssuer works fine but additionally the Issuers in the namespaces are created as well.

**Pull request merged**
