### PR TITLE
`jx promote` coverage increase

### PR DESCRIPTION
**Pull request by amuniz**
Increasing test coverage for `jx promote`.

### CODE REVIEW

**Comment by jstrachan** [comment]
@amuniz looks like the unit tests fail. You should be able to reproduce this locally via:
```
make test-slow-integration
```
e.g.
```
--- FAIL: TestPromoteToProductionRun (6.23s)
    test_helpers.go:221:
        	Error Trace:	test_helpers.go:221
        	            				promote_test.go:64
        	Error:      	Missing Promote
        	Test:       	TestPromoteToProductionRun
        	Messages:   	No Promote found on PipelineActivity myorg-my-app-master-1 for Environment production
    test_helpers.go:363:
        	Error Trace:	test_helpers.go:363
        	            				promote_test.go:65
        	Error:      	Not equal:
        	            	expected: "Running"
        	            	actual  : "Succeeded"

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-Running
        	            	+Succeeded
        	Test:       	TestPromoteToProductionRun
        	Messages:   	activity status for PipelineActivity myorg-my-app-master-1
    test_helpers.go:353:
        	Error Trace:	test_helpers.go:353
        	            				promote_test.go:72
        	Error:      	Missing Promote
        	Test:       	TestPromoteToProductionRun
        	Messages:   	No Promote found on PipelineActivity myorg-my-app-master-1 for Environment production
```

**Comment by amuniz** [comment]
Yeah, I was finally able to access the logs and saw that. My last commit should fix the tests. Waiting now for a new build to finish.

Thanks!

**Comment by amuniz** [comment]
Hmm, still failing... having a look.

**Comment by amuniz** [comment]
Failures coming from master are of the form:

```
--- FAIL: TestImportProjects (2.92s)
    import_integration_test.go:84: 
        	Error Trace:	import_integration_test.go:84
        	            				import_integration_test.go:59
        	            				import_integration_test.go:46
        	Error:      	Received unexpected error:
        	            	Running in batch mode and no default Git username found
        	Test:       	TestImportProjects
        	Messages:   	Failed with Running in batch mode and no default Git username found
```

**Comment by jstrachan** [comment]
@amuniz it seems most PRs that are rebased are working again now - dunno if that helps or not ;) Lets see if this retest works...

**Comment by jstrachan** [comment]
FWIW pipelines were failing as our nexus used for the BDD tests on each PR was out of disk

**Comment by amuniz** [comment]
Thanks @jstrachan 

These are real test failures, however I'm unable to reproduce them locally. Trying to figure out what could be the cause.

**Comment by amuniz** [comment]
Noting it here in case others face the same issue than me: **default parameter values read from the environment can potentially affect tests when building JX by JX** (which is the case for PR in this project).

In my case the activity key was being [read from the default values on env](https://github.com/jenkins-x/jx/blob/6817508c49bdaca79651b7231beba70a69b49bf7/pkg/jx/cmd/common.go#L853-L855), which was good in my local test run but not in CI, where the real PR build values are taken (something like `jenkins-x-jx-pr-2126-15` instead of the expected test value `myorg-myapp-master-1`). So my test activity step was being registered to the wrong activity thus my test failed.

**Comment by amuniz** [comment]
Last failure seems unrelated to the content of this PR. Retriggering.

**Comment by amuniz** [comment]
I believe this is ready to merge. Can someone review/approve please?

**Pull request merged**
