### PR TITLE
fix: use namespace from jx-requirements

### PR DESCRIPTION
**Pull request by pmuir**
#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

Part of #5034

### CODE REVIEW

**Comment by macox** [comment]
@pmuir Should we verify the namespace in the verifyRequirements function?

**Comment by pmuir** [comment]
@macox done

**Comment by abayer** [comment]
Looks like the flaky `FAIL: pkg/cmd/step/scheduler TestStepSchedulerConfigMigrateNonGitopsAdvanced` test. Rerunning.

**Pull request merged**
