### PR TITLE
[wip] test: Experimenting with boot-vault using k8s 1.16

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

Just trying this out. Looks like the terraform script will always use the default k8s version, so I didn't bother changing anything there.

#### Which issue this PR fixes

relates to #6957

### CODE REVIEW

**Comment by abayer** [comment]
Took a couple tries to get the flag right, but https://dashboard-jx.jenkins-x.live/teams/jx/projects/jenkins-x/jx/PR-7272/19 booted properly on 1.16. Everything seems to be running properly, so let's see how the actual tests go...

**Comment by abayer** [comment]
`boot-vault` works (mostly) against the UI after I updated it to use `apps/v1` for its deployments, but the UI now requires basic authentication, and our tests fail on that.

**Comment by hferentschik** [comment]
Is this pull request obsolete in the light if #7313

**Comment by abayer** [comment]
@hferentschik This was just a way to verify all our charts worked anyway, so yeah, closing.

**Pull request closed without merging**
