### PR TITLE
WIP switch to go modules (tests pass)

### PR DESCRIPTION
**Pull request by i0n**

### CODE REVIEW

**Comment by rawlingsj** [comment]
I've not got the logs sorted yet so manually copy / pasting here...
<details><summary>LOGS</summary>
<p>


```python
go: finding github.com/xanzy/ssh-agent v0.2.0
go: finding github.com/Azure/draft v0.15.0
go: finding github.com/golang/protobuf v1.1.0
go: finding github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
go: finding github.com/prometheus/client_golang v0.8.0
go: finding github.com/gregjones/httpcache v0.0.0-20180305231024-9cad4c3443a7
go: finding github.com/google/go-github v0.0.0-20180723152927-e1be32f26e66
go: finding github.com/fatih/color v1.7.0
go: finding github.com/rifflock/lfshook v0.0.0-20180227222202-bf539943797a
go: finding gopkg.in/AlecAivazis/survey.v1 v1.6.1
go: finding github.com/gophercloud/gophercloud v0.0.0-20180721014243-9bb899a7c1d9
go: finding github.com/spf13/cast v1.2.0
go: finding github.com/fsnotify/fsnotify v1.4.7
go: finding github.com/golang/groupcache v0.0.0-20180513044358-24b0969c4cb7
go: finding github.com/src-d/gcfg v1.3.0
go: finding github.com/viniciuschiele/tarx v0.0.0-20151205142357-6e3da540444d
go: finding github.com/Masterminds/semver v1.4.2
go: finding k8s.io/helm v2.7.2+incompatible
go: finding k8s.io/metrics v0.0.0-20180620010437-b11cf31b380b
go: finding gopkg.in/src-d/go-git-fixtures.v3 v3.1.0
go: finding github.com/inconshreveable/mousetrap v1.0.0
go: finding golang.org/x/image v0.0.0-20180708004352-c73c2afc3b81
go: finding github.com/mitchellh/mapstructure v0.0.0-20180715050151-f15292f7a699
go: finding github.com/chromedp/chromedp v0.1.1
go: finding github.com/prometheus/procfs v0.0.0-20180705121852-ae68e2d4c00f
go: finding github.com/BurntSushi/toml v0.3.0
go: finding github.com/magiconair/properties v1.8.0
go: finding github.com/json-iterator/go v0.0.0-20180701071628-ab8a2e0c74be
go: finding gopkg.in/inf.v0 v0.9.1
go: finding github.com/cenkalti/backoff v2.0.0+incompatible
go: finding github.com/stretchr/testify v1.2.2
go: finding github.com/modern-go/reflect2 v0.0.0-20180701023420-4b7aa43c6742
go: finding github.com/smartystreets/goconvey v0.0.0-20180222194500-ef6db91d284a
go: finding github.com/wbrefvem/go-bitbucket v0.0.0-20180519060909-27c6c0db883c
go: finding github.com/codeship/codeship-go v0.0.0-20180717142545-7793ca823354
go: finding github.com/hashicorp/hcl v0.0.0-20180404174102-ef8a98b0bbce
go: finding github.com/google/go-querystring v0.0.0-20170111101155-53e6ce116135
go: finding github.com/c2h5oh/datasize v0.0.0-20171227191756-4eba002a5eae
go: finding github.com/gorilla/sessions v1.1.1
go: finding golang.org/x/oauth2 v0.0.0-20180620175406-ef147856a6dd
go: finding golang.org/x/text v0.3.0
go: finding google.golang.org/appengine v1.1.0
go: finding github.com/davecgh/go-spew v1.1.0
go: finding github.com/jenkins-x/golang-jenkins v0.0.0-20180712110428-b5ec7e72291c
go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
go: finding github.com/go-yaml/yaml v2.1.0+incompatible
go: finding google.golang.org/genproto v0.0.0-20180722052100-02b4e9547331
go: finding github.com/docker/spdystream v0.0.0-20170912183627-bc6354cbbc29
go: finding github.com/hpcloud/tail v1.0.0
go: finding golang.org/x/image v0.0.0-20180628062038-cc896f830ced
go: finding github.com/mattn/go-colorable v0.0.9
go: finding google.golang.org/grpc v1.13.0
go: finding k8s.io/apimachinery v0.0.0-20180621070125-103fd098999d
go: finding gopkg.in/fsnotify.v1 v1.4.7
go: finding github.com/gogo/protobuf v1.1.1
go: finding gopkg.in/src-d/go-git.v4 v4.5.0
go: finding github.com/shurcooL/graphql v0.0.0-20180514000029-62c9ce094e75
go: finding github.com/mailru/easyjson v0.0.0-20180606163543-3fdea8d05856
go: finding github.com/shurcooL/go v0.0.0-20180423040247-9e1955d9fb6e
go: finding gopkg.in/warnings.v0 v0.1.2
go: finding github.com/aws/aws-sdk-go v1.14.31
go: finding github.com/onsi/ginkgo v1.6.0
go: finding github.com/kr/pty v1.1.2
go: finding github.com/google/martian v2.0.0-beta.2+incompatible
go: finding github.com/ghodss/yaml v1.0.0
go: finding github.com/mailru/easyjson v0.0.0-20180723221831-d5012789d665
go: finding github.com/wbrefvem/go-gitlab v0.0.0-20180628044536-ecc4c5b8455a
go: finding github.com/hashicorp/go-version v0.0.0-20180716215031-270f2f71b1ee
go: finding github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
go: finding github.com/Azure/go-autorest v10.14.0+incompatible
go: finding gopkg.in/robfig/cron.v2 v2.0.0-20150107220207-be2e0b0deed5
go: finding github.com/hashicorp/golang-lru v0.0.0-20180201235237-0fb14efe8c47
go: finding golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
go: finding github.com/spf13/afero v1.1.1
go: github.com/wbrefvem/go-gitlab@v0.0.0-20180628044536-ecc4c5b8455a: unknown revision ecc4c5b8455a
go: finding github.com/Netflix/go-expect v0.0.0-20180810002857-85261cf71f0b
go: finding github.com/imdario/mergo v0.3.5
go: finding code.gitea.io/sdk v0.0.0-20180702024448-79a281c4e34a
go: finding cloud.google.com/go v0.25.0
go: finding github.com/gliderlabs/ssh v0.1.1
go: finding github.com/gopherjs/gopherjs v0.0.0-20180628210949-0892b62f0d9f
go: finding github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: finding github.com/jenkins-x/chyle v0.0.0-20180226080600-68f7a93a63ec
go: finding k8s.io/api v0.0.0-20180712090710-2d6f90ab1293
go: finding github.com/peterbourgon/diskv v2.0.1+incompatible
go: finding golang.org/x/net v0.0.0-20180719180050-a680a1efc54d
go: finding github.com/jbrukh/bayesian v0.0.0-20161210175230-bf3f261f9a9c
go: finding gopkg.in/airbrake/gobrake.v2 v2.0.9
go: finding k8s.io/kube-openapi v0.0.0-20180719232738-d8ea2fe547a4
go: finding github.com/spf13/pflag v1.0.1
go: finding github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: finding github.com/lusis/slack-test v0.0.0-20180109053238-3c758769bfa6
go: finding github.com/pelletier/go-buffruneio v0.2.0
go: finding github.com/danwakefield/fnmatch v0.0.0-20160403171240-cbb64ac3d964
go: finding github.com/MakeNowJust/heredoc v0.0.0-20171113091838-e9091a26100e
go: finding github.com/bouk/monkey v0.0.0-20180215074647-5df1f207ff77
go: finding gopkg.in/yaml.v2 v2.2.1
go: finding github.com/chromedp/cdproto v0.0.0-20180720050708-57cf4773008d
go: finding go.opencensus.io v0.14.0
go: finding github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
go: finding github.com/shurcooL/githubv4 v0.0.0-20180509030948-19298c78142b
go: finding github.com/alcortesm/tgz v0.0.0-20161220082320-9c5fe88206d7
go: finding github.com/Sirupsen/logrus v1.0.6
go: finding github.com/pkg/errors v0.8.0
go: finding gopkg.in/ini.v1 v1.38.1
go: finding github.com/Jeffail/gabs v0.0.0-20180420203615-7a0fed31069a
go: finding github.com/beevik/etree v1.0.1
go: finding github.com/kevinburke/ssh_config v0.0.0-20180317175531-9fc7bb800b55
go: finding github.com/emirpasic/gods v1.9.0
go: finding gopkg.in/src-d/go-billy.v4 v4.2.0
go: finding github.com/googleapis/gnostic v0.2.0
go: finding github.com/cpuguy83/go-md2man v1.0.8
go: finding github.com/google/btree v0.0.0-20180124185431-e89373fe6b4a
go: finding golang.org/x/sys v0.0.0-20180715085529-ac767d655b30
go: finding github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: finding github.com/blang/semver v3.5.1+incompatible
go: finding gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: finding github.com/andygrunwald/go-gerrit v0.0.0-20171029143327-95b11af228a1
go: finding golang.org/x/crypto v0.0.0-20180723164146-c126467f60eb
go: finding github.com/gobwas/glob v0.2.3
go: finding github.com/onsi/gomega v1.4.1
go: finding github.com/gorilla/websocket v1.2.0
go: finding k8s.io/client-go v0.0.0-20180621073103-e5bc2a7bbbdf
go: finding github.com/hinshun/vt10x v0.0.0-20180809195222-d55458df857c
go: finding github.com/elazarl/goproxy v0.0.0-20180725130230-947c36da3153
go: finding github.com/flynn/go-shlex v0.0.0-20150515145356-3f9db97f8568
go: finding github.com/sirupsen/logrus v1.0.6
go: finding github.com/mitchellh/go-homedir v0.0.0-20180523094522-3864e76763d9
go: finding github.com/mattn/go-isatty v0.0.3
go: finding github.com/google/gofuzz v0.0.0-20170612174753-24818f796faf
go: finding gopkg.in/gemnasium/logrus-airbrake-hook.v2 v2.1.2
go: finding github.com/jenkins-x/draft-repo v0.0.0-20180417100212-2f66cc518135
go: finding github.com/gorilla/securecookie v1.1.1
go: finding github.com/Pallinder/go-randomdata v0.0.0-20180616180521-15df0648130a
go: finding github.com/fatih/structs v1.0.0
go: finding github.com/pelletier/go-toml v1.2.0
go: finding github.com/heptio/sonobuoy v0.0.0-20180723203701-093f4a7fc64e
go: finding github.com/nlopes/slack v0.0.0-20180721202243-347a74b1ea30
go: finding golang.org/x/time v0.0.0-20180412165947-fbb02b2291d2
go: finding github.com/alexflint/go-filemutex v0.0.0-20171028004239-d358565f3c3f
go: finding github.com/jtolds/gls v4.2.1+incompatible
go: finding github.com/chromedp/cdproto v0.0.0-20180703215205-c125a34ea3b3
go: finding github.com/trivago/tgo v1.0.1
go: finding github.com/gfleury/go-bitbucket-v1 v0.0.0-20180608194953-66450bf15655
go: finding github.com/spf13/jwalterweatherman v0.0.0-20180109140146-7c0cea34c8ec
go: finding github.com/prometheus/common v0.0.0-20180518154759-7600349dcfe1
go: finding github.com/spf13/cobra v0.0.3
go: finding github.com/googleapis/gax-go v2.0.0+incompatible
go: finding github.com/denormal/go-gitignore v0.0.0-20180713143441-75ce8f3e513c
go: finding github.com/russross/blackfriday v1.5.1
go: finding github.com/lusis/go-slackbot v0.0.0-20180109053408-401027ccfef5
go: finding github.com/knq/sysutil v0.0.0-20180306023629-0218e141a794
go: finding github.com/go-ini/ini v1.38.1
go: finding github.com/gorilla/context v1.1.1
go: finding github.com/satori/go.uuid v1.2.0
go: finding github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
go: finding github.com/pkg/browser v0.0.0-20170505125900-c90ca0c84f15
go: finding github.com/gorilla/mux v1.6.2
go: finding google.golang.org/api v0.0.0-20180724000608-2c45710c7f3f
go: finding github.com/pborman/uuid v0.0.0-20170612153648-e790cca94e6c
go: finding github.com/sergi/go-diff v1.0.0
go: finding github.com/knative/build v0.1.1
go: finding k8s.io/test-infra v0.0.0-20180814210940-a362b01ca57b
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding github.com/spf13/viper v1.0.2
go: finding github.com/andygrunwald/go-jira v1.5.0
go: finding github.com/disintegration/imaging v1.4.2
go: finding github.com/smartystreets/assertions v0.0.0-20180803164922-886ec427f6b9
go: finding k8s.io/apiextensions-apiserver v0.0.0-20180621085152-bbc52469f98b
go: finding github.com/anmitsu/go-shlex v0.0.0-20161002113705-648efa622239
go: finding github.com/google/go-cmp v0.2.0
go: error loading module requirements
go: finding github.com/wbrefvem/go-gitlab v0.0.0-20180628044536-ecc4c5b8455a
go: finding github.com/go-ini/ini v1.25.4
go: finding github.com/jmespath/go-jmespath v0.0.0-20160202185014-0b12d6b521d8
go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: github.com/wbrefvem/go-gitlab@v0.0.0-20180628044536-ecc4c5b8455a: unknown revision ecc4c5b8455a
go: error loading module requirements
CGO_ENABLED=0 go build -ldflags " -X github.com/jenkins-x/jx/pkg/version.Version=-dev+a88af53 -X github.com/jenkins-x/jx/pkg/version.Revision='a88af53' -X github.com/jenkins-x/jx/pkg/version.Branch='master' -X github.com/jenkins-x/jx/pkg/version.BuildDate='20180829-21:38:21' -X github.com/jenkins-x/jx/pkg/version.GoVersion='1.11'" -o build/jx cmd/jx/jx.go
go: finding github.com/wbrefvem/go-gitlab v0.0.0-20180628044536-ecc4c5b8455a
go: github.com/wbrefvem/go-gitlab@v0.0.0-20180628044536-ecc4c5b8455a: unknown revision ecc4c5b8455a
go: error loading module requirements
Makefile:58: recipe for target 'build' failed
make: *** [build] Error 1
```

</p>
</details>

**Comment by ccojocar** [comment]
@i0n should we close this PR, and create another one for migration to Go modules?

**Comment by ccojocar** [comment]
Closing this for now since it is a bit out of sync. We will follow with with a new PR.

**Pull request closed without merging**
