### PR TITLE
fix: update Go supported versions in CONTRIBUTING.MD

### PR DESCRIPTION
**Pull request by hervelemeur**
#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [X] Change is covered by existing or new tests.

#### Description

[This PR](https://github.com/j…enkins-x/jx/pull/7025) has been merged but CONTRIBUTING.MD is still mentioning 1.12 as the upper supported version. The documentation repository has been updated, here is a PR to update it here too.

#### Which issue this PR fixes

Relates to/fixes https://github.com/jenkins-x/jx-docs/issues/2813

### CODE REVIEW

**Comment by abayer** [comment]
Mind changing the commit message and PR title to `fix: ...` instead of `doc: ...`? And use `git commit --signoff`? =)

**Comment by hervelemeur** [comment]
> Mind changing the commit message and PR title to `fix: ...` instead of `doc: ...`?
No problem :)

>  And use `git commit --signoff`? =)
Already fixed ^^

**Comment by abayer** [comment]
yay!

**Comment by hervelemeur** [comment]
@abayer can you tell me more about these build errors?

**Comment by ankitm123** [comment]
@hervelemeur if you retest they would go away.

**Comment by abayer** [comment]
It's due to quay.io being down - I'll retest here once it's up.

**Pull request merged**
