### PR TITLE
Wrap Exposecontroller UrlTemplate config in quotes

### LINKED ISSUE #5800: jx upgrade ingress lost all ingress rules
### Summary 

`jx upgrade ingress` lost all ingress rules

### Steps to reproduce the behavior

`jx upgrade ingress ` and set custom template to `"{{.Service}}.{{.Domain}}"`

### Expected behavior

update success

### Actual behavior

the console shows ingress rules created. but that's not true, I cannot find any ingress rules after that.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.780
Kubernetes cluster v1.13.10-eks-5ac0f1
kubectl            v1.16.0
helm client        Client: v2.14.3+g0e7f3b6
git                2.23.0
Operating System   Mac OS X 10.14.6 build 18G103
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

I'm using multi-cluster, this happens on the production cluster.

### PR DESCRIPTION
**Pull request by lhr0909**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

This change is to react to https://github.com/jenkins-x/exposecontroller/pull/191 this change in exposecontroller template. Need to add quote around the template generation code in `jx` as well.

#### Which issue this PR fixes

fixes #5800
fixes https://github.com/jenkins-x/exposecontroller/issues/192

### CODE REVIEW

**Comment by lhr0909** [comment]
@jiangytcn I am almost positive. Right now I cannot get the tests to pass, but I feel where I am updating it can help resolve the issue. If there is anyone on the Jenkins X team or @rawlingsj can come in and help out, that'd be great.

**Comment by hferentschik** [comment]
So the tekon ingress tests keep failing:

```
configmap "exposecontroller" deleted
serviceaccount "exposecontroller" deleted
role.rbac.authorization.k8s.io "exposecontroller" deleted
rolebinding.rbac.authorization.k8s.io "exposecontroller" deleted
Ingress rules recreated
Waiting for TLS certificates to be issued...
• Failure [306.219 seconds]
upgrade ingress
/tmp/jenkins-x/bdd-**/test/suite/ingress/**_upgrade_ingress.go:256
  Given valid parameters
  /tmp/jenkins-x/bdd-**/test/suite/ingress/**_upgrade_ingress.go:300
    when running upgrade ingress
    /tmp/jenkins-x/bdd-**/test/suite/ingress/**_upgrade_ingress.go:301
      creates the ingress resource and fetch a TLS certificate for services from specified namespace
       [It]
      /tmp/jenkins-x/bdd-**/test/suite/ingress/**_upgrade_ingress.go:302
      Timed out after 300.000s.
      Expected process to exit.  It did not.
      /tmp/jenkins-x/bdd-**/test/utils/runner/runner.go:67
------------------------------
Summarizing 3 Failures:
[Fail] upgrade ingress
 Given valid parameters when running upgrade ingress [It] creates the ingress resource for services from specified namespace
 
/tmp/jenkins-x/bdd-**/test/suite/ingress/**_upgrade_ingress.go:247
[Fail] upgrade ingress
 Given valid parameters when running upgrade ingress [It] creates the ingress resource only for selected service from specified namespace
 
/tmp/jenkins-x/bdd-**/test/suite/ingress/**_upgrade_ingress.go:247
[Fail] upgrade ingress
 Given valid parameters when running upgrade ingress [It] creates the ingress resource and fetch a TLS certificate for services from specified namespace
 
/tmp/jenkins-x/bdd-**/test/utils/runner/runner.go:67
Ran 3 of 3 Specs in 363.605 seconds
FAIL! -- 0 Passed | 3 Failed | 0 Pending | 0 Skipped
```

I am not sure whether this is due to a problem with the pull request or whether the tests need updating as well. @ccojocar @abayer - wdyt? 

Would be nice to get this resolved one way or another.

**Comment by hferentschik** [comment]
@lhr0909, any idea why your issues would cause problems with the BDD tests - https://github.com/jenkins-x/bdd-jx/blob/master/test/suite/ingress/jx_upgrade_ingress.go?

I am not sure whether this test gives us a false negative atm, or whether there is something wrong with the test. I am actually to locally reproduce this test failure. If you are interested I could help you set things up in order to run these BDD test locally as well. WDYT?

**Comment by hferentschik** [comment]
I am going to close this PR in favour of #6130.

#6130 adds the quotes around the URL template as well, but only if the template is not empty. I think for non-empty URL templates the quotes are indeed needs.

That said, `jx upgrade ingress` seems to work with an empty URL template, but not with a custom one. Let's try to get #6130 in since I think it is a step forward anyways.

**Pull request closed without merging**
