### PR TITLE
feat:(install) Support JFrog Artifactory

### PR DESCRIPTION
**Pull request by ccojocar**
@yahavi  I restored the original PR #1274 after being merged and reverted.

 @rawlingsj Please could you post here more details regarding the issue caused by this PR?

### CODE REVIEW

**Comment by rawlingsj** [comment]
Sure thing so when testing the Jenkins X codeship integration we started being prompted to choose between nexus and artifactsory in the CI build which causes the job to fail:

External loadbalancer created
Waiting to find the external host name of the ingress controller Service in namespace kube-system with name jxing-nginx-ingress-controller
No domain flag provided so using default 35.205.239.180.nip.io to generate Ingress rules
nginx ingress controller installed and configured
Lets set up a git username and API token to be able to perform CI/CD
```
? Select binary repository manager:  [Use arrows to move, type to filter, ? for more help]
 Nexus
  Artifactory
mand didn't output anything for 10 minutes, thus we stopped it.
Please make sure your steps regularly print to standard out or standard error.
If the error is on our end please inform us so we can help you to fix this.
--------------------------------------------------------------------------------
```

I just had a quick look at the commit and there's no default + batch check before the CLI wizard asking for nexus / artifactory.  Though not sure how this passed in the BDD tests as I'd expect them to suffer the same issue.

**Comment by ccojocar** [comment]
@rawlingsj I configured `Nexus` as default repository manager when the `headless` flag is on. it shouldn't prompt now anymore when `install` is executed in `headless` mode.

**Comment by eyalbe4** [comment]
Thanks @ccojocar,
Please let us know if there's anything we can do to help validate this.

**Comment by ccojocar** [comment]
@eyalbe4 The PR still needs some work. The maven configuration is incomplete. It does not point to the artifactory URL. 

It seems also that the `artifactory secrets` gets deleted after a while.

**Comment by yahavi** [comment]
@ccojocar,
This pull request is coupled with 2 other pull requests:
jenkins-x/jenkins-x-image#32 - For the Artifactory plugin
jenkins-x/draft-packs#50 - For the Artifactory pipeline scripts

To provide out-of-the-box Artifactory support with full support and functionality, we need the *Jenkins-Artifactory plugin* to be installed on Jenkins. The `jenkins-x-image` PR includes *Jenkins-Artifactory plugin*.

During the installation, if Artifactory was chosen, the JX CLI requires the Artifactory instance credentials. Then, the credentials are mounted into */var/artifactory* in the Jenkins node. During startup, the Artifactory Plugin searches for the Artifactory credentials in */var/artifactory/*. If credentials are found in this directory, then the Artifactory Plugin persists the credentials. That’s the reason why *artifactory secrets* is not needed anymore after installation.

The PR in `draft-packs` includes pipeline scripts which use the [Artifactory Pipeline APIs](https://www.jfrog.com/confluence/display/RTF/Working+With+Pipeline+Jobs+in+Jenkins) added by the Artifactory Plugin. To move forward faster, I guess we don't have to merge this PR now. We can continue discussing it later on.

Please let me know if additional infiormation is needed.

Thanks!

**Comment by yahavi** [comment]
@ccojocar,
About the mounting - Let the code speak for itself: https://github.com/jenkins-x/jx/pull/1384/files#diff-4fceaeb279093560c5e080c2d91f7cb7R975

The functionality in this PR allows using your organisation Artifactory with Jenkins X.
This is how we’d like to have our CI/CD pipeline se up with Jenkins X and I assume this is a typical use case for other organisations which already use Artifactory.

We’d be happy to create a follow up PR that will also allow setting up an Artifactory instance as a chart in the cluster. We can make sure to use a trial Artifactory instance which will not require a license for a while. This way, all use cases will be covered.

I can create the draft-packs in a way that maven and gradle are used natively, but some parts of pipeline script will need to change so that it works properly. I suggest we take the draft-packs PR out of this scope and work on it separately.

Please let me know what you think.

**Comment by yahavi** [comment]
@ccojocar,

Do you need my help validating the PR?
LMK - I'd be happy to help

**Comment by ccojocar** [comment]
@yahavi Right now, I am focusing on another task, no much time to deal with this. 

It would be great, if you could provide a working example with Artifactory running as a service in Kubernetes:
- quick-start project which publishes the artifacts in Artifactory using maven/gradle
- import it in jx
- some documentation how to configure and run it

**Comment by yahavi** [comment]
Here's how you can test the new functionality:

Before merging the 3 pull requests, do the following (after the pull requests are merged the following will not be needed):
1. **Create the docker image**
You can use my image in: https://hub.docker.com/r/yahavi/jenkinsx/ or you can create your own:
git clone `https://github.com/yahavi/jenkins-x-image`
`cd jenkins-x-image`
Build the docker image: `docker build . -t <username>/jenkinsx:<tag>`
Upload the docker image to Dockerhub: 
`docker login`
`docker push <username>/jenkinsx:<tag>`

Clone cloud-environments and add the Docker image to your cloud environment, in `myvalues.yml` file.
```
jenkins:
    Master:
        Image: "<username>/jenkinsx"
        ImageTag: "<tag>"
```

You can also use my image if you want:
```
jenkins:
    Master:
        Image: "yahavi/jenkinsx"
        ImageTag: "2.16.2"
```

2. **Install jx**
`cd cloud-environments`
`jx install --local-cloud-environment` 
 Please use jx from the pull request

3. **Replace draft packs**
`jx edit buildpack`
Build pack git clone URL: https://github.com/yahavi/draft-packs.git
Build pack git ref: 2.1

4. **Install demo application**
`jx create quickstart -g yahavi -f jxDemo`
Project name demo

---
I hope the above steps will make testing this functionality a lot easier. I took me a few hours to update my local environment with all of the recent changes made to Jenkins-X. Hopefully, we can finalize the testing and validation soon. 

Looking forward for your feedback,
Thank you.

**Comment by ccojocar** [comment]
I am closing this in favour of #1753.

**Pull request closed without merging**
