### PR TITLE
chore: fix spelling of healthy

### PR DESCRIPTION
**Pull request by edwardmlyte**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by hferentschik** [comment]
@edwardmlyte, any chance you could change your commit message. It should be in the [conventional commit message](https://www.conventionalcommits.org/en/v1.0.0-beta.3/) format.

Something like "chore: fix spelling of healthy" should do.

**Comment by edwardmlyte** [comment]
updated @hferentschik

**Pull request merged**
