### PR TITLE
feat: Add a step to get a dependency version from the dependency matrix

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

Can be used either with the version stream or a local directory.

First step of #5595

#### Special notes for the reviewer(s)

/assign @cagiti 
/assign @pmuir 

#### Which issue this PR fixes

n/a

### CODE REVIEW

**Comment by abayer** [comment]
So the idea here is that we'll have an override of `pipelineConfig.pipelines.release.setVersion` in `jenkins-x-builders` that will have something like `jx step next-version --version $(jx step get dependency-version --host=github.com --owner=jenkins-x --repo=jx --dir . | sed 's/.*: \(.*\)/\1/') --use-git-tag-only --tag`.

The output of `jx step get dependency-version --host=github.com --owner=jenkins-x --repo=jx --dir .` will be something like `Version for host github.com, owner jenkins-x, repo jx in matrix at . is: 2.0.784`

**Comment by cagiti** [comment]
👍

**Comment by abayer** [comment]
Moved things around a little and added a test - should be good to go.

**Pull request merged**
