### PR TITLE
feat: Moved tenant cluster delegation to install phase

### PR DESCRIPTION
**Pull request by cagiti**

### CODE REVIEW

**Comment by rawlingsj** [comment]
@cagiti I just saw this in the logs of the BDD test failure...
```
error: Failed to install team bdd-ghe-jx-pr-4193-9: A tenannt-service URL is required to use this option
```

**Comment by cagiti** [comment]
> @cagiti I just saw this in the logs of the BDD test failure...
> 
> ```
> error: Failed to install team bdd-ghe-jx-pr-4193-9: A tenannt-service URL is required to use this option
> ```

weird how the bdd tests on the initial change didn't fail, I'm guessing the bdd test reuses a cluster?

**Pull request merged**
