### PR TITLE
[wip] fix: make sure git providers created successfully 

### LINKED ISSUE #6391: failed to add new git provider after boot
### Summary 
deploy jx with ghe, but failed to add extra git provider with 

jx create git server -k gitea -u http://github.192.168.1.12.nip.io -n abc

### Steps to reproduce the behavior
1. deploy gitea
1. deploy jx with boot and ghe setting
2. add new git provider with `gitea`
jx create git server -k gitea -u  _git_provider_url_ -n localgit

### Expected behavior
successfully add new git provder

### Actual behavior
failed with 
`error: failed to save GitAuthConfigService: current user for "http://github.192.168.1.12.nip.io" server is empty
`
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1094
Kubernetes cluster v1.16.3-k3s.2
kubectl            v1.17.0
helm client        Client: v2.14.2+ga8b13cc
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

k3s

### Operating system / Environment
VERSION="18.04.3 LTS (Bionic Beaver)"

### PR DESCRIPTION
**Pull request by jiangytcn**
Signed-off-by: Jiang Yi Tao <jiangyt.cn@gmail.com>

#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [X] Change is covered by existing or new tests.

#### Description
failed to add git providers after boot. 
The output after fix:
```
~/go/src/github.com/jenkins-x/jx light.ystacks.com on  fix-git-server! ⌚ 17:26:08
$ jx create git server -k gitea -u http://github.192.168.1.12.nip.io -n undercloud                                                             ‹ruby-2.6.3›  /home/jiangytcn
WARNING: Added Git server jx-pipeline-git-gitea-undercloud for URL http://github.192.168.1.12.nip.io with empty user
Added Git server undercloud for URL http://github.192.168.1.12.nip.io
already has GitService undercloud in namespace jx for URL http://github.192.168.1.12.nip.io
Ensured we have a GitService called undercloud for URL http://github.192.168.1.12.nip.io in namespace jx

~/go/src/github.com/jenkins-x/jx light.ystacks.com on  fix-git-server! ⌚ 17:26:15
$ jx get git                                                                                                                                   ‹ruby-2.6.3›  /home/jiangytcn
WARNING: Git server undercloud for URL http://github.192.168.1.12.nip.io having empty user
Name       Kind   URL
ghe        github https://github.xxx.com
undercloud gitea  http://github.192.168.1.12.nip.io

~/go/src/github.com/jenkins-x/jx light.ystacks.com on  fix-git-server! ⌚ 17:26:17
$ jx create git token jiangytcn -n undercloud -t e98ed0c7f8686bf1c6679df63fbc266681edc687                                                      ‹ruby-2.6.3›  /home/jiangytcn
WARNING: Git server undercloud for URL http://github.192.168.1.12.nip.io having empty user
already has GitService undercloud in namespace jx for URL http://github.192.168.1.12.nip.io
Ensured we have a GitService called undercloud for URL http://github.192.168.1.12.nip.io in namespace jx
Created user jiangytcn API Token for Git server undercloud at http://github.192.168.1.12.nip.io

~/go/src/github.com/jenkins-x/jx light.ystacks.com on  fix-git-server! ⌚ 17:26:21
$ jx get git                                                                                                                                   ‹ruby-2.6.3›  /home/jiangytcn
Name       Kind   URL
ghe        github https://github.xxx.com
undercloud gitea  http://github.192.168.1.12.nip.io
```
#### Special notes for the reviewer(s)

@ccojocar 

#### Which issue this PR fixes

fixes #6391

### CODE REVIEW

**Comment by abayer** [comment]
There are a few test failures:

```
=== Failed
=== FAIL: pkg/auth TestSaveConfig/save_invalid_config_into_kubernetes_secret_with_empty_credentials (0.00s)
    --- FAIL: TestSaveConfig/save_invalid_config_into_kubernetes_secret_with_empty_credentials (0.00s)
        kube_config_handler_test.go:772: 
            	Error Trace:	kube_config_handler_test.go:772
            	Error:      	An error is expected but got nil.
            	Test:       	TestSaveConfig/save_invalid_config_into_kubernetes_secret_with_empty_credentials
            	Messages:   	should save config into secret with an error
=== FAIL: pkg/auth TestSaveConfig/save_invalid_config_into_kubernetes_secret_with_empty_username (0.00s)
WARNING: Git server GitHub for URL https://github.com having empty user
    --- FAIL: TestSaveConfig/save_invalid_config_into_kubernetes_secret_with_empty_username (0.00s)
        kube_config_handler_test.go:772: 
            	Error Trace:	kube_config_handler_test.go:772
            	Error:      	An error is expected but got nil.
            	Test:       	TestSaveConfig/save_invalid_config_into_kubernetes_secret_with_empty_username
            	Messages:   	should save config into secret with an error
```

**Comment by jiangytcn** [comment]
hi @abayer I'd like to seek your suggestion on the implementation for such feature. 
The issue i  m trying to fix is to let user create git server with empty user, and then add user for it. 
that's why   updated the logic of here. 

I can fix the test case in `kube_config_handler_test.go` to address the integration issue, however, better to understand  the community's direction about this. 

Or let user provide an `user` as an required parameter when adding new git server ? 

Please advise, thanks

**Comment by ccojocar** [comment]
> hi @abayer I'd like to seek your suggestion on the implementation for such feature.
The issue i m trying to fix is to let user create git server with empty user, and then add user for it.
that's why updated the logic of here.

I think that we should initially have a server which has a user auth. This config would be ready to be used.

> Or let user provide an user as an required parameter when adding new git server ?

I would prefer that we extend the command to add the user authentication instead of allowing server without any user auth.

**Comment by ccojocar** [comment]
@jiangytcn Do you have any plans to follow up on this? Do you need any help? Thanks!

**Comment by jiangytcn** [comment]
thanks @ccojocar . just had the vacation, I'll start to implement this in recent days.

**Comment by jiangytcn** [comment]
would create new one once finished.

**Pull request closed without merging**
