### PR TITLE
Upgraded AWS SDK

### PR DESCRIPTION
**Pull request by hekonsek**
Basically executed `dep ensure -update github.com/aws/aws-sdk-go` and performed some manual regression tests.

### CODE REVIEW

**Comment by hekonsek** [comment]
Is that one still failing on CI? If so, can you paste Jenkins job output here? I cannot access your Jenkins instance. I cannot reproduce build error on my local machine :( .

**Comment by ccojocar** [comment]
Failed BDD test:

```
        + jx promote -b --all-auto --timeout 1h --version 0.0.1

        Promoting app bdd-test-spring-1536068369 version 0.0.1 to namespace pr-1579-2-staging

        Created Pull Request: https://github.com/****/environment-stormhelix-staging/pull/1

        

        Failed to query the Pull Request last commit status for https://github.com/****/environment-stormhelix-staging/pull/1 ref dcd489a0591231ea152e136b5f9013eae1c39c2e Could not find a status for repository ****/environment-stormhelix-staging with ref dcd489a0591231ea152e136b5f9013eae1c39c2e

        Failed to query the Pull Request last commit status for https://github.com/****/environment-stormhelix-staging/pull/1 ref dcd489a0591231ea152e136b5f9013eae1c39c2e Could not find a status for repository ****/environment-stormhelix-staging with ref dcd489a0591231ea152e136b5f9013eae1c39c2e

        Failed to query the Pull Request last commit status for https://github.com/****/environment-stormhelix-staging/pull/1 ref dcd489a0591231ea152e136b5f9013eae1c39c2e Could not find a status for repository ****/environment-stormhelix-staging with ref dcd489a0591231ea152e136b5f9013eae1c39c2e

        Pull Request https://github.com/****/environment-stormhelix-staging/pull/1 is merged at sha c956387943d5b36f34b6d84225bfa06c07f59557

        Merge commit has not yet any statuses on repo ****/environment-stormhelix-staging merge sha c956387943d5b36f34b6d84225bfa06c07f59557

        merge status: pending for URL https://api.github.com/repos/****/environment-stormhelix-staging/statuses/c956387943d5b36f34b6d84225bfa06c07f59557 with target: http://jenkins.pr-1579-2.104.155.31.11.nip.io/job/****/job/environment-stormhelix-staging/job/master/2/display/redirect description: This commit is being built

EXITCODE   0SIGQUIT: quit

PC=0x45ee91 m=0 sigcode=0



goroutine 0 [idle]:

runtime.futex(0x22446a0, 0x80, 0x0, 0x0, 0x7fc300000000, 0x20300000000000, 0x0, 0x0, 0x7ffea4d86400, 0x40c5f2, ...)

	/usr/local/go/src/runtime/sys_linux_amd64.s:531 +0x21

runtime.futexsleep(0x22446a0, 0x7ffe00000000, 0xffffffffffffffff)

	/usr/local/go/src/runtime/os_linux.go:46 +0x4b

runtime.notesleep(0x22446a0)

	/usr/local/go/src/runtime/lock_futex.go:151 +0xa2

runtime.stopm()

	/usr/local/go/src/runtime/proc.go:2016 +0xe3

runtime.findrunnable(0xc000054f00, 0x0)

	/usr/local/go/src/runtime/proc.go:2487 +0x4dc

runtime.schedule()

	/usr/local/go/src/runtime/proc.go:2613 +0x13a

runtime.park_m(0xc0000a3c80)

	/usr/local/go/src/runtime/proc.go:2676 +0xae

runtime.mcall(0x0)

	/usr/local/go/src/runtime/asm_amd64.s:299 +0x5b



goroutine 1 [chan send, 9 minutes]:

github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog.(*runner).concurrent(0xc0001472c0, 0x6, 0xc0003e87a1)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog/run.go:58 +0x139

github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog.RunWithOptions(0x14f1425, 0x5, 0x157ad20, 0x0, 0x1551360b2bce14fc, 0x0, 0x0, 0x0, 0x14f3f06, 0x8, ...)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog/run.go:165 +0x6d8

github.com/jenkins-x/godog-jx.TestMain(0xc000382e00)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/godog_test.go:39 +0x28b

main.main()

	_testmain.go:38 +0x13d



goroutine 6 [chan receive]:

github.com/jenkins-x/godog-jx/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x2243620)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/vendor/github.com/golang/glog/glog.go:879 +0x8b

created by github.com/jenkins-x/godog-jx/vendor/github.com/golang/glog.init.0

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/vendor/github.com/golang/glog/glog.go:410 +0x203



goroutine 10 [sleep]:

time.Sleep(0x3b9aca00)

	/usr/local/go/src/runtime/time.go:105 +0x14f

github.com/jenkins-x/godog-jx/vendor/github.com/jenkins-x/golang-jenkins.Poll(0x3b9aca00, 0xae9f7bcc000, 0xc0001882d0, 0x83, 0xc0003183a0, 0xc0001882d0, 0x83)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/vendor/github.com/jenkins-x/golang-jenkins/poll.go:41 +0x82

github.com/jenkins-x/godog-jx/jenkins.WaitForBuildToFinish(0xc0003a8700, 0xc000194000, 0xb, 0xd, 0xc000041e00, 0x2e, 0xc000368b46, 0x6, 0xc0002d6000, 0x31, ...)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/jenkins/jenkins_helpers.go:117 +0x548

github.com/jenkins-x/godog-jx/jenkins.ThereShouldBeAJobThatCompletesSuccessfully(0xc000043600, 0x31, 0xc0003a8700, 0x1, 0x1)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/jenkins/jenkins_helpers.go:179 +0x1c9

github.com/jenkins-x/godog-jx/common.(*Test).TheApplicationShouldBeBuiltAndPromotedViaCICD(0xc00017c230, 0xc000345380, 0x10)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/common/common.go:70 +0x2c4

github.com/jenkins-x/godog-jx/common.(*Test).TheApplicationShouldBeBuiltAndPromotedViaCICD-fm(0x0, 0x0)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/import_test.go:92 +0x2a

reflect.Value.call(0x12afb00, 0xc0003374b0, 0x13, 0x14f06f6, 0x4, 0x0, 0x0, 0x0, 0xc000318801, 0x0, ...)

	/usr/local/go/src/reflect/value.go:447 +0x449

reflect.Value.Call(0x12afb00, 0xc0003374b0, 0x13, 0x0, 0x0, 0x0, 0xc000318820, 0x1, 0x40a78b)

	/usr/local/go/src/reflect/value.go:308 +0xa4

github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog.(*StepDef).run(0xc00017d7a0, 0xc0002d82c8, 0x38)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog/stepdef.go:201 +0x2995

github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog.(*Suite).runStep(0xc000512900, 0xc0001a1e50, 0x0, 0x0, 0x0, 0x0)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog/suite.go:303 +0x1e7

github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog.(*Suite).runSteps(0xc000512900, 0xc000147240, 0x6, 0x8, 0xc0001680c0, 0xc000345e58)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog/suite.go:388 +0x7a

github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog.(*Suite).runScenario(0xc000512900, 0xc000350000, 0x0, 0xc000512900, 0x1)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog/suite.go:597 +0x1d1

github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog.(*Suite).runFeature(0xc000512900, 0xc000147280)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog/suite.go:566 +0x54f

github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog.(*Suite).run(0xc000512900)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog/suite.go:220 +0xaf

github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog.(*runner).concurrent.func1(0xc0001881b0, 0xc0001472c0, 0xc00036900b, 0xc000147280)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog/run.go:50 +0x122

created by github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog.(*runner).concurrent

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/vendor/github.com/DATA-DOG/godog/run.go:35 +0xef



goroutine 67 [IO wait, 9 minutes]:

internal/poll.runtime_pollWait(0x7fc393269d60, 0x72, 0xc000083868)

	/usr/local/go/src/runtime/netpoll.go:173 +0x66

internal/poll.(*pollDesc).wait(0xc0001c0f98, 0x72, 0xffffffffffffff00, 0x168c520, 0x21bc798)

	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a

internal/poll.(*pollDesc).waitRead(0xc0001c0f98, 0xc0000ed000, 0x400, 0x400)

	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d

internal/poll.(*FD).Read(0xc0001c0f80, 0xc0000ed000, 0x400, 0x400, 0x0, 0x0, 0x0)

	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x179

net.(*netFD).Read(0xc0001c0f80, 0xc0000ed000, 0x400, 0x400, 0x40a78b, 0xc000030000, 0x135c6c0)

	/usr/local/go/src/net/fd_unix.go:202 +0x4f

net.(*conn).Read(0xc0001c4010, 0xc0000ed000, 0x400, 0x400, 0x0, 0x0, 0x0)

	/usr/local/go/src/net/net.go:177 +0x68

crypto/tls.(*block).readFromUntil(0xc00036a6c0, 0x168adc0, 0xc0001c4010, 0x5, 0xc0001c4010, 0x0)

	/usr/local/go/src/crypto/tls/conn.go:491 +0x89

crypto/tls.(*Conn).readRecord(0xc000450700, 0x157cc17, 0xc000450828, 0x1)

	/usr/local/go/src/crypto/tls/conn.go:592 +0xe0

crypto/tls.(*Conn).Read(0xc000450700, 0xc0004b8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)

	/usr/local/go/src/crypto/tls/conn.go:1144 +0xf1

bufio.(*Reader).Read(0xc0001c6720, 0xc00013a118, 0x9, 0x9, 0xc0005c4058, 0xc0005c2140, 0xc000083d08)

	/usr/local/go/src/bufio/bufio.go:216 +0x22f

io.ReadAtLeast(0x1689240, 0xc0001c6720, 0xc00013a118, 0x9, 0x9, 0x9, 0xc000083cd8, 0x407c24, 0xc0005c4000)

	/usr/local/go/src/io/io.go:310 +0x88

io.ReadFull(0x1689240, 0xc0001c6720, 0xc00013a118, 0x9, 0x9, 0xc000083d08, 0xc000000001, 0xc000371650)

	/usr/local/go/src/io/io.go:329 +0x58

github.com/jenkins-x/godog-jx/vendor/golang.org/x/net/http2.readFrameHeader(0xc00013a118, 0x9, 0x9, 0x1689240, 0xc0001c6720, 0x0, 0x0, 0xc000083fb0, 0xc000255e00)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/vendor/golang.org/x/net/http2/frame.go:237 +0x7b

github.com/jenkins-x/godog-jx/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc00013a0e0, 0xc00036a360, 0x0, 0x0, 0x0)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/vendor/golang.org/x/net/http2/frame.go:492 +0xa3

github.com/jenkins-x/godog-jx/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000083fb0, 0x157ba58, 0xc0004707b0)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/vendor/golang.org/x/net/http2/transport.go:1428 +0x9c

github.com/jenkins-x/godog-jx/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc0000d4680)

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/vendor/golang.org/x/net/http2/transport.go:1354 +0x83

created by github.com/jenkins-x/godog-jx/vendor/golang.org/x/net/http2.(*Transport).newClientConn

	/home/jenkins/go/src/github.com/jenkins-x/godog-jx/vendor/golang.org/x/net/http2/transport.go:579 +0x602



goroutine 182 [select]:

net/http.(*persistConn).writeLoop(0xc0001a98c0)

	/usr/local/go/src/net/http/transport.go:1885 +0x113

created by net/http.(*Transport).dialConn

	/usr/local/go/src/net/http/transport.go:1339 +0x966



goroutine 181 [IO wait]:

internal/poll.runtime_pollWait(0x7fc393269c90, 0x72, 0xc00007fa88)

	/usr/local/go/src/runtime/netpoll.go:173 +0x66

internal/poll.(*pollDesc).wait(0xc0003b8998, 0x72, 0xffffffffffffff00, 0x168c520, 0x21bc798)

	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a

internal/poll.(*pollDesc).waitRead(0xc0003b8998, 0xc000669000, 0x1000, 0x1000)

	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d

internal/poll.(*FD).Read(0xc0003b8980, 0xc000669000, 0x1000, 0x1000, 0x0, 0x0, 0x0)

	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x179

net.(*netFD).Read(0xc0003b8980, 0xc000669000, 0x1000, 0x1000, 0x0, 0x0, 0xc00045e300)

	/usr/local/go/src/net/fd_unix.go:202 +0x4f

net.(*conn).Read(0xc0004c63d8, 0xc000669000, 0x1000, 0x1000, 0x0, 0x0, 0x0)

	/usr/local/go/src/net/net.go:177 +0x68

net/http.(*persistConn).Read(0xc0001a98c0, 0xc000669000, 0x1000, 0x1000, 0xc0003be360, 0xc0001a98c0, 0x0)

	/usr/local/go/src/net/http/transport.go:1497 +0x75

bufio.(*Reader).fill(0xc0000972c0)

	/usr/local/go/src/bufio/bufio.go:100 +0x106

bufio.(*Reader).Peek(0xc0000972c0, 0x1, 0x2, 0x0, 0x0, 0xc0000aec00, 0x0)

	/usr/local/go/src/bufio/bufio.go:132 +0x3f

net/http.(*persistConn).readLoop(0xc0001a98c0)

	/usr/local/go/src/net/http/transport.go:1645 +0x1a2

created by net/http.(*Transport).dialConn

	/usr/local/go/src/net/http/transport.go:1338 +0x941



rax    0xca

rbx    0x2244560

rcx    0x45ee93

rdx    0x0

rdi    0x22446a0

rsi    0x80

rbp    0x7ffea4d863c8

rsp    0x7ffea4d86380

r8     0x0

r9     0x0

r10    0x0

r11    0x286

r12    0x1

r13    0x1

r14    0x5

r15    0x0

rip    0x45ee91

rflags 0x286

cs     0x33

fs     0x0

gs     0x0

*** Test killed with quit: ran too long (10m0s).

exit status 2

FAIL	github.com/jenkins-x/godog-jx	600.205s

make: *** [jx-spring] Error 1

script returned exit code 2```

**Comment by hekonsek** [comment]
How do you execute that test? I'm doing this and can't see the issue:

```
$ git checkout aws-skd-upgrade-2 
$ make test && make build && echo "I'm OK!"
...
I'm OK!

**Comment by ccojocar** [comment]
It's `make bdd-tests` which are in a different repo `jenkins-x/godog-jx`. 

https://github.com/jenkins-x/jx/blob/a765e37533416cdc41ce344c5510acd8637416dc/Jenkinsfile#L77

**Pull request merged**
