### PR TITLE
chore: add vendor.json and external dependencies

### PR DESCRIPTION
**Pull request by sanketjpatel**
Using `govendor` to manage dependencies. Ran `govendor init` and `govendor add +external`.

https://github.com/kardianos/govendor#quick-start-also-see-the-faq

### CODE REVIEW

**Comment by sanketjpatel** [comment]
Unfortunately I can't see why the build breaks. Would it be possible to make the logs public?

**Comment by rawlingsj** [comment]
Unfortunately we're not able to make the logs public yet.  Here's the logs..
```
[jx] Running shell script
[j
+ make
CGO_ENABLED=0 GO15VENDOREXPERIMENT=1 go build -ldflags " -X github.com/jenkins-x/jx/pkg/version.Version=1.0.1 -X github.com/jenkins-x/jx/pkg/version.Revision='1fb3211' -X github.com/jenkins-x/jx/pkg/version.Branch='HEAD' -X github.com/jenkins-x/jx/pkg/version.BuildDate='20180511-16:51:31' -X github.com/jenkins-x/jx/pkg/version.GoVersion='1.9.2'" -o build/jx cmd/jx/jx.go
vendor/github.com/jenkins-x/jx/pkg/gits/gitea.go:9:2: cannot find package "code.gitea.io/sdk/gitea" in any of:
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/code.gitea.io/sdk/gitea (vendor tree)
	/usr/local/go/src/code.gitea.io/sdk/gitea (from $GOROOT)
	/home/jenkins/go/src/code.gitea.io/sdk/gitea (from $GOPATH)
vendor/github.com/jenkins-x/jx/pkg/jx/cmd/import.go:11:2: cannot find package "github.com/Azure/draft/pkg/draft/draftpath" in any of:
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/Azure/draft/pkg/draft/draftpath (vendor tree)
	/usr/local/go/src/github.com/Azure/draft/pkg/draft/draftpath (from $GOROOT)
	/home/jenkins/go/src/github.com/Azure/draft/pkg/draft/draftpath (from $GOPATH)
vendor/github.com/jenkins-x/jx/pkg/draft/draft.go:12:2: cannot find package "github.com/Azure/draft/pkg/draft/pack/repo" in any of:
```

**Comment by sanketjpatel** [comment]
Thanks @rawlingsj 
Seems like all dependencies weren't being vendored...

The reason I'm trying to do this is that we shouldn't need to vendor out tests and other non-useful files from the dependencies

https://github.com/jenkins-x/jx/pull/800#issue-187460280

**Comment by rawlingsj** [comment]
```
CGO_ENABLED=0 GO15VENDOREXPERIMENT=1 go build -ldflags " -X github.com/jenkins-x/jx/pkg/version.Version=1.0.1 -X github.com/jenkins-x/jx/pkg/version.Revision='862fe28' -X github.com/jenkins-x/jx/pkg/version.Branch='HEAD' -X github.com/jenkins-x/jx/pkg/version.BuildDate='20180511-18:19:28' -X github.com/jenkins-x/jx/pkg/version.GoVersion='1.9.2'" -o build/jx cmd/jx/jx.go
EXITCODE   0# github.com/jenkins-x/jx/vendor/github.com/cpuguy83/go-md2man/md2man
vendor/github.com/cpuguy83/go-md2man/md2man/roff.go:15:15: undefined: blackfriday.Extensions
make: *** [build] Error 2
```

**Comment by rawlingsj** [comment]
> The reason I'm trying to do this is that we shouldn't need to vendor out tests and other non-useful files from the dependencies.

OK - I guess I just worry slightly as it's a change to the way things have been working without issue.  But if this reduces the vendor dir and doesn't cause any other issues then ok.

**Comment by rawlingsj** [comment]
Will the `make bootstrap` target need to change?

**Comment by sanketjpatel** [comment]
I'll work on this on a separate branch. Closing this PR
Thanks James

**Comment by rawlingsj** [comment]
OK sounds good.  Shout if there's anything we can do to help.

**Pull request closed without merging**
