### PR TITLE
feat: add method code for UpdatePullRequest + tests + correct previously un…

### PR DESCRIPTION
**Pull request by orbsfoc**
#### Submitter checklist

- [x ] Change is code complete and matches issue description.
- [x ] Change is covered by existing or new tests.

#### Description
An update required to progress assimilation of the updatebot functionality. Adds UpdatePullRequest method to gitlab + unit tests

#### Special notes for the reviewer(s)
Also includes a fix for an undefined variable previously in the tests

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by jstrachan** [comment]
@orbsfoc ah looks like a rebase is needed

**Comment by orbsfoc** [comment]
Can i run the lint testing locally?

**Comment by hferentschik** [comment]
> Can i run the lint testing locally?

```
$ make lint
```

**Comment by hferentschik** [comment]
@orbsfoc  is not passing the Semantic Pull Request checks. I recommend you squash your commits into a single commit, use a commit message in the [conventional commit format ](https://www.conventionalcommits.org/en/v1.0.0-beta.4/) and do a force pushed to this PR.

**Comment by hferentschik** [comment]
See also https://jenkins-x.io/contribute/development/#the-commit-message and https://jenkins-x.io/contribute/development/#contribution-workflow

**Comment by orbsfoc** [comment]
Does the last pending mean fail too?

**Pull request merged**
