### PR TITLE
Issue #3205 - Add ability to determine whether a given flag was explicitly set

### LINKED ISSUE #3205: Creating GKE Cluster Ignores `--preemptible=false` flag
### Summary 
When creating a cluster with `jx create cluster gke —-prow=false --verbose --zone='us-east1-b' --preemptible=false --min-num-nodes='3' --max-num-nodes='5' --project-id='ckcd-sa-demo' --machine-type='n1-standard-4'` you are still asked if you want to use preemptible VMs or not
### Steps to reproduce the behavior
Run the following command:  `jx create cluster gke —-prow=false --verbose --zone='us-east1-b' --preemptible=false --min-num-nodes='3' --max-num-nodes='5' --project-id='ckcd-sa-demo' --machine-type='n1-standard-4'`
### Expected behavior
You shouldn't be prompted to use preemptible VMs or not.
### Actual behavior
You are still prompted.
### Jx version
1.3.925
The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.925
jenkins x platform 0.0.3402
Kubernetes cluster v1.11.7-gke.4
kubectl            v1.13.2
helm client        v2.12.3+geecf22f
helm server        v2.12.3+geecf22f
git                git version 2.9.2
Operating System   Mac OS X 10.14.2 build 18C54
```

### Kubernetes cluster
GKE

### Operating system / Environment
Mac OS X

### PR DESCRIPTION
**Pull request by hferentschik**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #3205

### CODE REVIEW

**Comment by hferentschik** [comment]
Hi @garethjevans, @ccojocar - have a look at this. Check out the behaviour for the  `enhanced-scopes` and `enhanced-apis` as well. I think this is how it should be, but maybe there are other intentions at play. Regarding `preemptible` it's definitely the behaviour we want. 

I pushed `IsFlagExplicitlySet` all the way down to `CommonOptions`, since I have a feeling it might be needed/useful in other commands as well.

**Comment by rawlingsj** [comment]
until we get the logrus PR merged
/hold

**Comment by hferentschik** [comment]
@rawlingsj 

> until we get the logrus PR merged

LOL, so it is easier for me to rebase? ;-) BTW, did you see [my comment](https://github.com/jenkins-x/jx/pull/3618#pullrequestreview-226058192) on your pull request. I'd personally go a step further than just replacing _fmt_ with _logrus_ and introduce a single point of entry for all of our logging.

**Comment by rawlingsj** [comment]
> LOL, so it is easier for me to rebase? ;-) BTW, did you see my comment on your pull request. I'd personally go a step further than just replacing fmt with logrus and introduce a single point of entry for all of our logging. 

Yeah I did and replied, will see if I have time but we need that PR for our monitoring and alerting so don't want to hold up other PRs too long.  We try to take the approach of creating followup PRs as much as possible so we keep moving forward, I'll try that now but I've only an hour left this afternoon before needing to head off.  Will see what I can do.  But you will only need to rebase if you have merge conflicts and the pipeline does a git merge with HEAD anyways before merging PRs so you should be fine.

**Comment by hferentschik** [comment]
rebased

**Pull request merged**
