### PR TITLE
docs: Version Stream documentation links

### PR DESCRIPTION
**Pull request by hajowieland**
#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [X] Change is covered by existing or new tests.

#### Description

Fix the links shown in the jx binary output for Jenkins-X Version Stream documentation.

### CODE REVIEW

**Comment by hferentschik** [comment]
@hajowieland, thanks for the pull request. Much appreciated.

The change looks good, but could you adjust the commit message using the conventional commit format? We are enforcing this format since we use the commit message metadata to create changelogs.

See also https://jenkins-x.io/docs/contributing/code/#the-commit-message

**Comment by hajowieland** [comment]
@hferentschik , thanks for taking the time to inform me about this issue.
I updated the commit message format to use conventional commit.

**Pull request merged**
