### PR TITLE
test(git provider): add tests for git providers creation from URL

### PR DESCRIPTION
**Pull request by ccojocar**

### CODE REVIEW

**Comment by rawlingsj** [comment]
ok this is building now

**Comment by ccojocar** [comment]
@rawlingsj Thanks! The tests seem to failed because of the secret masking:
```
expected: auth.UserAuth{Username:"test", ApiToken:"test", BearerToken:"", Password:""} actual : auth.UserAuth{Username:"****", ApiToken:"****", BearerToken:"", Password:""}
```
Any idea how can I disable it during tests?

**Comment by rawlingsj** [comment]
> Thanks! The tests seem to failed because of the secret masking:
Any idea how can I disable it during tests?

Ah I see, hmm I'm afraid I dont, @jtnord might have an idea?

**Pull request merged**
