### PR TITLE
chore: migrate code.gitea.io/sdk/gitea to v0.12.0

### PR DESCRIPTION
**Pull request by 6543**
migrate to new version & use new features

https://gitea.com/gitea/go-sdk/src/branch/master/docs/migrate-v0.11-to-v0.12.md

### CODE REVIEW

**Comment by hferentschik** [comment]
@6543, thanks for the PR, much appreciated. You will need to sign-off the commit in order to pass the DCO check. See  https://jenkins-x.io/community/code/#signoff.

**Comment by hferentschik** [comment]
Could you also squash the commits and use the conventional commit message format? We are enforcing this format since we use the commit message to, amongst other things,  create changelogs - see https://jenkins-x.io/community/code/#the-commit-message

**Comment by hferentschik** [comment]
```
Showing logs for build jenkins-x-jx-pr-7224-integratio-jf8tn-1 stage ci and container step-build
CGO_ENABLED=0 GO111MODULE=on go build -ldflags " -X github.com/jenkins-x/**/v2/pkg/version.Version=0.0.0-SNAPSHOT-PR-7224-1 -X github.com/jenkins-x/**/v2/pkg/version.Revision='c15b189a9' -X github.com/jenkins-x/**/v2/pkg/version.Branch='master' -X github.com/jenkins-x/**/v2/pkg/version.BuildDate='20200525-07:32:56' -X github.com/jenkins-x/**/v2/pkg/version.GoVersion='1.13.8' """ -p 2 -o build/** cmd/**/**.go
go: code.gitea.io/sdk/gitea@v0.12.0: reading http://jenkins-x-athens-proxy:80/code.gitea.io/sdk/gitea/@v/v0.12.0.mod: 404 Not Found
make: *** [build] Error 1
```

Seems to be an issue downloading the dependency atm.

**Comment by 6543** [comment]
@hferentschik all done and yes gitea.com had some downtime

it woudl be nice you send me the log of the CI error

**Comment by hferentschik** [comment]
Could you also please run `make generate` and check-in any changes?

**Comment by 6543** [comment]
@hferentschik `make generate` did strange things ☝️

**Comment by 6543** [comment]
I'll test if this make CI happy if not, I'll revert it

**Comment by 6543** [comment]
@hferentschik make generate do strange things, I think I'll need some help on your side since I'm not familiar with this project :/

**Comment by abayer** [comment]
Here's the codegen error:

```
--- a/go.sum
+++ b/go.sum
@@ -82,6 +82,10 @@ github.com/alcortesm/tgz v0.0.0-20161220082320-9c5fe88206d7 h1:uSoVVbwJiQipAclBb
 github.com/alcortesm/tgz v0.0.0-20161220082320-9c5fe88206d7/go.mod h1:6zEj6s6u/ghQa61ZWa/C2Aw3RkjiTBOix7dkqa1VLIs=
 github.com/alecthomas/jsonschema v0.0.0-20190504002508-159cbd5dba26 h1:b/CA15BzZIj8xNKnBxUwUmXt3USfJjb4Gl9eJIfMLtE=
 github.com/alecthomas/jsonschema v0.0.0-20190504002508-159cbd5dba26/go.mod h1:qpebaTNSsyUn5rPSJMsfqEtDw71TTggXM6stUDI16HA=
+github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751 h1:JYp7IbQjafoB+tBA3gMyHYHrpOtNuDiK/uB5uXxq5wM=
+github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751/go.mod h1:LOuyumcjzFXgccqObfd/Ljyb9UuFJ6TxHnclSeseNhc=
+github.com/alecthomas/units v0.0.0-20190924025748-f65c72e2690d h1:UQZhZ2O0vMHr2cI+DC1Mbh0TJxzA3RcLoMsFw+aXw7E=
+github.com/alecthomas/units v0.0.0-20190924025748-f65c72e2690d/go.mod h1:rBZYJk541a8SKzHPHnH3zbiI+7dagKZ0cgpgrD7Fyho=
 github.com/alexflint/go-filemutex v0.0.0-20171028004239-d358565f3c3f h1:tbgFqBK8r77y+mT2RKkQ8ukhk/uvPtPZvr3a3166YNw=
 github.com/alexflint/go-filemutex v0.0.0-20171028004239-d358565f3c3f/go.mod h1:CgnQgUtFrFz9mxFNtED3jI5tLDjKlOM+oUF/sTk6ps0=
 github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190308093441-53f19b3c6bee h1:KBt+NX/vLd/MHWUVwqCnPg8M1qRy0ceVF9u7qCwIPJ0=
@@ -1024,6 +1028,8 @@ google.golang.org/grpc v1.23.1/go.mod h1:Y5yQAOtifL1yxbo5wqy6BxZv8vAUGQwXBOALyac
 gopkg.in/AlecAivazis/survey.v1 v1.8.3 h1:uf8V0NkfqJkwWF9mWziv/xkpVc31xgwftG7mXU7udHk=
 gopkg.in/AlecAivazis/survey.v1 v1.8.3/go.mod h1:iBNOmqKz/NUbZx3bA+4hAGLRC7fSK7tgtVDT4tB22XA=
 gopkg.in/airbrake/gobrake.v2 v2.0.9/go.mod h1:/h5ZAUhDkGaJfjzjKLSjv6zCL6O0LLBxU4K+aSYdM/U=
+gopkg.in/alecthomas/kingpin.v2 v2.2.6 h1:jMFz6MfLP0/4fUyZle81rXUoxOBFi19VUFKVDOQfozc=
+gopkg.in/alecthomas/kingpin.v2 v2.2.6/go.mod h1:FMv+mEhP44yOT+4EoQTLFTRgOQ1FBLkstjWtayDeSgw=
 gopkg.in/cenkalti/backoff.v1 v1.1.0 h1:Arh75ttbsvlpVA7WtVpH4u9h6Zl46xuptxqLxPiSo4Y=
 gopkg.in/cenkalti/backoff.v1 v1.1.0/go.mod h1:J6Vskwqd+OMVJl8C33mmtxTBs2gyzfv7UDAkHu8BrjI=
 gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405/go.mod h1:Co6ibVJAznAaIkqp8huTwlJQCZ016jof/cbN4VW5Yz0=
make: *** [Makefile.codegen:85: verify-generation-complete] Error 1
```

**Comment by hferentschik** [comment]
Seems to be `go.sum` which is the issue. Have you checked in all changes to that file?

```
 	github.com/alecthomas/jsonschema v0.0.0-20190504002508-159cbd5dba26
+	github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751 // indirect
+	github.com/alecthomas/units v0.0.0-20190924025748-f65c72e2690d // indirect
 	github.com/alexflint/go-filemutex v0.0.0-20171028004239-d358565f3c3f
 	github.com/andygrunwald/go-gerrit v0.0.0-20181026193842-43cfd7a94eb4
 	github.com/andygrunwald/go-jira v1.5.0
@@ -122,6 +124,7 @@ require (
 	golang.org/x/sys v0.0.0-20200323222414-85ca7c5b95cd
 	golang.org/x/tools v0.0.0-20200415034506-5d8e1897c761
 	gopkg.in/AlecAivazis/survey.v1 v1.8.3
+	gopkg.in/alecthomas/kingpin.v2 v2.2.6 // indirect
 	gopkg.in/src-d/go-git.v4 v4.13.1
 	gopkg.in/yaml.v2 v2.2.8
 	k8s.io/api v0.0.0-20190718183219-b59d8169aab5
diff --git a/go.sum b/go.sum
index ffbe091f3..06cf37e81 100644
--- a/go.sum
+++ b/go.sum
@@ -82,6 +82,10 @@ github.com/alcortesm/tgz v0.0.0-20161220082320-9c5fe88206d7 h1:uSoVVbwJiQipAclBb
 github.com/alcortesm/tgz v0.0.0-20161220082320-9c5fe88206d7/go.mod h1:6zEj6s6u/ghQa61ZWa/C2Aw3RkjiTBOix7dkqa1VLIs=
 github.com/alecthomas/jsonschema v0.0.0-20190504002508-159cbd5dba26 h1:b/CA15BzZIj8xNKnBxUwUmXt3USfJjb4Gl9eJIfMLtE=
 github.com/alecthomas/jsonschema v0.0.0-20190504002508-159cbd5dba26/go.mod h1:qpebaTNSsyUn5rPSJMsfqEtDw71TTggXM6stUDI16HA=
+github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751 h1:JYp7IbQjafoB+tBA3gMyHYHrpOtNuDiK/uB5uXxq5wM=
+github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751/go.mod h1:LOuyumcjzFXgccqObfd/Ljyb9UuFJ6TxHnclSeseNhc=
+github.com/alecthomas/units v0.0.0-20190924025748-f65c72e2690d h1:UQZhZ2O0vMHr2cI+DC1Mbh0TJxzA3RcLoMsFw+aXw7E=
+github.com/alecthomas/units v0.0.0-20190924025748-f65c72e2690d/go.mod h1:rBZYJk541a8SKzHPHnH3zbiI+7dagKZ0cgpgrD7Fyho=
 github.com/alexflint/go-filemutex v0.0.0-20171028004239-d358565f3c3f h1:tbgFqBK8r77y+mT2RKkQ8ukhk/uvPtPZvr3a3166YNw=
 github.com/alexflint/go-filemutex v0.0.0-20171028004239-d358565f3c3f/go.mod h1:CgnQgUtFrFz9mxFNtED3jI5tLDjKlOM+oUF/sTk6ps0=
 github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190308093441-53f19b3c6bee h1:KBt+NX/vLd/MHWUVwqCnPg8M1qRy0ceVF9u7qCwIPJ0=
@@ -1024,6 +1028,8 @@ google.golang.org/grpc v1.23.1/go.mod h1:Y5yQAOtifL1yxbo5wqy6BxZv8vAUGQwXBOALyac
 gopkg.in/AlecAivazis/survey.v1 v1.8.3 h1:uf8V0NkfqJkwWF9mWziv/xkpVc31xgwftG7mXU7udHk=
 gopkg.in/AlecAivazis/survey.v1 v1.8.3/go.mod h1:iBNOmqKz/NUbZx3bA+4hAGLRC7fSK7tgtVDT4tB22XA=
 gopkg.in/airbrake/gobrake.v2 v2.0.9/go.mod h1:/h5ZAUhDkGaJfjzjKLSjv6zCL6O0LLBxU4K+aSYdM/U=
+gopkg.in/alecthomas/kingpin.v2 v2.2.6 h1:jMFz6MfLP0/4fUyZle81rXUoxOBFi19VUFKVDOQfozc=
+gopkg.in/alecthomas/kingpin.v2 v2.2.6/go.mod h1:FMv+mEhP44yOT+4EoQTLFTRgOQ1FBLkstjWtayDeSgw=
 gopkg.in/cenkalti/backoff.v1 v1.1.0 h1:Arh75ttbsvlpVA7WtVpH4u9h6Zl46xuptxqLxPiSo4Y=
 gopkg.in/cenkalti/backoff.v1 v1.1.0/go.mod h1:J6Vskwqd+OMVJl8C33mmtxTBs2gyzfv7UDAkHu8BrjI=
 gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405/go.mod h1:Co6ibVJAznAaIkqp8huTwlJQCZ016jof/cbN4VW5Yz0=
make: *** [Makefile.codegen:85: verify-generation-complete] Error 1
FAILED make verify-generation-complete
```

Seems when you run `make generate`. `go.

**Comment by hferentschik** [comment]
> ake generate do strange things, I think I'll need some help on your side since I'm not familiar with this project 

let me check ...

**Comment by hferentschik** [comment]
Ok, as said, `go.sum` and `go.mod` seem to be missing some things. I tried to push to your branch, but it seems you don't have the option enabled to let me do that. I will create a new PR instead. If it works, we can close this pull request in favour of the new one.

**Comment by hferentschik** [comment]
So here we go #7246

**Comment by hferentschik** [comment]
btw, could you also open an issue for this upgrade and reference it in the commit message and/or the pull request message?

**Comment by 6543** [comment]
sure

**Pull request closed without merging**
