### PR TITLE
Minikube: Prompt for VM driver should not be invoked if driver option has been used

### PR DESCRIPTION
**Pull request by hekonsek**
When creating Minikube cluster prompt for VM driver should not be invoked if driver option has been used. 

Basically if I execute `jx create cluster minikube --vm-driver=kvm2` I don't want jx to prompt me again for VM driver, but with `kvm2` selected as default. I just want jx to use `kvm2` instead.

### CODE REVIEW

**Comment by jstrachan** [comment]
@hekonsek many thanks! fancy doing a rebase and push?

**Comment by hekonsek** [comment]
Sure, I've just resolved the conflict.

**Comment by rawlingsj** [comment]
We're not able to open the CI for read only access yet so for now cross posting failure:

```
pkg/jx/cmd/create_cluster_minikube.go:227:2: undefined: err
pkg/jx/cmd/create_cluster_minikube.go:228:5: undefined: err
pkg/jx/cmd/create_cluster_minikube.go:229:10: undefined: err
pkg/jx/cmd/create_cluster_minikube.go:234:2: undefined: err
pkg/jx/cmd/create_cluster_minikube.go:238:5: undefined: err
pkg/jx/cmd/create_cluster_minikube.go:239:10: undefined: err
```

**Comment by hekonsek** [comment]
Ahhh, I was trying to use this fancy GitHib on line conflict resolver :P I will do it in IDE this time and push again ;)

**Comment by rawlingsj** [comment]
ok thanks :)

**Comment by hekonsek** [comment]
OK, ready to roll :) .

**Comment by rawlingsj** [comment]
thanks!

**Pull request merged**
