### PR TITLE
feat: generate a dependency matrix

### PR DESCRIPTION
**Pull request by pmuir**
#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description
Also adds a component matrix for dependencies. The new updatebot will generate this for you in your downstream repo.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by abayer** [comment]
Would it be rude for me to ask what exactly this is adding and/or how to take advantage of it? =)

**Comment by pmuir** [comment]
Yes - this needs some docs once it's all done ;-)

Basically - this is the updatebot improvement work - so when you use updatebot in the future it will generate this matrix for you.

**Pull request merged**
