### PR TITLE
fix: jx import creates Jenkins git credentials with ID

### PR DESCRIPTION
**Pull request by wbrefvem**
see #622 

@jstrachan not sure if this is what you had in mind for 622 so I left it open, but I think this fixes it.

### CODE REVIEW

**Comment by jstrachan** [comment]
Thanks! 

I was thinking of actually querying all the available pipeline Secrets of kind `git` and find the one for the same git server URL - if one is not found then prompt the user to add one. 

Lemme take a stab at this one as I know the secret loading code pretty well...

**Comment by wbrefvem** [comment]
Sure thing. Wasn't totally sure I understood what you were getting at, so I'm interested to see how you approach this.

**Comment by jstrachan** [comment]
@wbrefvem still polishing, but a heads up: https://github.com/jstrachan/jx/blob/malarkey/pkg/jx/cmd/common_import.go#L60-L62

which then calls:
https://github.com/jstrachan/jx/blob/malarkey/pkg/jx/cmd/common_import.go#L196-L212

This branch also works if you try something like:
```
jx import --url https://some-new-repo.com/foo/bar.got
```
where the user has never called `jx create git server ....` for `some-new-repo.com` and so incrementally sets up the server, auth + credentials on the fly

**Comment by wbrefvem** [comment]
@jstrachan that makes a lot more sense. IIUC, you're using k8s as a store for secrets not necessarily used by k8s, right?

**Comment by jstrachan** [comment]
yeah; we use this plugin: https://github.com/jenkinsci/kubernetes-credentials-provider-plugin so that we can use `Secrets` to manage the available `Credentials` in Jenkins; which means we can use GitOps / Helm to manage them etc.

Then the advantage of a `Secret` is we can add extra labels and annotations to it. e.g to indicate a `Secret/Credential` is for git and if so what git kind, server name and server URL is it for

**Comment by wbrefvem** [comment]
Okay, I think I grok this now. Thanks for the help!

**Pull request closed without merging**
