### PR TITLE
fix: test application deletion on static Jenkins

### PR DESCRIPTION
**Pull request by fiunchinho**
#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [X] Change is covered by existing or new tests.

#### Description
Deleting an application using jx delete application was broken when using static jenkins.

#### Special notes for the reviewer(s)
We didn't realize about this issue because deleting the app is disabled in the bdd tests.

### CODE REVIEW

**Comment by pmuir** [comment]
Apart from the module changes, lgtm

**Comment by abayer** [comment]
/hold
Putting on hold so #4552 can land first.

**Pull request merged**
