### PR TITLE
feat: add the capability to configure exposer

### PR DESCRIPTION
**Pull request by jiangytcn**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

OpenShift can use `Route` to expose endpoints, the configmap for the exposer always set to the `Ingress` by `jx boot` before. With such parameter, we can configure exposer type.

#### Which issue this PR fixes

fixes #

Support:

https://github.com/jenkins-x-charts/jxboot-resources/pull/9

### CODE REVIEW

**Comment by jiangytcn** [comment]
hi @abayer @garethjevans  is this PR can be merged to support https://github.com/jenkins-x-charts/jxboot-resources/pull/9

**Comment by ccojocar** [comment]
@jiangytcn Please could you rebase this PR? Thanks!

**Comment by jiangytcn** [comment]
hi @ccojocar code rebased, can you approve the testing

**Pull request merged**
