### PR TITLE
refactor(cmd): moving step_create_task into package jx/cmd/step/create

### PR DESCRIPTION
**Pull request by hferentschik**
Moving StepOption into opts package to break the cyclic dependency

Once this merged most step commands should be able to move into dedicated packages.

### CODE REVIEW

**Comment by abayer** [comment]
/lgtm

Well, once the merge conflict is resolved. =)

**Comment by hferentschik** [comment]
rebased. @abayer you might need to add the lgtm label again

**Comment by abayer** [comment]
/lgtm

Yup, was waiting for just that. =)

**Pull request merged**
