### PR TITLE
fix: support multiple contexts

### PR DESCRIPTION
**Pull request by pmuir**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by abayer** [comment]
I think the test failure may be legit.

**Comment by abayer** [comment]
Holding briefly to avoid batching with #5170.

**Comment by abayer** [comment]
The other PR had a flaky test failure anyway, so hey, unholding.

**Comment by abayer** [comment]
This one failed too! I give up. =)

**Comment by abayer** [comment]
fwiw, in both cases, it was `TestStepSchedulerConfigMigrateNonGitopsAdvanced` that failed.

**Comment by abayer** [comment]
For giggles, since I'm not asleep yet, one more try.

**Comment by hferentschik** [comment]
What's the state on this PR? Tests seemed to have passed now? @pmuir @ccojocar @abayer

**Comment by hferentschik** [comment]
/test all

Triggering another test round.

**Comment by pmuir** [comment]
I talked to @daveconde  about this, I'll try to pick it back up soon.

**Pull request merged**
