### PR TITLE
chore(deps): bump cobra from 0.0.5 to 1.0.0

### PR DESCRIPTION
**Pull request by garethjevans**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by hferentschik** [comment]
@garethjevans ooi, is there anything particular you are hoping out of the upgrade?

**Comment by garethjevans** [comment]
@hferentschik mainly trying to be a good citizen.  We're using 1.0.0 elsewhere so it makes sense bump this version.  It does appear to have lots of fixes around code completion in the newer versions.

**Pull request merged**
