### PR TITLE
fix: Don't accidentally reuse PipelineStructures

### LINKED ISSUE #3370: `jx get build logs` not returning master branch pipelines anymore
jx 1.3.980

I just upgraded to the latest jx (unfortunately I don't know the version I was on before) and I'm now not seeing master branch pipelines returned in the list to choose.  I only see PR related pipelines.

Think it may be a regression?

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

Pointers are hard. For me, at least.

I still need to write a bunch of unit tests for `get_build_logs` one of these days.

#### Special notes for the reviewer(s)

/assign @rawlingsj 

#### Which issue this PR fixes

Fixes #3370

### CODE REVIEW

**Comment by rawlingsj** [comment]
popping on hold while we sort the release pipeline
BTW tested and the fix totally works - thanks @abayer!
/lgtm
/hold

**Comment by abayer** [comment]
@rawlingsj - should this still be on hold?

**Comment by rawlingsj** [comment]
> should this still be on hold?

@abayer yeah we have an issue that the jx version wasn't being updated in the downstream builder images so I was holding PRs until that's fixed.  @garethjevans is helping out with a fix to updatebot that updates the dockerfiles correctly after I moved some about to help with image caching.  Hopefully we'll catch up in the morning and at worst merge more urgent PRs like this and manually update the downstream repo.

**Comment by abayer** [comment]
@rawlingsj Gotcha - just wasn't sure what the status was. =)

**Pull request merged**
