### PR TITLE
feat: have preview environments open in new tab

### PR DESCRIPTION
**Pull request by MarckK**
Signed-off-by: Kara de la Marck <MarckK@users.noreply.github.com>

### CODE REVIEW

**Comment by ankitm123** [comment]
would be nice to have an issue linked to this PR.

**Comment by MarckK** [comment]
Closes #7496

**Comment by MarckK** [comment]
<a href="https://jenkins-x.io/" target="_blank">here</a>

**Comment by MarckK** [comment]
Sadly, GitHub seems to be changing the html, removing target="_blank" and adding rel="nofollow".

Closing for now.

**Pull request closed without merging**
