### PR TITLE
Allow to checkout a different branch while running bdd tests

### PR DESCRIPTION
**Pull request by fiunchinho**
#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description
The jx step bdd command currently allow us to run bdd tests for jenkins-x, but we could use it to run tests for applications that require a running jx platform.

With these changes you can specify not only a different git repository to checkout, but a specific branch. That way you can checkout changes that are pending to be merge and test if they work.

### CODE REVIEW

**Comment by rawlingsj** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/jenkins-x/jx/pull/2722#issuecomment-455177255" title="LGTM">jstrachan</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/jenkins-x/jx/blob/master/OWNERS)~~ [jstrachan]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ccojocar** [comment]
Is this related to this bug https://github.com/jenkins-x/jx/issues/2433?

**Comment by fiunchinho** [comment]
Yeah, this fixes https://github.com/jenkins-x/jx/issues/2433

**Comment by fiunchinho** [comment]
It seems tide is ignoring this PR?

**Comment by pmuir** [comment]
Yes. There is a problem right now. I'm trying to get it fixed.

**Pull request merged**
