### PR TITLE
WIP test: use bdd jx branch to run ui smoke tests

### PR DESCRIPTION
**Pull request by romainverduci**

### CODE REVIEW

**Comment by hferentschik** [comment]
Thanks for the PR. You will need to sign-off the commit in order to pass the DCO check. 

See:

- https://github.com/jenkins-x/jx/pull/<pr>/checks
- https://jenkins-x.io/docs/contributing/code/#signoff

**Comment by romainverduci** [comment]
> Thanks for the PR. You will need to sign-off the commit in order to pass the DCO check.
> 
> See:
> 
> * https://github.com/jenkins-x/jx/pull//checks
> * https://jenkins-x.io/docs/contributing/code/#signoff

I will close this PR once https://github.com/jenkins-x/bdd-jx/pull/87 is merged.
This was just to allow testing with a branch of `bdd-jx`

**Comment by romainverduci** [comment]
Closing as this was just to validate new tests

**Comment by abayer** [comment]
yay!

**Pull request closed without merging**
