### PR TITLE
fix: Prevent concurrent environment deploys

### LINKED ISSUE #5281: All resources deleted from permanent environment
### Summary 

When running a remote environment set up according to https://jenkins-x.io/getting-started/multi-cluster/ a race condition exists that means all applications in the environment can be deleted.

### Steps to reproduce the behavior

1. Setup remote cluster according to https://jenkins-x.io/getting-started/multi-cluster/
2. Promote 2 applications  to environment in remote cluster at the same time

### Expected behavior

Any changes are deployed

### Actual behavior

All resources managed by the environment repo except pvc, configmaps and secrets got deleted.

### Analysis

The step build-step-build-helm-apply in the second pipeline run that got started had applied it's changes just before the first pipeline runs build-step-build-helm-apply had come to "Removing Kubernetes resources from older releases using selector". So all resources from environment-sto-staging where deleted since they had gotten the version of the second pipeline run and thus mached the selector that was intended to fins old resources.

When using jenkins to deploy an environment the Jenkinsfile by default includes 

```
    options {
        disableConcurrentBuilds()
    }
```

preventing a race condition to occur. This is missing from the mechanism set up with the environment controller.

It might be relevant that the environment is configured to use helm template and not tiller.

### Jx version

Environment controller use the image gcr.io/jenkinsxio/builder-maven:0.1.549

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.643
Kubernetes cluster v1.13.8-eks-a977ba
kubectl            v1.14.1
helm client        Client: v2.14.1+g5270352
git                2.16.2
Operating System   Mac OS X 10.14.6 build 18G95
```

### PR DESCRIPTION
**Pull request by msvticket**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

When deploying environment with jenkins concurrent execution of pipelines are disabled with disableConcurrentBuilds in Jenkinsfile. Nothing like that is available in Tekton and thus some other way of preventing dangerous race conditions is needed.

#### Which issue this PR fixes

fixes #5281

### CODE REVIEW

**Comment by abayer** [comment]
The `lint` build is failing with this error:
```
diff --git a/pkg/cmd/step/create/step_create_task.go b/pkg/cmd/step/create/step_create_task.go
index 4d23cd47b..8de5c276f 100644
--- a/pkg/cmd/step/create/step_create_task.go
+++ b/pkg/cmd/step/create/step_create_task.go
@@ -72,7 +72,7 @@ var (

 	createTaskOutDir  string
 	createTaskNoApply bool
-	pipelineLock sync.Mutex
+	pipelineLock      sync.Mutex
 )

 // StepCreateTaskOptions contains the command line flags
@@ -365,7 +365,7 @@ func (o *StepCreateTaskOptions) Run() error {
 		if o.DisableConcurrent {
 			// Ensure
 			pipelineLock.Lock()
-			o.waitForPreviousPipeline(tektonClient, ns, 100 * time.Second)
+			o.waitForPreviousPipeline(tektonClient, ns, 100*time.Second)
 		}
 		log.Logger().Infof("Applying changes ")
 		err := tekton.ApplyPipeline(jxClient, tektonClient, tektonCRDs, ns, activityKey)
@@ -409,13 +409,13 @@ func (o *StepCreateTaskOptions) waitForPreviousPipeline(tektonClient tektonclien
 							update := <-pipelineWatch.ResultChan()
 							if update.Type == watch.Deleted {
 								pipelineWatch.Stop()
-								break;
+								break
 							}
 							if update.Type == watch.Modified {
 								pr = update.Object.(*pipelineapi.PipelineRun)
 								if pr.Status.CompletionTime != nil {
 									pipelineWatch.Stop()
-									break;
+									break
 								}
 							}
 						}
@@ -426,7 +426,7 @@ func (o *StepCreateTaskOptions) waitForPreviousPipeline(tektonClient tektonclien
 		}
 	}
 	// When waiting to wait for previous pipeline run just wait for 100 seconds
-	if ! pipelineWait {
+	if !pipelineWait {
 		log.Logger().Infof("Can't access previous pipeline. Waiting %v to ensure it finishes", defaultWait)
 		time.Sleep(defaultWait)
 	}
make: *** [verify-generation-complete] Error 1
Makefile.codegen:62: recipe for target 'verify-generation-complete' failed
FAILED make verify-generation-complete
```

Looks like you need to run `gofmt`. =)

**Comment by msvticket** [comment]
When following the tekton test link I get "
Internal Server Error

Failed to authenticate: github: user "msvticket" not in required orgs or teams
"
Could you give me permission to check the tests myself? It's not like this will be my last PR...

**Pull request merged**
