### PR TITLE
Disable OpenAPI generation for CommitStatus to avoid validation failing

### PR DESCRIPTION
**Pull request by davidcurrie**
Signed-off-by: David Currie <dcurrie@cloudbees.com>

#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

Disable validation of `CommitStatus` as workaround for #2995 pending upstream fix of https://github.com/kubernetes/kubernetes/issues/68466 (Root cause has now been addressed in https://github.com/go-openapi/validate/pull/106 so just waiting for this to be picked up by kube.)

### CODE REVIEW

**Comment by abayer** [comment]
/lgtm

But has a merge conflict. =)

**Comment by pmuir** [comment]
Can you rebase?

**Comment by rawlingsj** [comment]
until we get the logrus PR merged
/hold

**Comment by rawlingsj** [comment]
still needs a rebase but let's remove the hold now that big PRs have been merged
/hold cancel

**Comment by hferentschik** [comment]
Is this still an issue? Should we rebase?

**Comment by hferentschik** [comment]
@davidcurrie ^^

**Comment by ccojocar** [comment]
@davidcurrie @hferentschik I think we should close this on.

**Comment by hferentschik** [comment]
@ccojocar +1

**Comment by ccojocar** [comment]
@davidcurrie I am closing this PR. Feel free to open another PR if you still need this fix.

**Comment by davidcurrie** [comment]
Sorry - something screwy being going on with my GitHub notifications. I believe this is still a problem but not one that is impacting me at the moment so not motivated to provide an updated fix.

**Pull request closed without merging**
