### PR TITLE
chore: Move tekton and bdd baseline coverage into separate pipelines

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

They'll get kicked off by Prow directly as part of postsubmit - see https://github.com/jenkins-x/prow-config-tekton/pull/109

#### Special notes for the reviewer(s)

/assign @pmuir 

#### Which issue this PR fixes

n/a

### CODE REVIEW

**Comment by hferentschik** [comment]
@abayer - this one needs a rebase now

**Comment by abayer** [comment]
@hferentschik done!

**Pull request merged**
