### PR TITLE
feat(install): getting the GtiOps mode with vault fully running for classic Jenkins

### PR DESCRIPTION
**Pull request by ccojocar**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by jstrachan** [comment]
/lgtm

great stuff!!!

**Comment by ccojocar** [comment]
@jstrachan Thanks for review! I hope tomorrow to have the BDD also passing at least `create spring` test.

**Pull request merged**
