### PR TITLE
chore: Use jx versions repository configuration when running the bdd tests

### LINKED ISSUE #4440: jx repo BDD tests on jenkins should use tillerless
right now they are using tiller which isn't our default

### PR DESCRIPTION
**Pull request by fiunchinho**
#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [X] Change is covered by existing or new tests.

#### Description
Use the configuration we have in the jenkins-x-versions repository to run the bdd tests. We will use a `--no-tiller` cluster for testing our code, which is the default option.

#### Special notes for the reviewer(s)
IIUC this will create a new cluster when running the bdd context/job, using static jenkins.

#### Which issue this PR fixes

fixes #4440

### CODE REVIEW

**Comment by abayer** [comment]
Looks reasonable - are we sure the `jx/scripts/*.sh` files that get deleted aren't used anywhere else?

**Comment by hferentschik** [comment]
@fiunchinho  what's the state on this PR? Are you planning to rebase and continue working on it? Or should we close it for now?

**Comment by ccojocar** [comment]
@fiunchinho @pmuir @hferentschik I am going to close this. It doesn't seems to be any active work ongoing to get it merged since quite a while. Thanks

**Pull request closed without merging**
