### PR TITLE
test: mock the resources used by the namespace test to allow running the unit tests without a cluster connection

### PR DESCRIPTION
**Pull request by ccojocar**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by abayer** [comment]
Lint failure is fixed in https://github.com/jenkins-x/jx/pull/5150

**Comment by ccojocar** [comment]
> Lint failure is fixed in #5150

I also fixed in the PR.

**Pull request merged**
