### PR TITLE
Upgraded AWS SDK version

### PR DESCRIPTION
**Pull request by hekonsek**
Upgraded AWS SDK version.

### CODE REVIEW

**Comment by rawlingsj** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/jenkins-x/jx/pull/2724#issuecomment-455177074" title="LGTM">jstrachan</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/jenkins-x/jx/blob/master/OWNERS)~~ [jstrachan]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rawlingsj** [comment]
@hekonsek: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
serverless-jenkins | 1f0d3a59546a049612041714afef2620e15a5c1f | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by hekonsek** [comment]
I've fixed AWS SDK checksum (it was go mod cache issue). Should be good now.

**Comment by hekonsek** [comment]
Is it false error by any chance? :)

**Comment by hekonsek** [comment]
Can we try to rerun tests and this one merged? Thanks!

**Comment by ccojocar** [comment]
@hekonsek Please could you rebase this, `go.mod` needs an update:

```
index 7eca882c3..0bb313ebc 100644
--- a/go.mod
+++ b/go.mod
@@ -18,6 +18,7 @@ require (
 	github.com/alexflint/go-filemutex v0.0.0-20171028004239-d358565f3c3f
 	github.com/andygrunwald/go-gerrit v0.0.0-20181026193842-43cfd7a94eb4
 	github.com/andygrunwald/go-jira v1.5.0
+	github.com/antham/chyle v1.4.0
 	github.com/aws/aws-sdk-go v1.16.20
 	github.com/banzaicloud/bank-vaults v0.0.0-20181129101211-e31657d7c4fe
 	github.com/beevik/etree v1.0.1
```

**Comment by hekonsek** [comment]
Rebase done.

**Comment by ccojocar** [comment]
@hekonsek I guess this PR needs again to be rebased. Sorry for this! Thanks

**Comment by ccojocar** [comment]
@hekonsek This PR looks a bit outdated. Any plans to work on it? Thanks

**Comment by ccojocar** [comment]
@hekonsek Any chance to rebase this PR? Thanks

**Comment by hekonsek** [comment]
Closing this PR on behalf of https://github.com/jenkins-x/jx/pull/3279. Can we try to get #3279 merged fast to avoid deps and checksum conflicts? :) This is just a dependency update.

**Pull request closed without merging**
