### PR TITLE
fix: don’t include data in error

### LINKED ISSUE #5258: parameters schema discloses secrets the logs when an error occurs
### Summary 

The parameters schema leaks passwords in the logs when updating the values in vault and an error occurs:

```
STEP: helm-populate-params command: /bin/sh -c jx step create values --name parameters in dir: env

defaulting to secret storage scheme vault found from requirements file at /workspace/source/bdd-config/jx-requirements.yml
defaulting to secret base path to the cluster name pr-48-33-bdd-boot-v found from requirements file at /workspace/source/bdd-config/jx-requirements.yml

Jenkins X Admin Username admin [Automatically accepted existing value]
defaulting value from $JX_VALUE_ADMINUSER_PASSWORD
Jenkins X Admin Password *** []
error: asking questions for schema: failed to write to vaultPath pr-48-33-bdd-boot-v/adminUser with data map[string]interface {}{"password":"password"}: Error making API request.
```

### Expected behavior

It should not disclose the secrets in the error messages. 

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### PR DESCRIPTION
**Pull request by pmuir**
Signed-off-by: Pete Muir <pmuir@bleepbleep.org.uk>

#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #5258

### CODE REVIEW

**Comment by ccojocar** [comment]
@pmuir Can you please remove also the generated token form boot logs? 
```
? Jenkins X Admin Username admin
? Jenkins X Admin Password [? for help] *****
? Pipeline bot Git username ccojocar
? Pipeline bot Git email address cosmin.cojocar@gmx.ch
? Pipeline bot Git token [? for help] ****************************************
Generated token fe4f.., to use it press enter.
This is the only time you will be shown it so remember to save it
? HMAC token, used to validate incoming webhooks. Press enter to use the generated token [? for help]
? Do you want to configure an external Docker Registry? No
```

I don't think, it needs to be displayed when vault is enabled.

**Comment by pmuir** [comment]
See https://github.com/jenkins-x/jx/issues/5100

**Pull request merged**
