### PR TITLE
chore: Add Tekton BDD to release coverage baseline generation

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

Followup to #4301. Also fixes a bad image name I put in. Sigh.

#### Special notes for the reviewer(s)

/assign @pmuir 
/assign @daveconde 
/assign @cagiti 

#### Which issue this PR fixes

n/a

### CODE REVIEW

**Comment by abayer** [comment]
/hold

Holding so #4529 can get merged without batch hell.

**Comment by rawlingsj** [comment]
> Holding so #4529 can get merged without batch hell.
:pray:

**Pull request merged**
