### PR TITLE
chore: revert the clone methods

### PR DESCRIPTION
**Pull request by pmuir**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by hferentschik** [comment]
@pmuir, was the intention to get this merged or did you just want to show what we potentially could do?

**Comment by pmuir** [comment]
Just to show potentially what we could do I think. I'm not 100% convinced this is safe. I'll try to do a local fix today.

**Comment by hferentschik** [comment]
>  I'm not 100% convinced this is safe.

Why not? What are your concerns? It looks definitely much simpler ;-)

**Comment by pmuir** [comment]
As we discussed this area is delicate and requires manual testing. Just because something is simple doesn't mean it's right.

**Pull request closed without merging**
