### PR TITLE
switch to gcs chartmuseum

### PR DESCRIPTION
**Pull request by i0n**

### CODE REVIEW

**Comment by ccojocar** [comment]
@i0n What is the state of this PR?

**Comment by i0n** [comment]
@ccojocar It's all working and good to go, but we can't merge until we merge:
https://github.com/jenkins-x/draft-packs/pull/58
https://github.com/jenkins-x/cloud-environments/pull/159

and then deploy HA chartmuseum infrastructure

**Comment by ccojocar** [comment]
@i0n I guess is failing for some reasons.

**Comment by rawlingsj** [comment]
@i0n sorry but I've not caught up properly, is this PR still needed or shall we defer until after JW?

**Comment by i0n** [comment]
Yeah, I think we can close this for now and revisit some time in the future.

**Comment by rawlingsj** [comment]
sound good :+1:

**Pull request closed without merging**
