### PR TITLE
Gitlab integration [WIP]

### PR DESCRIPTION
**Pull request by jlordiales**
This is a first wip of the gitlab integration. All methods are implemented but there's a lot of testing and error handling logic missing. Also haven't implemented pagination for list* operations.

Not sure what's your convention to add new dependencies, just did a `glide get github.com/xanzy/go-gitlab` here but the diff seems unnecessarily large.

### CODE REVIEW

**Comment by jstrachan** [comment]
@jlordiales thanks! yeah I usually just add the dependencies to the `glide.yaml` file and do `make bootstrap`. Usually quite a few things change mind you ;)

**Comment by jstrachan** [comment]
not sure if you can see the compile error there btw:
```
CGO_ENABLED=0 GO15VENDOREXPERIMENT=1 go build -ldflags " -X github.com/jenkins-x/jx/pkg/version.Version=1.0.1 -X github.com/jenkins-x/jx/pkg/version.Revision='b184812' -X github.com/jenkins-x/jx/pkg/version.Branch='HEAD' -X github.com/jenkins-x/jx/pkg/version.BuildDate='20180327-10:48:36' -X github.com/jenkins-x/jx/pkg/version.GoVersion='1.9.2'" -o build/jx cmd/jx/jx.go

vendor/github.com/Azure/draft/pkg/linguist/linguist.go:13:2: cannot find package "github.com/sirupsen/logrus" in any of:

	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/sirupsen/logrus (vendor tree)

	/usr/local/go/src/github.com/sirupsen/logrus (from $GOROOT)

	/home/jenkins/go/src/github.com/sirupsen/logrus (from $GOPATH)

make: *** [build] Error 1

```

**Comment by jlordiales** [comment]
Oh boy... I love Go but dependency management really sucks.

I'll take a look, thanks!

**Comment by jstrachan** [comment]
@jlordiales agreed! its the worst part of go really! painful!

**Comment by jstrachan** [comment]
BTW the CI build still gives: 
```

CGO_ENABLED=0 GO15VENDOREXPERIMENT=1 go build -ldflags " -X github.com/jenkins-x/jx/pkg/version.Version=1.0.1 -X github.com/jenkins-x/jx/pkg/version.Revision='6284038' -X github.com/jenkins-x/jx/pkg/version.Branch='HEAD' -X github.com/jenkins-x/jx/pkg/version.BuildDate='20180327-12:17:36' -X github.com/jenkins-x/jx/pkg/version.GoVersion='1.9.2'" -o build/jx cmd/jx/jx.go

vendor/github.com/Azure/draft/pkg/linguist/linguist.go:13:2: cannot find package "github.com/sirupsen/logrus" in any of:

	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/sirupsen/logrus (vendor tree)

	/usr/local/go/src/github.com/sirupsen/logrus (from $GOROOT)

	/home/jenkins/go/src/github.com/sirupsen/logrus (from $GOPATH)

make: *** [build] Error 1

script returned exit code 2
```
wonder if we need to add `github.com/sirupsen/logrus` to the `glide.yaml` file then re-run `make bootstrap`?

**Comment by jlordiales** [comment]
No luck... still failing for the same dep or something else now?

**Comment by wbrefvem** [comment]
@jlordiales I like the way you did the mocking for the tests. I've been looking for a way to do the same with Bitbucket, so I'm probably going to steal it. ;)

**Comment by jstrachan** [comment]
@jlordiales looks like a specific version of `github.com/sirupsen/logrus` is required:
```
+ make

CGO_ENABLED=0 GO15VENDOREXPERIMENT=1 go build -ldflags " -X github.com/jenkins-x/jx/pkg/version.Version=1.0.1 -X github.com/jenkins-x/jx/pkg/version.Revision='c6ec05a' -X github.com/jenkins-x/jx/pkg/version.Branch='HEAD' -X github.com/jenkins-x/jx/pkg/version.BuildDate='20180327-14:46:22' -X github.com/jenkins-x/jx/pkg/version.GoVersion='1.9.2'" -o build/jx cmd/jx/jx.go

# github.com/jenkins-x/jx/vendor/github.com/sirupsen/logrus

vendor/github.com/sirupsen/logrus/terminal_notwindows.go:20:14: undefined: Termios

vendor/github.com/sirupsen/logrus/terminal_notwindows.go:23:69: undefined: ioctlReadTermios

make: *** [build] Error 2

script returned exit code 2
```

**Comment by vietwow** [comment]
@jlordiales Is this feature for gitlab cloud or private (self-hosted) gitlab-ce ? Thanks

**Comment by michaelneale** [comment]
and it has tests, nice!

**Comment by jlordiales** [comment]
@wbrefvem to be fair I stole it from https://github.com/xanzy/go-gitlab/blob/master/gitlab_test.go (the github client uses a very similar approach https://github.com/google/go-github/blob/master/github/github_test.go)

@vietwow as far as I could see the API is the same so it should work for both.

**Comment by jlordiales** [comment]
Ok, I think I finally fixed the problem with `logrus`. FWIW, it was related to https://github.com/sirupsen/logrus/issues/570#issuecomment-313933276

**Comment by jstrachan** [comment]
@jlordiales great thanks!

**Pull request merged**
