### PR TITLE
Update README.md to add codescene reporting

### PR DESCRIPTION
**Pull request by michaelneale**
hey @ccojocar @rawlingsj found this near tool called "codescene" which gives all sorts of analysis around code health, hostspots and things that have a lot of churn or need refactoring. 

Thought it is worth a try (at the moment it looks at a few repos)

### CODE REVIEW

**Comment by michaelneale** [comment]
what it looks like: 

Screen Shot 2019-05-01 at 4 03 49 pm

**Comment by ccojocar** [comment]
It looks interesting! I like the hotsports. They seems to be relevant :). Does it integrate with the repositories as a GitHub application?

**Comment by michaelneale** [comment]
@ccojocar I think it might be an oauth app - not sure (can't seem to see where it went as an install app)

**Comment by michaelneale** [comment]
yes it is an oauth app (I approved it, I can see it there now)

**Pull request merged**
