### PR TITLE
fix(install): make sure that a domain is configured even when the skip-ingress option is active

### LINKED ISSUE #2571: skip-ingress flag not working
### Summary
During jx install on an existing empty cluster, using the flag "--skip-ingress" cause an issue and prevent the installation.

### Steps to reproduce the behavior

* create a GKE cluster ether manually or using gcloud SDK
* install JX
	`jx install \
		--default-environment-prefix playground \
		--skip-ingress \
		--environment-git-owner Interdiscount \
		--default-admin-password ***** \`
* the process is interrupted by an error (see screenshot below)
image

### Jx version
1.3.684

### Kubernetes cluster
GKE version 1.11.5-gke.5

### Operating system / Environment
MacOsX 10.14.2

### Expected behavior
The installation should end without issues and jx should not install any kubernetes ingress controller after the creation or import of a new application.

### Actual behavior
The installation of JX in an already existing empty cluster failed.

### PR DESCRIPTION
**Pull request by ccojocar**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #2571

### CODE REVIEW

**Comment by rawlingsj** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ccojocar**

If they are not already assigned, you can assign the PR to them by writing `/assign @ccojocar` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/jenkins-x/jx/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rawlingsj** [comment]
@ccojocar: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
serverless-jenkins | a63e39b259bac69c3f86b3e808c114d15200aca7 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by rawlingsj** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/jenkins-x/jx/pull/2727#issuecomment-455177944" title="LGTM">jstrachan</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/jenkins-x/jx/blob/master/OWNERS)~~ [jstrachan]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rawlingsj** [comment]
@ccojocar: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
serverless-jenkins | a63e39b259bac69c3f86b3e808c114d15200aca7 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by rawlingsj** [comment]
@ccojocar: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
serverless-jenkins | a63e39b259bac69c3f86b3e808c114d15200aca7 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ccojocar** [comment]
@jstrachan Please can you add a `lgmt` again? Thanks

**Pull request merged**
