### PR TITLE
feat: allow github app flag in requirements.yaml

### PR DESCRIPTION
**Pull request by warrenbailey**
Add flag in requirements file to enable and disable the use of the github app.

Signed-off-by: warrenbailey <warren@warrenbailey.net>

#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by hferentschik** [comment]
@warrenbailey what's the state of this PR?

**Comment by warrenbailey** [comment]
@hferentschik sorry got sidetrack on some other work. I'm picking this back up today.

**Comment by warrenbailey** [comment]
for some reason the boot test fail with a validation error:

error: Validation failures in YAML file **-requirements.yml:
(root): Additional property githubApp is not allowed

Investigating

**Comment by jstrachan** [comment]
@warrenbailey think you may need to run `make fmt` and commit to get the lint passing

**Comment by jstrachan** [comment]
replaced with this PR https://github.com/jenkins-x/jx/pull/5942

@warrenbailey I made the GitHubApp a pointer so its optional

**Pull request closed without merging**
