### PR TITLE
Unique Loop Name

### LINKED ISSUE #4228: Name is not supported in the loop
### Summary 

I have the following pipeline.

```yaml
buildPack: go
pipelineConfig:
  pipelines:
    pullRequest:
      build:
        preSteps:
        - loop:
            variable: ARCH
            values:
            - arch-1
            - arch-2
            - arch-3
            steps:
            - command: echo ${ARCH}
              name: my-loop
```

With that YAML, pipeline fails to run (tekton Pod is not even created). If I remove the `name` instruction it works correctly. `jx step syntax validate pipeline` claims that the syntax is correct.

### Steps to reproduce the behavior

Run the above-mentioned pipeline.

### Expected behavior

Pipeline run is started

### Actual behavior

Pipeline does not run

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.253
jenkins x platform 2.0.330
Kubernetes cluster v1.12.8-gke.6
kubectl            v1.14.3
helm client        Client: v2.14.1+g5270352
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.5 build 18F203
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [X] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE

### Operating system / Environment

macOS

### PR DESCRIPTION
**Pull request by warrenbailey**
If the step name is set in a loop then ensure its unique

#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

Fixes #4228

### CODE REVIEW

**Comment by abayer** [comment]
/lgtm
Nice catch!

**Comment by warrenbailey** [comment]
Thanks @abayer just added a unit test

**Pull request merged**
