### PR TITLE
chore: fixing punctuation's in README

### PR DESCRIPTION
**Pull request by sumitkharche**

### CODE REVIEW

**Comment by abayer** [comment]
Hi! Thanks for the PR - could you change the commit message and PR title to fit semantic standards? That means prefixing the message/title with `fix: `, `chore: `, or `feat: `.

**Comment by hferentschik** [comment]
@sumitkharche, thanks for the pull request. Looking basically ok. Do you mind updating your commit message though to follow [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0-beta.2/) format?

Something like: "chore(docs): fixing punctuation in README"

**Comment by sumitkharche** [comment]
@hferentschik I have updated the title

**Comment by hferentschik** [comment]
> I have updated the title

You updated the title of the pull request which is good, but it is really the git commit message which needs changing. You commit message is "Updated missing punctuation's ".

Usually, if you do your work on a feature branch, you would:

```bash
$ git rebase -i master
```

and then mark your commit as "reword" which then will pop up an editor to let you change the commit message. See also https://help.github.com/en/github/using-git/about-git-rebase

I think, however, you made the commit on the master branch, so in this case you will need to do something like:

```bash
$ git rebase -i HEAD~1
```

or

```bash
$ git reset HEAD~1
```

Either way, once you adjusted the commit message you will need to do a force push to this pull request in order to update it. Alternatively, you close this PR and create a new one from the updates commit.

Hope that helps.

**Comment by hferentschik** [comment]
See also https://jenkins-x.io/docs/contributing/code/#the-commit-message

**Comment by hferentschik** [comment]
@sumitkharche, any luck with updating the commit message?

**Comment by sumitkharche** [comment]
> @sumitkharche, any luck with updating the commit message?

@hferentschik Sorry for the late reply. I will create separete PR with correct commit title and PR heading.

**Comment by sumitkharche** [comment]
@hferentschik I have created new PR #5991

**Comment by sumitkharche** [comment]
> @hferentschik I have created new PR #5991 and closing this PR.

**Pull request closed without merging**
