### PR TITLE
fix: Use vault operator version from chart

### LINKED ISSUE #4988: jx upgrade addons downgrades vault-operator
### Summary 
Calling `jx upgrade addons` downgrades vault-operator from 0.4.16 to version 0.2.1, which is no longer available.

### Steps to reproduce the behavior
1. `jx create addon vault-operator`
```
$ kubectl get pod vault-operator-589647bfd4-rtkzc -o "jsonpath={$.spec.containers[0].image}"
banzaicloud/vault-operator:0.4.16
```
2. `jx upgrade addons`
```
$ kubectl get pod vault-operator-8477f4cf4b-sz7fc
NAME                              READY   STATUS             RESTARTS   AGE
vault-operator-8477f4cf4b-sz7fc   0/1     ImagePullBackOff   0          73m

$ kubectl get pod vault-operator-8477f4cf4b-sz7fc -o "jsonpath={$.spec.containers[0].image}"
banzaicloud/vault-operator:0.2.1
```

### Expected behavior

vault-operator should be upgraded

### Actual behavior

vault-operator downgraded to `banzaicloud/vault-operator:0.2.1`

### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 2.0.554
jenkins x platform 2.0.905
Kubernetes cluster v1.14.2
kubectl            v1.15.1
helm client        Client: v2.13.0+g79d0794
git                git version 2.22.0
Operating System   Mac OS X 10.14.6 build 18G84
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

[Banzai Cloud PKE](https://github.com/banzaicloud/pke) cluster

### Operating system / Environment

Mac OS X 10.14.6 build 18G84

### PR DESCRIPTION
**Pull request by warrenbailey**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description
Use the vault operator version from the vault-operator in jenkins-x-charts (https://github.com/jenkins-x-charts/vault-operator/blob/master/vault-operator/values.yaml)

This should then allow us to remove the version info in the jenkins-x-versions (https://github.com/jenkins-x/jenkins-x-versions/blob/master/docker/banzaicloud/vault-operator.yml) 

#### Which issue this PR fixes

fixes #4988

### CODE REVIEW

**Comment by pmuir** [comment]
/lgtm

@warrenbailey I also updated the fixes in the PR so that it links to the issue properly.

**Comment by warrenbailey** [comment]
thanks @pmuir

**Pull request merged**
