### PR TITLE
chore add missing entries from go.sum

### PR DESCRIPTION
**Pull request by jtnord**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

Add some entries that where missing from `go.sum`

### CODE REVIEW

**Comment by jglick** [comment]
Relation to #2257?

**Comment by jtnord** [comment]
@jglick that doesn't fully work.  the makefile and build won;t pull uneeded dependencies it seems and some things may be conditionally compiled (haven;t checked)  but on my windows system if I run
`go list ./...` which is used in the `Makefile` bootstrap then it will modify the files (presumably as I am on windows and it pulls those files.
If i run `set GOOS=linux & go list ./...` then it does not update the files.

I expected others to be able to reproduce this on linux/mac by doing `export GOOS=windows & go list ./...` but that apparantly does not show the issue.

https://kubernetes.slack.com/archives/C9LTHT2BB/p1542375114244400?thread_ts=1542116244.174600&cid=C9LTHT2BB

**Comment by jglick** [comment]
@jtnord maybe `go mod tidy` is what you were looking for? Just guessing.

**Pull request merged**
