### PR TITLE
fix: correct setup the gitInfo on jx create pullrequest

### LINKED ISSUE #5224: jx create pullrequest behaviour change impacting ML builds
### Summary 
Machine Learning training builds have stopped working following a recent change beneath `jx create pullrequest`.

The pipeline for ML training applications uses `jx create pullrequest --push -b --title 'New model trained' --body 'feat: New model trained'` in order to push an instance of the trained model into the repo for the associated ML service app. This has stopped working following a platform upgrade late last week.

I now see the error: 
```
Switched to a new branch 'syncmodel'
Updated git hooks.
Git LFS initialized.
"*.onnx" already supported
error: failed to create PR for base master and head branch syncmodel: pushing merged branch syncmodel: Have you set up a git credential helper? See https://help.github.com/articles/caching-your-github-password-in-git/
: git output: fatal: '//abuildbot:<redactedtoken>@' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.: failed to run 'git push //abuildbot:<redactedtoken>@ --force HEAD:syncmodel' command in directory '/workspace/source/test012-service', output: 'fatal: '//abuildbot:<redactedtoken>@' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.'
Using previous PR
<redacted>  model.onnx
```

Looks like the git push is missing the URL of the repo to push to.

### PR DESCRIPTION
**Pull request by pmuir**
#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #5224

### CODE REVIEW

**Comment by pmuir** [comment]
@tdcox can you test this please

**Comment by abayer** [comment]
Looks good, will hold off approving until Terry can test it.

**Comment by tdcox** [comment]
That fixes it.

/lgtm

**Pull request merged**
