### PR TITLE
chore: remove sso addon which is replaced by jx-app-sso

### PR DESCRIPTION
**Pull request by ccojocar**
This addon was replaced by jx-app-sso. See github.com/jenkins-x-apps/jx-app-sso for more detials.

#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by tdcox** [comment]
jx-app-sso has no documentation so you may want to recycle the relevant parts of the sso addon docs before they are removed.

**Comment by ccojocar** [comment]
Good point! It seems that the description of the parameters are missing form the schema https://github.com/jenkins-x-apps/jx-app-sso/blob/master/jx-app-sso/values.schema.json.

**Pull request merged**
