### PR TITLE
fix: use the upgrade addon prow command

### LINKED ISSUE #3392: Hook and Tide pods failing with credentials error
### Summary 
Both Hook and Tide pods have started failing into CrashLoopBackOff with the same "Bad credentials" error against GitHub.
```
{"component":"tide","error":"error getting bot name: fetching bot name from GitHub: status code 401 not one of [200], body: {\"message\":\"Bad credentials\",\"documentation_url\":\"https://developer.github.com/v3\"}","level":"fatal","msg":"Error getting Git client.","time":"2019-03-21T10:15:31Z"}
```

### Steps to reproduce the behavior
Unclear. This server has been running for about three days on preemptible nodes. The fault appears to have started a little while after upgrading the platform install and subsequent to a node being automatically flushed.

### Expected behavior
Expected that Hook and Tide would continue to be able to connect to GitHub.

### Actual behavior
Both pods seem to have lost the credentials needed to connect to GitHub. Are they unable to persist their config through a restart?

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.998
jenkins x platform 0.0.3588
Kubernetes cluster v1.11.7-gke.4
kubectl            v1.13.4
helm client        Client: v2.13.0+g79d0794
git                git version 2.21.0
Operating System   Mac OS X 10.13.6 build 17G4015
```

### Jenkins type

- [ ] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster
```
jx create cluster gke \
--cluster-name='d27' \
--default-admin-password='xxxxx' \
--environment-git-owner='tdcox' \
--enhanced-apis=true \
--enhanced-scopes=true \
--git-username='tdcox' \
--git-private=false \
--kaniko=true \
--labels='demo=true' \
--machine-type='n1-standard-4' \
--max-num-nodes='3' \
--min-num-nodes='2' \
--no-tiller=true \
--preemptible=true \
--project-id='jx-mar19' \
--prow=true \
--skip-login=true \
--tekton=true \
--vault=false \
--zone='europe-west1-d'
```

### PR DESCRIPTION
**Pull request by warrenbailey**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

Defer to the `jx upgrade add on prow` command when upgrading all add ons including jx-prow.

#### Which issue this PR fixes

fixes #3392

https://github.com/jenkins-x/jx/issues/3392

### CODE REVIEW

**Comment by rawlingsj** [comment]
@warrenbailey think it was just a small lint issue, :point_up: I pushed to your branch

**Comment by warrenbailey** [comment]
thanks @rawlingsj

**Pull request merged**
