### PR TITLE
fix: Switch bdd context to create a cluster

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

The `bdd` context has been flaky lately in the shared cluster, so let's move it to new clusters for each run.

#### Which issue this PR fixes

n/a

### CODE REVIEW

**Comment by abayer** [comment]
/hold

Holding until I've verified that the contents of `jenkins-x-static.yml` actually work, at which point I'll revert the overwrite of `jenkins-x-bdd.yml`.

**Comment by abayer** [comment]
/hold cancel

Unholding - not worth the hassle of context renaming, really.

**Comment by ccojocar** [comment]
@abayer I guess you need to add `static-e2e-tests` to weasel cluster dev env. It doesn't seem to trigger.

**Pull request merged**
