### PR TITLE
fix(tekton): Make sure the effective pipeline yml contains release.setVersion

### LINKED ISSUE #4844: setVersion steps from build packs aren't executed by `step_create_task`
Since the move to generating the effective pipeline, `setBuildVersion` has been getting passed a `PipelineConfig` without any lifecycles, just the `Pipeline`s. This means that we can't tell what the release `setVersion` steps are to run them in `step_create_task`, so that things like the `maven` build pack calling `mvn versions:set ...` never happen.

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

Otherwise we don't know what exactly to run in `setBuildVersion`.

#### Special notes for the reviewer(s)

/assign @hferentschik 

#### Which issue this PR fixes

fixes #4844

### CODE REVIEW

**Comment by hferentschik** [comment]
Ok, I tested this locally and I got:

```yaml
buildPack: maven
pipelineConfig:
  agent:
    image: maven
    label: jenkins-maven
  extends:
    file: maven/pipeline.yaml
    import: classic
  pipelines:
    post: {}
    pullRequest:
      pipeline:
        options:
          containerOptions:
            env:
            - name: DOCKER_REGISTRY
              valueFrom:
                configMapKeyRef:
                  key: docker.registry
                  name: jenkins-x-docker-registry
            - name: TILLER_NAMESPACE
              value: kube-system
            - name: DOCKER_CONFIG
              value: /home/jenkins/.docker/
            - name: GIT_AUTHOR_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_AUTHOR_NAME
              value: jenkins-x-bot
            - name: GIT_COMMITTER_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_COMMITTER_NAME
              value: jenkins-x-bot
            - name: JENKINS_URL
              value: http://jenkins:8080
            - name: MAVEN_OPTS
              value: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
            - name: XDG_CONFIG_HOME
              value: /home/jenkins
            - name: _JAVA_OPTIONS
              value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
                -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5
                -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
                -Xms10m -Xmx192m
            name: ""
            resources:
              requests:
                cpu: 400m
                memory: 512Mi
            securityContext:
              privileged: true
            volumeMounts:
            - mountPath: /home/jenkins
              name: workspace-volume
            - mountPath: /var/run/docker.sock
              name: docker-daemon
            - mountPath: /root/.m2/
              name: volume-0
            - mountPath: /home/jenkins/.docker
              name: volume-1
            - mountPath: /home/jenkins/.gnupg
              name: volume-2
        stages:
        - agent:
            image: maven
          name: from-build-pack
          steps:
          - command: mvn versions:set -DnewVersion=$PREVIEW_VERSION
            dir: /workspace/source
            image: maven
            name: build-set-version
          - command: mvn install
            dir: /workspace/source
            image: maven
            name: build-mvn-install
          - command: skaffold version
            dir: /workspace/source
            image: maven
            name: build-skaffold-version
          - args:
            - --cache=true
            - --cache-dir=/workspace
            - --context=/workspace/source
            - --dockerfile=/workspace/source/Dockerfile
            - --destination=gcr.io/apps-dev-229310/liberty:${inputs.params.version}
            - --cache-repo=gcr.io/apps-dev-229310/cache
            command: /kaniko/executor
            dir: /workspace/source
            image: gcr.io/kaniko-project/executor:9912ccbf8d22bbafbf971124600fbb0b13b9cbd6
            name: build-container-build
          - command: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
            dir: /workspace/source
            image: maven
            name: postbuild-post-build
          - command: make preview
            dir: /workspace/source/charts/preview
            image: maven
            name: promote-make-preview
          - command: jx preview --app $APP_NAME --dir ../..
            dir: /workspace/source/charts/preview
            image: maven
            name: promote-jx-preview
    release:
      pipeline:
        options:
          containerOptions:
            env:
            - name: DOCKER_REGISTRY
              valueFrom:
                configMapKeyRef:
                  key: docker.registry
                  name: jenkins-x-docker-registry
            - name: TILLER_NAMESPACE
              value: kube-system
            - name: DOCKER_CONFIG
              value: /home/jenkins/.docker/
            - name: GIT_AUTHOR_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_AUTHOR_NAME
              value: jenkins-x-bot
            - name: GIT_COMMITTER_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_COMMITTER_NAME
              value: jenkins-x-bot
            - name: JENKINS_URL
              value: http://jenkins:8080
            - name: MAVEN_OPTS
              value: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
            - name: XDG_CONFIG_HOME
              value: /home/jenkins
            - name: _JAVA_OPTIONS
              value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
                -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5
                -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
                -Xms10m -Xmx192m
            name: ""
            resources:
              requests:
                cpu: 400m
                memory: 512Mi
            securityContext:
              privileged: true
            volumeMounts:
            - mountPath: /home/jenkins
              name: workspace-volume
            - mountPath: /var/run/docker.sock
              name: docker-daemon
            - mountPath: /root/.m2/
              name: volume-0
            - mountPath: /home/jenkins/.docker
              name: volume-1
            - mountPath: /home/jenkins/.gnupg
              name: volume-2
        stages:
        - agent:
            image: maven
          name: from-build-pack
          steps:
          - command: jx step git credentials
            dir: /workspace/source
            image: maven
            name: setup-jx-git-credentials
          - command: mvn clean deploy
            dir: /workspace/source
            image: maven
            name: build-mvn-deploy
          - command: skaffold version
            dir: /workspace/source
            image: maven
            name: build-skaffold-version
          - args:
            - --cache=true
            - --cache-dir=/workspace
            - --context=/workspace/source
            - --dockerfile=/workspace/source/Dockerfile
            - --destination=gcr.io/apps-dev-229310/liberty:${inputs.params.version}
            - --cache-repo=gcr.io/apps-dev-229310/cache
            command: /kaniko/executor
            dir: /workspace/source
            image: gcr.io/kaniko-project/executor:9912ccbf8d22bbafbf971124600fbb0b13b9cbd6
            name: build-container-build
          - command: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:${VERSION}
            dir: /workspace/source
            image: maven
            name: build-post-build
          - command: jx step changelog --version v${VERSION}
            dir: /workspace/source/charts/liberty
            image: maven
            name: promote-changelog
          - command: jx step helm release
            dir: /workspace/source/charts/liberty
            image: maven
            name: promote-helm-release
          - command: jx promote -b --all-auto --timeout 1h --version ${VERSION}
            dir: /workspace/source/charts/liberty
            image: maven
            name: promote-jx-promote
      setVersion:
        steps:
        - image: maven
          steps:
          - comment: so we can retrieve the version in later steps
            name: next-version
            sh: echo \$(jx-release-version) > VERSION
          - name: set-version
            sh: mvn versions:set -DnewVersion=\$(cat VERSION)
          - name: tag-version
            sh: jx step tag --version \$(cat VERSION)
```

So I can see how the effective pipeline contains `setVersion` now and I understand that this kind of works with _step create task_. As a first step, we probably want to merge this, since it will bring back functionality which was lost with the effective pipeline approach. 

However, this also means that setting the version is still not part of the pipeline per se, but executed as part or better prior to creating the Tekton CRDs. This also explains, why the pipelinerunner would be based on a maven image since it needs mvn to set the release version. Not to mention that it uses `jx-release-version` (Is this binary still supported? Does it get added to all our builder images? What is its relation to `jx step next version`).

What if someone wants to increment the version in a different way or has his own tool? As it stands now, the agent/image is ignored for `setVersion`, it executes in the image `step create task` is executed. Currently, this means the `pipelinerunner` image and with meta pipeline, it will be the image meta pipeline uses per default for the `step create task` step. 

IMO the setting of the version, aka the `setVersion` part of the pipeline config, have to become steps which need to be inserted prior to the actual release steps, in the case of maven, prior to `mvn deploy`. 

@abayer WDYT? 
@jstrachan, @rawlingsj  - why is `setVersion` executed locally?

**Comment by abayer** [comment]
@hferentschik Sounds reasonable to me.

**Comment by hferentschik** [comment]
Verified this worked and solves the problem for now.

/lgtm

**Pull request merged**
