### PR TITLE
refactor: remove the headless flag and replace its usage with batch flag

### PR DESCRIPTION
**Pull request by ccojocar**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

part of #1016

fixes #

### CODE REVIEW

**Comment by pmuir** [comment]
Looks like generation needs to be run

**Comment by jstrachan** [comment]
@ccojocar I wonder if you could rebase? we had some proxy/code generation/formatting issues fixed yesterday?

**Comment by jstrachan** [comment]
@ccojocar  looks like compile error
```
# github.com/jenkins-x/jx/pkg/jx/cmd_test [github.com/jenkins-x/jx/pkg/jx/cmd.test]
pkg/jx/cmd/install_gitops_integration_test.go:105:3: o.Headless undefined (type cmd.InstallOptions has no field or method Headless)
```

**Pull request merged**
