### PR TITLE
[wip] fix: check for response code when validating repository

### LINKED ISSUE #7198: Check for response status code before asserting the existence of a remote git repository
### Summary 
`ValidateRepositoryName` in the case of a github repository calls this api: https://developer.github.com/v3/repos/#get-a-repository, and asserts that the repository exists, if the error is nil. The error nil in this case just means the jx was able to contact the api, and get a response, it could be any status code. This behaviour exists for other git providers also (bitbucket and gitlab)

### Steps to reproduce the behavior
https://kubernetes.slack.com/archives/C9MBGQJRH/p1589656864056600
### Expected behavior
If the repository **does not** exist, jx should not throw an error that the repository exists.
### Actual behavior
jx throws an error that the repository exists.
### Jx version
2.1.38
The output of `jx version` is:

```
NAME               VERSION
jx                 2.1.38
Kubernetes cluster v1.15.11-eks-af3caf
kubectl            v1.16.2
helm client        2.16.7
git                2.21.1 (Apple Git-122.3)
Operating System   Mac OS X 10.15.4 build 19E287
```

### Kubernetes cluster

EKS v1.15.11

### Operating system / Environment
Mac OSX 10.15.4

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description
This PR does some general refactoring of the ValidateRepositoryName function. It would be nice to have a single function, since the logic is repeated across different git providers. However, there needs to be some changes upstream (in gitea go-sdk), before we can do that. Also a general refactoring of gitlab is needed before that imo.

#### Which issue this PR fixes

fixes #7198

/assign @hferentschik

### CODE REVIEW

**Comment by ankitm123** [comment]
@hferentschik that's why it is in WIP :)

**Comment by hferentschik** [comment]
@ankitm123 - hi, just wondering what the status is on this pull request?

**Comment by ankitm123** [comment]
@hferentschik There is an upstream gitea issue that I need to fix before I can work on this PR. I will get to it today. The idea is to have similar function signatures for gitea as github and bitbucket.

**Comment by hferentschik** [comment]
Thanks for the update :-) 

>  There is an upstream gitea issue that I need to fix before I can work on this PR.

Cool. Way to go. Fixing even issues in dependencies. Big 👍 

> I will get to it today. The idea is to have similar function signatures for gitea as github and bitbucket

No worries at all. Just wanted to see where things are.

**Comment by ankitm123** [comment]
Closing this for now, will re-open once the gitea PR is merged.

**Pull request closed without merging**
