### PR TITLE
fix: corrected funky find charts logic

### PR DESCRIPTION
**Pull request by tomhobson**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

findChartsDir() logic is messed up by an or checking if the file path is greater than the other. Which completely voids the use of the rank() method.

#### Which issue this PR fixes

fixes https://github.com/jenkins-x/jx/issues/7591

### CODE REVIEW

**Comment by tomhobson** [comment]
@rawlingsj could you update on what's gone wrong with this PR?

**Comment by rawlingsj** [comment]
> could you update on what's gone wrong with this PR? 

Just checked and its related to an old chart that is part of this BDD test, I'm half tempted to override the failing test but might see if I can fix it quickly.

**Comment by rawlingsj** [comment]
jacoco app is failing to release with the new deployment api version so overriding failing tests until we get time to fix that.  Focus is currently on getting v3 to beta.
/override tekton
/override boot-vault
/lgtm

**Pull request merged**
