### PR TITLE
feat: perform pre-release of jx prior to version stream release

### PR DESCRIPTION
**Pull request by cagiti**
Signed-off-by: Cai Cooper <caicooper82@gmail.com>

### CODE REVIEW

**Comment by ccojocar** [comment]
@cagiti What's the status of this one? Are you planning to work on it to complete it?

**Comment by hferentschik** [comment]
@cagiti Same question as @ccojocar ;-) I would love to get this in to prevent doing `jx` releases getting out with defects. ATM, we catch a lot of issues in the version stream tests, but by the time they run the new `jx` version is already pushed out afaiu.

**Comment by cagiti** [comment]
apologies @ccojocar & @hferentschik, your comments were lost in the hundreds of github messages I get :(

**Pull request merged**
