### PR TITLE
feat: add option request memory to devpod

### LINKED ISSUE #6918: add request-memory option for devpod
### Summary 
The same way we have a request cpu option for devpod and request memory should be added

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### PR DESCRIPTION
**Pull request by yelhouti**
#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [X] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #6918

### CODE REVIEW

**Comment by hferentschik** [comment]
@yelhouti, looking good. Would you mind opening an issue as well and referencing it in the pull request and/or commit message?

Wonder whether this could be somehow made testable?

**Comment by yelhouti** [comment]
@hferentschik I can definitely try to add some tests if needed, but since this a dev feature, and there is already a request-cpu, I just copy pasted and edited the code, this is really not a big deal...
Also I only tend to create issues for bugs, when doing new features or code cleanups I feel the PR is self documenting (not really an issue)

**Comment by hferentschik** [comment]
>  I can definitely try to add some tests if needed, but since this a dev feature, and there is already a request-cpu, I just copy pasted and edited the code, this is really not a big deal...

ok. I am fine with that. Test coverage is an issue in the codebase, so I like to use every opportunity to nudge people to write tests :-) I think at least planting the seed is a win.

> Also I only tend to create issues for bugs, when doing new features or code cleanups I feel the PR is self documenting (not really an issue)

We try to create issues for everything. Issues are not only reserved for bugs. For that reason, there are also labels like kind/bug and kind/feature.
Being consistent this way makes searching easier (even though GitHub treats PR and issues partly the same way, they are not and you usually search in one or the other) and it makes fore a more consistent changelog generation. 

Also creating an issue helps you to reflect and put into words what you are trying to solve and gives the reviewer the context he needs to see the change in the bigger picture. 

Hope that clarifies a bit where I am coming from.

**Comment by yelhouti** [comment]
> Hope that clarifies a bit where I am coming from.
Totally get you, here you go an issue has been added :)

**Pull request merged**
