### PR TITLE
fix: always fetch to a new local branch

### LINKED ISSUE #5576: JX Boot can create a local commit during that then gets rejected during a fetch
### Summary 

When running the master build of `jx boot`, outside of a tekton pipeline, its possible to generate a local commit (often due to whitespace/formatting changes) that stops a the `git fetch` from working.

A hack would be to change the `git fetch` to a `git fetch --force`, but a better solution would be to use FETCH_HEAD and create a merge (if required)

```
error: creating dev environment for environment-jx-aps-consumer-gjq-dev: forking and pulling https://github.com/garethjevans-test/environment-jx-aps-consumer-gjq-dev.git: fetching origin master: git output: From https://github.com/garethjevans-bot/environment-jx-aps-consumer-gjq-dev
 ! [rejected]        master     -> origin/master  (non-fast-forward): failed to run 'git fetch https://garethjevans-bot:<token>@github.com/garethjevans-bot/environment-jx-aps-consumer-gjq-dev.git master:remotes/origin/master' command in directory '/home/jenkins/environment-jx-aps-consumer-gjq-dev', output: 'From https://github.com/garethjevans-bot/environment-jx-aps-consumer-gjq-dev
 ! [rejected]        master     -> origin/master  (non-fast-forward)'
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step verify env' command in directory '.', output: ''
```

### PR DESCRIPTION
**Pull request by pmuir**
fixes #5576

Signed-off-by: Pete Muir <pmuir@bleepbleep.org.uk>

#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [X] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by garethjevans** [comment]
it looks like there are a lot of genuine test failures on this

**Comment by rawlingsj** [comment]
> it looks like there are a lot of genuine test failures on this

yeah agreed, here's one of them:
```
=== FAIL: pkg/cmd/upgrade TestUpgradeAppForGitOps (0.73s)
Read credentials for http://fake.chartmuseum from vault helm/repos
    upgrade_apps_test.go:70: 
        	Error Trace:	upgrade_apps_test.go:70
        	Error:      	Received unexpected error:
        	            	failed to run 'git merge f38857c9-f1b8-4e46-87f8-3367d8cb0ba7' command in directory '/tmp/**-environments350583759/dev', output: 'merge: f38857c9-f1b8-4e46-87f8-3367d8cb0ba7 - not something we can merge'
        	            	git output: merge: f38857c9-f1b8-4e46-87f8-3367d8cb0ba7 - not something we can merge
        	            	github.com/jenkins-x/**/pkg/gits.(*GitCLI).gitCmd
        	            		/workspace/source/pkg/gits/git_cli.go:526
        	            	github.com/jenkins-x/**/pkg/gits.(*GitCLI).Merge
        	            		/workspace/source/pkg/gits/git_cli.go:1020
        	            	github.com/jenkins-x/**/pkg/gits.ForkAndPullRepo
        	            		/workspace/source/pkg/gits/helpers.go:610
        	            	github.com/jenkins-x/**/pkg/environments.(*EnvironmentPullRequestOptions).Create
        	            		/workspace/source/pkg/environments/gitops.go:58
        	            	github.com/jenkins-x/**/pkg/apps.(*GitOpsOptions).UpgradeApp
        	            		/workspace/source/pkg/apps/gitops.go:103
        	            	github.com/jenkins-x/**/pkg/apps.(*InstallOptions).UpgradeApp
        	            		/workspace/source/pkg/apps/install.go:261
        	            	github.com/jenkins-x/**/pkg/cmd/upgrade.(*UpgradeAppsOptions).Run
        	            		/workspace/source/pkg/cmd/upgrade/upgrade_apps.go:213
        	            	github.com/jenkins-x/**/pkg/cmd/upgrade_test.TestUpgradeAppForGitOps
        	            		/workspace/source/pkg/cmd/upgrade/upgrade_apps_test.go:69
        	            	testing.tRunner
        	            		/usr/local/go/src/testing/testing.go:865
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1337
        	            	github.com/jenkins-x/**/pkg/gits.ForkAndPullRepo
        	            		/workspace/source/pkg/gits/helpers.go:612
        	            	github.com/jenkins-x/**/pkg/environments.(*EnvironmentPullRequestOptions).Create
        	            		/workspace/source/pkg/environments/gitops.go:58
        	            	github.com/jenkins-x/**/pkg/apps.(*GitOpsOptions).UpgradeApp
        	            		/workspace/source/pkg/apps/gitops.go:103
        	            	github.com/jenkins-x/**/pkg/apps.(*InstallOptions).UpgradeApp
        	            		/workspace/source/pkg/apps/install.go:261
        	            	pulling environment repo https://fake.git/fc358fc8-4815-405b-a6ee-a08acf344674/environment-fc358fc8-4815-405b-a6ee-a08acf344674-4bbb2d04-fc09-4b4b-b596-6fa972bb5fff-dev.git into /tmp/**-environments350583759
        	            	github.com/jenkins-x/**/pkg/environments.(*EnvironmentPullRequestOptions).Create
        	            		/workspace/source/pkg/environments/gitops.go:61
        	            	github.com/jenkins-x/**/pkg/apps.(*GitOpsOptions).UpgradeApp
        	            		/workspace/source/pkg/apps/gitops.go:103
        	            	github.com/jenkins-x/**/pkg/apps.(*InstallOptions).UpgradeApp
        	            		/workspace/source/pkg/apps/install.go:261
        	            	github.com/jenkins-x/**/pkg/cmd/upgrade.(*UpgradeAppsOptions).Run
        	            		/workspace/source/pkg/cmd/upgrade/upgrade_apps.go:213
        	            	github.com/jenkins-x/**/pkg/cmd/upgrade_test.TestUpgradeAppForGitOps
        	            		/workspace/source/pkg/cmd/upgrade/upgrade_apps_test.go:69
        	            	testing.tRunner
        	            		/usr/local/go/src/testing/testing.go:865
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1337
        	Test:       	TestUpgradeAppForGitOps
    upgrade_apps_test.go:73: 
        	Error Trace:	upgrade_apps_test.go:73
        	Error:      	Received unexpected error:
        	            	pull request with id '1' not found
        	Test:       	TestUpgradeAppForGitOps
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x219757c]
```

**Pull request merged**
