### PR TITLE
fix(git): parsing of Bitbucket Server URLs

### LINKED ISSUE #6419: jx preview fails for repo in bitbucket server
### Summary 

jx preview fails for quickstart repo in bitbucket server

### Steps to reproduce the behavior

Install Jenkins X as Server on EKS, use Bitbucket Server as repository for quickstart

### Expected behavior

jx preview succeeds

### Actual behavior

jx preview fails
On the surface it looks like it is using the term "overview" instead of the actual repository name. Is it a possible but for bitbucketserver integrations?

I have provided the term ```<org>``` instead of the actual BitBucket organisation

```
+ jx preview --app demo-app --dir ../..
Creating a preview
WARNING: issue getting pull request <org>, overview, 3: Status: 404 , Body: {"errors":[{"context":null,"message":"Repository <org>/overview does not exist.","exceptionName":"com.atlassian.bitbucket.repository.NoSuchRepositoryException"}]}
WARNING: Unable to get commits: Status: 404 , Body: {"errors":[{"context":null,"message":"Repository <org>/overview does not exist.","exceptionName":"com.atlassian.bitbucket.repository.NoSuchRepositoryException"}]}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x370dbec]

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/cmd/preview.(*PreviewOptions).Run(0xc000978000, 0x4cacd01, 0xa)
	/workspace/source/pkg/cmd/preview/preview.go:321 +0x392c
github.com/jenkins-x/jx/pkg/cmd/preview.NewCmdPreview.func1(0xc000967680, 0xc0008b2c00, 0x0, 0x4)
	/workspace/source/pkg/cmd/preview/preview.go:134 +0xaa
github.com/spf13/cobra.(*Command).execute(0xc000967680, 0xc0008b2bc0, 0x4, 0x4, 0xc000967680, 0xc0008b2bc0)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc000655400, 0xc0007c2040, 0x59d65c0, 0xc0000bc000)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/jenkins-x/jx/cmd/jx/app.Run(0x0, 0x0, 0x0, 0xc0008b1f88, 0xc0000a2058)
	/workspace/source/cmd/jx/app/jx.go:19 +0x185
main.main()
	/workspace/source/cmd/jx/jx.go:11 +0x32
````

I believe GitInfo.Name is being populated incorrectly. See https://github.com/jenkins-x/jx/blob/3032216788e7fd1a720a5eab56e52cad63fd0dba/pkg/cmd/preview/preview.go#L291

### Jx version

The output of `jx version` is:

```
jx                 2.0.1100
jenkins x platform 2.0.1813
Kubernetes cluster v1.14.9-eks-c0eccc
kubectl            v1.15.3
helm client        Client: v2.14.3+g0e7f3b6
git                2.22.0
Operating System   Mac OS X 10.14.6 build 18G95
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ X ] Classic Jenkins

### Kubernetes cluster

EKS - Created using eksctl

### Operating system / Environment

On Jenkins Server

### PR DESCRIPTION
**Pull request by polothy**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

The source URL can sometimes look like this in Jenkins:

    /projects/ORG/repos/NAME/pull-requests/1/overview

The /overview causes the git URL parser to think that the project name is "overview" instead of "NAME".

#### Which issue this PR fixes

Fixes #6419

### CODE REVIEW

**Comment by abayer** [comment]
/lgtm

Thanks!

**Comment by abayer** [comment]
/retest

The lint failure was a random issue downloading a go module dependency, rerunning.

**Comment by polothy** [comment]
Thanks for looking at this @abayer - let me know if I need to make any updates to fix the lint test.

**Comment by polothy** [comment]
/retest

Just seeing if it'll go through now.

**Comment by abayer** [comment]
@polothy Nothing you need to do on your side - I'm seeing it locally as well and am pretty sure it's something transient and out of our control. I'll rerun this later today/this weekend until it actually passes.

**Comment by polothy** [comment]
OK, thanks for the update!

**Comment by abayer** [comment]
ha, so it's because https://github.com/googleapis/gnostic/tree/master/openapiv2 was renamed from `OpenAPIv2` and broke `go get` stuff used in the OpenAPI codegen. Sigh. I'll take a quick look to see if there's a quick fix, otherwise I'll just override this.

**Comment by polothy** [comment]
ooof

**Comment by abayer** [comment]
Ok, I opened #6679, and #6680 to "fix" it. I want to get reviews from people who've dealt with our codegen tooling's quirky logic around `go get` in the past so that I have a slightly higher level of confidence that this won't, y'know, break more things, but I'm pretty sure it's good. Once that's in (which admittedly probably won't be until Monday, or possibly Tuesday since the entire jx team here at CloudBees is traveling to a week of face-to-face meetings on Monday), I'll retest this and it should be fine. And if for some reason my fix isn't sufficient and `lint` is still borked by sometime Tuesday EU time, I'll just sigh and override this. =)

**Comment by polothy** [comment]
Hey @abayer - thanks so much for looking into the CI problem!  Have fun at with the team :)

**Comment by polothy** [comment]
thanks @abayer ! 🍺

**Pull request merged**
