### PR TITLE
chore: remove the --file flag from 'jx step credential'

### PR DESCRIPTION
**Pull request by garethjevans**
this command allows a pipeline to download a secret and store it in
a file on the file system.  This is not a recommended approach, secrets 
should be mounted outside of the workDir

### CODE REVIEW

**Comment by abayer** [comment]
/hold

@garethjevans - putting this on hold briefly so that we can get #5613 in ASAP. I'll unhold it once that merges.

**Comment by garethjevans** [comment]
no worries @abayer

**Comment by abayer** [comment]
(this got unheld right after I added `boot-vault` as required, so it went and kicked that off, but it also needs to run all the other contexts since there'd been a merge to master, so I just launched them manually)

**Comment by abayer** [comment]
...and then `boot-vault` failed but that was due to a burp fetching go modules.

**Pull request merged**
