### PR TITLE
fix: Add cleanup for GKE addresses

### LINKED ISSUE #3285: Extend the `jx gc gke` command to remove unused items from GKE
### Summary 

During the process of creating and destroying clusters by user/automated tests, it leaves many unused items, which build up over time and breach our quota. We already have a mechanism to generate a script which clears down some items, but it would be useful if that were extended to also cover:
- IP addresses
- Instance groups

### PR DESCRIPTION
**Pull request by cagiti**
#### Description
This change adds cleanup commands for more items not removed when clusters are removed from GKE

#### Which issue this PR fixes

fixes #3285

### CODE REVIEW

**Comment by cagiti** [comment]
@rawlingsj this seems to be a lot healthier since we moved it over to build on tekton

**Comment by rawlingsj** [comment]
awesome!
/lgtm

**Pull request merged**
