### PR TITLE
fix: fix the jx changelog for now

### PR DESCRIPTION
**Pull request by pmuir**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Special notes for the reviewer(s)
This at least restores the broken release notes as covered in #4867. @hferentschik when you are back you should pick this up and see how you think it should be fixed properly. 

We should also think about how we actually test this - it was certainly returning a nonexistent SHA.

### CODE REVIEW

**Comment by pmuir** [comment]
I think I genuinely have failing tests locally. Unfortunately I can't run these tests locally. Will try to fix now

**Comment by sboardwell** [comment]
As requested, here's the link to the [slack channel thread explaining the problem](https://kubernetes.slack.com/archives/C9LTHT2BB/p1554101602076100?thread_ts=1554101602.076100&cid=C9LTHT2BB)

Basically the changes made (i.e. the commit) from replacing the various versions (in `Chart.yaml`, etc) are not pushed back to the branch under test, but rather pushed with the tag being created. Therefore:
* the commit (of the actual release tag) will not be found on the main branch
* the parent commit (of the actual release tag) will be found, but is not tagged

Here as a git graph from the jx repository:
```
$ git log --tags --graph --oneline --decorate --simplify-by-decoration| head
* b5570557c (tag: v2.0.538) release 2.0.538
* d4d40f1c6 (upstream/master) fix: fixed a bug that made boot fail when a generated bucket name ended with '-'
| * 29303a392 (tag: v2.0.537) release 2.0.537
|/
| * 37fd31f18 (tag: v2.0.536) release 2.0.536
|/
| * bbcbc3a81 (tag: v2.0.535) release 2.0.535
|/
| * c3ff6503b (tag: v2.0.534) release 2.0.534
|/
```

Interestingly, at some point, the tags were being committed to the master branch, here for example around version `2.0.399` :
```
$ git log --tags --graph --oneline --decorate --simplify-by-decoration| grep -C 4 "2\.0\.399"
| * 63611b2c1 (tag: v2.0.401) release 2.0.401
|/
| * 5ed7aaae9 (tag: v2.0.400) release 2.0.400
|/
* 5250ff555 (tag: v2.0.399) release 2.0.399
* 1f6bb6256 (tag: v2.0.398) release 2.0.398
| * cb3b46e16 (tag: v2.0.397) release 2.0.397
|/
| * 87fcb470c (tag: v2.0.396) release 2.0.396
```
This tag can be found on the master branch
```
$ git --no-pager branch --contains 5250ff555
* master
```
However, the next release `5ed7aaae9 (tag: v2.0.400) release 2.0.400` cannot:
```
$ git --no-pager branch --contains 5ed7aaae9
```

---------------------------------------------------
One initial workaround was to tag the parent commit with a `v` prefix `v<version>` and the "released/replaced" commit with an `r` prefix `r<version>`, so that:

The `v` prefix tag is on the parent and can be found using `git describe`
```
$ git describe --abbrev=0 --tags --always
v3.1.0

$ git --no-pager branch --contains v3.1.0
  develop
* master
```

It has a associated `r` prefix tag, which is headless and cannot be found 
```
$ git --no-pager branch --contains r3.1.0
```

The diff between the two is the version replacement
```
$ git --no-pager diff v3.1.0..r3.1.0
diff --git a/charts/eur988-jx-quickstart/Chart.yaml b/charts/eur988-jx-quickstart/Chart.yaml
index e40e929..d28e930 100644
--- a/charts/eur988-jx-quickstart/Chart.yaml
+++ b/charts/eur988-jx-quickstart/Chart.yaml
@@ -2,4 +2,4 @@ apiVersion: v1
 description: A Helm chart for Kubernetes
 icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/nodejs.png
 name: eur988-jx-quickstart
-version: 0.1.0-SNAPSHOT
+version: 3.1.0
diff --git a/charts/eur988-jx-quickstart/values.yaml b/charts/eur988-jx-quickstart/values.yaml
index 55d5e01..c98f9a2 100755
--- a/charts/eur988-jx-quickstart/values.yaml
+++ b/charts/eur988-jx-quickstart/values.yaml
@@ -3,8 +3,8 @@
 # Declare variables to be passed into your templates.
 replicaCount: 1
 image:
-  repository: draft
-  tag: dev
+  repository: us.gcr.io/devops-project-200915/eur988-jx-quickstart
+  tag: 3.1.0
   pullPolicy: IfNotPresent

 # define environment variables here as a map of key: value
```

Still, it's not perfect and I am currently exploring using gitflow with Jenkins X, using [gitversion](https://gitversion.readthedocs.io/en/latest/) as the version creation tool. Will let you know how I get on.

Hope this helps a little.

**Comment by pmuir** [comment]
I also found out that that the sha of the tag is not the same as the sha of the commit pointed to by the sha. If we use the latter, it works (which makes sense) given Steve's comments above but I think is generally correct anyway as the tag itself will never be on the mainline regardless of whether we push the commit or not.

**Comment by sboardwell** [comment]
I think it's about the ref names of the commits.

You can tag a specific commit on the master which would result in the tag being identifiable in the git history/log. However, tagging a commit that is not on the history basically creates a separate unassociated branch.

My normal commit is tagged (this doesn't happen in Jenkins X as standard)
```
$ git log --pretty=format:"%h %ad %an %s %d" | grep "3\.1\.0"
2a71b2b 3 days ago Steve Boardwell Merge branch 'release-3.1.0'  (tag: v3.1.0)
```
The release version changing commit is also tagged, just not pushed back into to the master branch (which is correct btw, because you don't want every push to master to have a twin version change commit).

You can see this if you git check the tag itself out.
```
$ gco -q r3.1.0
$ git log --pretty=format:"%h %ad %an %s %d" | grep "3\.1\.0"
74f2cc3 3 days ago jenkins-x-bot Official Release 3.1.0  (HEAD, tag: r3.1.0)
2a71b2b 3 days ago Steve Boardwell Merge branch 'release-3.1.0'  (tag: v3.1.0)
```

**Pull request merged**
