### PR TITLE
Upgraded AWS SDK

### PR DESCRIPTION
**Pull request by hekonsek**
Upgraded AWS SDK Go dependency.

### CODE REVIEW

**Comment by hekonsek** [comment]
Can we try to resurrect this one? :)

**Comment by hekonsek** [comment]
Is this false negative by any chance? Can we try to rerun it or somehow see what build error is?

**Comment by rawlingsj** [comment]
> Is this false negative by any chance? Can we try to rerun it or somehow see what build error is?

yeah - wonder if you don't mind rebasing or closing this PR and opening a new one?  That `serverless jenkins` context is old now as we've moved this repo to tekton

**Comment by rawlingsj** [comment]
while we move releases to new infra
/hold

**Comment by rawlingsj** [comment]
> yeah - wonder if you don't mind rebasing or closing this PR and opening a new one? That serverless jenkins context is old now as we've moved this repo to tekton 

ignore above comment as I can override the context
/override serverless-jenkins

**Pull request merged**
