### PR TITLE
fix: exit with a diff in pipeline

### LINKED ISSUE #5120: `step-verify-env` failing when running jx boot in cluster for the dev environment pipeline
When running a master pipeline build for the dev environment, running `jx boot` we get the following error:

```
Showing logs for build jenkins-x/environment-tekton-weasel-dev/master #7 promotion stage release and container step-verify-env
validating git repository for dev at URL https://github.com/jenkins-x/environment-tekton-weasel-dev.git
creating environment dev git repository for URL: https://github.com/jenkins-x/environment-tekton-weasel-dev.git to namespace jx
Attempting to cherry pick commits that were on master but not yet pushed
WARNING: Unable to cherry-pick 732a22214778d5cec1509442cc8559a0e320f7f2: git output: error: could not apply 732a222... release 0.0.7
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit': failed to run 'git cherry-pick 732a22214778d5cec1509442cc8559a0e320f7f2' command in directory '/workspace/source', output: 'error: could not apply 732a222... release 0.0.7
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit''

error: creating dev environment for environment-tekton-weasel-dev: forking and pulling https://github.com/jenkins-x/environment-tekton-weasel-dev.git: git output: error: Merging is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.: failed to run 'git merge origin/master' command in directory '/workspace/source', output: 'error: Merging is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.'
Showing logs for build jenkins-x/environment-tekton-weasel-dev/master #7 promotion stage release and container step-log-repos
Showing logs for build jenkins-x/environment-tekton-weasel-dev/master #7 promotion stage release and container step-apply-repositories
Showing logs for build jenkins-x/environment-tekton-weasel-dev/master #7 promotion stage release and container step-apply-pipeline-schedulers
Showing logs for build jenkins-x/environment-tekton-weasel-dev/master #7 promotion stage release and container step-update-webhooks
Showing logs for build jenkins-x/environment-tekton-weasel-dev/master #7 promotion stage release and container step-verify-install
```

### PR DESCRIPTION
**Pull request by pmuir**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description
This fixes jx step verify environments to not create a PR in a pipeline but instead run git diff and error if there is a diff

#### Which issue this PR fixes

fixes #5120

### CODE REVIEW

**Comment by abayer** [comment]
Ok, I'm now convinced there's something wrong with `cmd/controller/pipeline/pipelinerunner_controller_test` - it's failing with eerie consistency here. But I can't see how that would be happening due to changes here, and it's passing for me on master...

**Comment by abayer** [comment]
@hferentschik - any ideas?

**Comment by pmuir** [comment]
Error `0x6f` is connection refused (`ECONNREFUSED`) which makes me strongly suspect that there is not a http server listening on the `server:port` at the point in time the connection is attempted. This means either the server is failing to start, not started in time, or already shutdown. I  doubt it's already shutdown, so it's either failing to start or not started in time. We need to increase the logigng to find out.

**Comment by pmuir** [comment]
Also it's notable that it binds to `0.0.0.0` but looks for ports and performs requests against `127.0.0.1` which feels like a typo.

**Comment by pmuir** [comment]
We're also completely dropping the error if the http server fails to `ListenAndServe` - it's definitely worth logging it at some level.

**Comment by pmuir** [comment]
Ok, we are explicitly disabling log output in this test. This is hiding a whole raft of errors!

**Comment by pmuir** [comment]
Yeah, looking at the log output, I would say it's just chance it runs properly locally (caused by the fact the timings work - only the first test actually succeeds in starting a server)

**Comment by pmuir** [comment]
Ok, that looks spurious - it's just the server being closed.

**Comment by pmuir** [comment]
Ok, enabled logging in that test

**Pull request closed without merging**
