### PR TITLE
Add IBM Cloud Private as a provider

### PR DESCRIPTION
**Pull request by a-roberts**
This relies on the cloud-environment PR being released too. Tested on IBM Cloud Private 3.1, all x86-64 architecture. First release and with plenty of room for improvements!

Goes with https://github.com/jenkins-x/cloud-environments/pull/202.

I've also added some statements I found useful when debugging to do with RBAC, and a todo method for adding a cluster role through jx which may prove useful to somebody as well (I originally planned to create a cluster role for the created service account to use, so I don't need to use a tiller namespace "default" which gets cluster-admin privileges on ICP).

Here is an example (I've added some colour text as well for the headers).
```
adams-mbp:jx aroberts$ build/jx install --provider=icp
Using helmBinary helm with feature flag: none
Storing the kubernetes provider icp in the TeamSettings
Updated the team settings in namespace jx
Git configured for user: a-roberts and email aroberts@uk.ibm.com

IBM Cloud Private installation of Jenkins X
Configuring Jenkins X options for IBM Cloud Private: ensure your Kubernetes context is already configured to point tothe cluster jx will be installed into.

Permitting image repositories to be used
If you have a clusterimagepolicy, ensure that this policy permits pulling from the following additional repositories:the scope of which can be narrowed down once you are sure only images from certain repositories are being used:
- name: docker.io/*
- name: gcr.io/*
- name: quay.io/*
- name: k8s.gcr.io/*
- name: <your ICP cluster name>:8500/*

IBM Cloud Private defaults
By default, with IBM Cloud Private the Tiller namespace for jx will be "default" and the namespace where Jenkins X resources will be installed into is "jx".

Using the IBM Cloud Private Docker registry
To use the IBM Cloud Private Docker registry, when environments (namespaces) are created, create a Docker registry secret and patch the default service account in the created namespace to use the secret, adding it as an ImagePullSecret. This is required so that pods in the created namespace can pull images from the registry.

? Provide the external IP Jenkins X should use: typically your IBM Cloud Private proxy node IP address 
9.20.201.31
? Provide the domain Jenkins X should be available at: typically your IBM Cloud Private proxy node IP address but with? Provide the domain Jenkins X should be available at: typically your IBM Cloud Private proxy node IP address but with a domain added to the end 
9.20.201.31.nip.io
Using helm2
Configuring tiller
Tiller Deployment is running in namespace default
existing ingress controller found, no need to install a new one
Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
Using external IP: 9.20.201.31
nginx ingress controller installed and configured
Lets set up a Git username and API token to be able to perform CI/CD

? Do you wish to use a-roberts as the GitHub username for CI/CD pipelines: Yes
Current configuration dir: /Users/aroberts/.jx
options.Flags.CloudEnvRepository: https://github.com/a-roberts/cloud-environments
options.Flags.LocalCloudEnvironment: false
Cloning the Jenkins X cloud environments repo to /Users/aroberts/.jx/cloud-environments
? A local Jenkins X cloud environments repository already exists, recreate with latest? Yes
Current configuration dir: /Users/aroberts/.jx
options.Flags.CloudEnvRepository: https://github.com/a-roberts/cloud-environments
options.Flags.LocalCloudEnvironment: false
Cloning the Jenkins X cloud environments repo to /Users/aroberts/.jx/cloud-environments
Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Compressing objects: 100% (8/8), done.
Total 946 (delta 1), reused 0 (delta 0), pack-reused 938
Generated helm values /Users/aroberts/.jx/extraValues.yaml
Installing Jenkins X platform helm chart from: /Users/aroberts/.jx/cloud-environments/env-icp
Installing jx into namespace jx
Waiting for tiller pod to be ready, service account name is tiller, namespace is jx, tiller namespace is default
Waiting for cluster role binding to be defined, named tiller-role-binding in namespace jx
 tiller cluster role defined: cluster-admin in namespace jx
tiller pod running
waiting for install to be ready, if this is the first time then it will take a while to download images
Jenkins X deployments ready in namespace jx


        ********************************************************

             NOTE: Your admin password is: frilltar

        ********************************************************


Getting Jenkins API Token
Using url http://jenkins.jx.9.20.201.31.nip.io/me/configure
Unable to automatically find API token with chromedp using URL http://jenkins.jx.9.20.201.31.nip.io/me/configure
Error: creating the chrome client: timeout waiting for initial target
Please go to http://jenkins.jx.9.20.201.31.nip.io/me/configure and click Show API Token to get your API Token
Then COPY the token and enter in into the form below:

? API Token:
```

### CODE REVIEW

**Comment by ccojocar** [comment]
@a-roberts Please could you run `make test-slow-integration`? There is a test which is failing: 

```
# github.com/jenkins-x/jx/pkg/jx/cmd
pkg/jx/cmd/common_kube_rbac.go:48: Infof format %s reads arg #2, but call has 1 arg
ok  	github.com/jenkins-x/jx/pkg/gits	64.963s	coverage: 22.3% of statements
?   	github.com/jenkins-x/jx/pkg/gits/mocks	[no test files]
ok  	github.com/jenkins-x/jx/pkg/helm	0.987s	coverage: 34.5% of statements
?   	github.com/jenkins-x/jx/pkg/helm/mocks	[no test files]
?   	github.com/jenkins-x/jx/pkg/issues	[no test files]
?   	github.com/jenkins-x/jx/pkg/jenkins	[no test files]
FAIL	github.com/jenkins-x/jx/pkg/jx/cmd [build failed]
?   	github.com/jenkins-x/jx/pkg/jx/cmd/certmanager	[no test files]
?   	github.com/jenkins-x/jx/pkg/jx/cmd/mocks	[no test files]
?   	github.com/jenkins-x/jx/pkg/jx/cmd/mocks/matchers	[no test files]
?   	github.com/jenkins-x/jx/pkg/jx/cmd/templates	[no test files]
ok  	github.com/jenkins-x/jx/pkg/kube	0.520s	coverage: 28.0% of statements
?   	github.com/jenkins-x/jx/pkg/log	[no test files]
?   	github.com/jenkins-x/jx/pkg/maven	[no test files]
?   	github.com/jenkins-x/jx/pkg/nodes	[no test files]
?   	github.com/jenkins-x/jx/pkg/pipeline_events	[no test files]
ok  	github.com/jenkins-x/jx/pkg/prow	0.601s	coverage: 87.4% of statements
ok  	github.com/jenkins-x/jx/pkg/quickstarts	0.669s	coverage: 18.4% of statements
ok  	github.com/jenkins-x/jx/pkg/reports	0.099s	coverage: 39.7% of statements
?   	github.com/jenkins-x/jx/pkg/spring	[no test files]
?   	github.com/jenkins-x/jx/pkg/table	[no test files]
?   	github.com/jenkins-x/jx/pkg/terraform	[no test files]
?   	github.com/jenkins-x/jx/pkg/testkube	[no test files]
?   	github.com/jenkins-x/jx/pkg/tests	[no test files]
ok  	github.com/jenkins-x/jx/pkg/util	1.365s	coverage: 21.0% of statements
?   	github.com/jenkins-x/jx/pkg/util/mocks	[no test files]
ok  	github.com/jenkins-x/jx/pkg/version	0.115s	coverage: 40.0% of statements
?   	github.com/jenkins-x/jx/pkg/workflow	[no test files]
Makefile:94: recipe for target 'test-slow-integration' failed
make: *** [test-slow-integration] Error 2```

**Comment by a-roberts** [comment]
Thanks for the quick review and plenty of attention! Yes, running that now on my local system

**Pull request merged**
