### PR TITLE
fix: handle correctly ctrl+c on confirmation

### LINKED ISSUE #3291: Ctrl-C in jx init doesn't stop the application
### Summary 
When running `jx init`, on the very first step where you select your Cloud Provider, the Ctrl-C keystroke doesn't quit the program. Instead, it proceeds to the next step. But a second Ctrl-C will stop the program.

### Steps to reproduce the behavior

1. Run `jx init`

2. At the very first question where you're asked for your Cloud Provider, hit `Ctrl-C`.

### Expected behavior
The program should exit.

### Actual behavior
The program continues.
image

### Jx version

The output of `jx version` is:

```
15:30 $ jx version
Failed to find helm installs: failed to run 'helm list' command in directory '', output: 'Error: incompatible versions client[v2.13.0] server[v2.12.3]'
NAME               VERSION
jx                 1.3.953-dev+0565d1a79
Kubernetes cluster v1.11.7-gke.4
kubectl            v1.13.3
helm client        v2.13.0+g79d0794
helm server        v2.12.3+geecf22f
git                git version 2.19.1
Operating System   Ubuntu 18.10

```

### Jenkins type
- [ ] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster
GKE cluster, created via `jx create cluster gke --tekton -n name-of-cluster`

### Operating system / Environment
```
✔ ~/GitHub/jx [master ↓·2|⚑ 1] 
15:31 $ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10
DISTRIB_CODENAME=cosmic
DISTRIB_DESCRIPTION="Ubuntu 18.10"
✔ ~/GitHub/jx [master ↓·2|⚑ 1] 
15:31 $ go version
go version go1.11.4 linux/amd64
```

### LINKED ISSUE #5627: Hitting ctrl-c at the "cancel pipeline ... ?" prompt on `jx stop pipeline`...stops the pipeline.
Responding with `n` works as expected, but I sure would assume that ctrl-c would just cancel, not act the same as if you'd hit enter (to confirm the default of `Y`) or responded with `y`. =)

### PR DESCRIPTION
**Pull request by aure-olli**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

Prior to this commit, while a confirmation was required, `ctrl+c` would confirm the default value instead of stopping the program.
This could have the unintended purpose of confirming that a pipeline should be stopped instead of cancelling the operation.

#### Special notes for the reviewer(s)

On issue #5627 the answer was that it wasn't due to `jx` but the the library it's using. But `jx` ignores the error from the library: https://github.com/jenkins-x/jx/blob/master/pkg/util/pickers.go#L170

#### Which issue this PR fixes

fixes #5627, fixes #3291

### CODE REVIEW

**Comment by abayer** [comment]
/ok-to-test

This makes me very happy. =)

**Comment by abayer** [comment]
I do expect some lint errors on unused `answer` variables, FYI.

**Comment by abayer** [comment]
@aure-olli Yup, and some formatting as well. Want me to fix them for you?

**Comment by abayer** [comment]
@aure-olli I couldn't push to your branch, but https://github.com/abayer/jx/commit/c93d525fe753c1c34b49ef44f1c49ea63aa4ad11 has the formatting changes needed. I didn't seem to get any other lint errors when I ran locally.

**Comment by abayer** [comment]
Integration test failure is
```
=== FAIL: pkg/cmd/step/verify TestStepVerifyRequirements (0.06s)
=== PAUSE TestStepVerifyRequirements
=== CONT  TestStepVerifyRequirements
    step_verify_requirements_integration_test.go:48: 
        	Error Trace:	step_verify_requirements_integration_test.go:48
        	Error:      	Received unexpected error:
        	            	remote not found
        	            	failed to clone reference: refs/heads/master
        	            	github.com/jenkins-x/**/pkg/versionstream/versionstreamrepo.clone
        	            		/workspace/source/pkg/versionstream/versionstreamrepo/gitrepo.go:209
        	            	github.com/jenkins-x/**/pkg/versionstream/versionstreamrepo.deleteAndReClone
        	            		/workspace/source/pkg/versionstream/versionstreamrepo/gitrepo.go:151
        	            	github.com/jenkins-x/**/pkg/versionstream/versionstreamrepo.cloneJXVersionsRepo
        	            		/workspace/source/pkg/versionstream/versionstreamrepo/gitrepo.go:134
        	            	github.com/jenkins-x/**/pkg/versionstream/versionstreamrepo.CloneJXVersionsRepo
        	            		/workspace/source/pkg/versionstream/versionstreamrepo/gitrepo.go:23
        	            	github.com/jenkins-x/**/pkg/cmd/opts.(*CommonOptions).CloneJXVersionsRepo
        	            		/workspace/source/pkg/cmd/opts/version.go:150
        	            	github.com/jenkins-x/**/pkg/cmd/opts.(*CommonOptions).CreateVersionResolver
        	            		/workspace/source/pkg/cmd/opts/version.go:18
        	            	github.com/jenkins-x/**/pkg/cmd/step/verify.(*StepVerifyRequirementsOptions).Run
        	            		/workspace/source/pkg/cmd/step/verify/step_verify_requirements.go:93
        	            	github.com/jenkins-x/**/pkg/cmd/step/verify_test.TestStepVerifyRequirements
        	            		/workspace/source/pkg/cmd/step/verify/step_verify_requirements_integration_test.go:47
        	            	testing.tRunner
        	            		/usr/local/go/src/testing/testing.go:865
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1337
        	            	github.com/jenkins-x/**/pkg/versionstream/versionstreamrepo.cloneJXVersionsRepo
        	            		/workspace/source/pkg/versionstream/versionstreamrepo/gitrepo.go:136
        	            	github.com/jenkins-x/**/pkg/versionstream/versionstreamrepo.CloneJXVersionsRepo
        	            		/workspace/source/pkg/versionstream/versionstreamrepo/gitrepo.go:23
```

Not sure if that or the `boot-vault` failure is transient - I'm rerunning both of them.

**Comment by aure-olli** [comment]
Hi
Sorry I always forget `make fmt` :/ fixed and merged, this should be ok.

**Pull request merged**
