### PR TITLE
pkg/jx/cmd/{init.go,install.go},pkg/util/find_ips.go: Support for non-cloud LB

### PR DESCRIPTION
**Pull request by maniankara**
Support for non-cloud Loadbalancer (metallb)

1. Introduced InhouseProvider for non-public clouds
find_ips:
2. Generates range of (3) free IPs available from the current network (optional)
3. Does also validation of IPs provided by user

Fixes: #534 atleast

### CODE REVIEW

**Comment by maniankara** [comment]
This is how user feels when running from cli
Scenario1: When user chooses the default provided by `jx`
```
$ build/jx install --provider kubernetes
Tiller Deployment is running in namespace kube-system
Already up-to-date.
? No existing ingress controller found in the kube-system namespace, shall we install one? Yes
? Available IP range to use  [Use arrows to move, type to filter, ? for more help]
  192.168.10.36-192.168.10.38
  10.8.0.174-10.8.0.176
❯ other
? Please provide ip range (3 ips): (format: 192.168.10.36-192.168.10.38)
ingress init failed: interrupt
error: interrupt
$ 
```
Scenario2: When user chooses to provide ip range explicitly `jx`
```
$ build/jx install --provider kubernetes
Tiller Deployment is running in namespace kube-system
Already up-to-date.
? No existing ingress controller found in the kube-system namespace, shall we install one? Yes
? Available IP range to use other
? Please provide ip range (3 ips): (format: 192.168.10.36-192.168.10.38) 192.168.20.136-192.168.20.138
```
Currently this fails with this command, as I need help with this (how to update charmuseum?)
`helm install --name metallb jenkins-x/metallb --namespace kube-system --set rbac.create=true`

**Comment by maniankara** [comment]
Need help updating jenkins chat museum so that `helm install --name metallb jenkins-x/metallb --namespace kube-system --set rbac.create=true` will get through.

**Comment by isaron** [comment]
Need this feature: non-cloud Loadbalancer. Please merge this PR. thx!

**Comment by ccojocar** [comment]
@maniankara It would be great if you could rebase this PR and resolve the conflicts? Which issues are still pending? Thanks

**Comment by ccojocar** [comment]
@maniankara Do you still have time to complete this PR? It would be great, if it could get merged. Thanks

**Comment by rawlingsj** [comment]
Closing as it's gone stale

**Pull request closed without merging**
