### PR TITLE
fix(tekton): Clone before getting GitInfo in step create task

### LINKED ISSUE #4478: step create task tries to determine GitInfo from non existent directory
In the current version of _step_create_task_, the GitInfo struct is determined by calling `FindGitInfo(o.CloneDir)`. However, this call is made prior to `CloneDir` being set.

A better option is to get the GitInfo from the info from the passed source URL.

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

Metapipeline fun - if we don't clone first, we end up with no repo, which unsurprisingly is bad when we try to get the `GitInfo`. If the repo's already cloned (as will be the case when we switch over to `jx
step create pipeline`), we don't need to clone here, but for now...

I've tested this by hand after reproducing the original issue by hand, and it works, so yay. This sort of thing will get caught automatically once #4301 lands.

#### Special notes for the reviewer(s)

/assign @dwnusbaum 
/assign @hferentschik 

#### Which issue this PR fixes

fixes #4478

### CODE REVIEW

**Comment by dwnusbaum** [comment]
Ah ok nvm, didn't read the description fully, looks like https://github.com/jenkins-x/jx/pull/4301 would test this behavior.

/lgtm

**Comment by hferentschik** [comment]
Ahh, thanks. I was surprised the issue was already closed this morning. I had initially tried to make the clone URL obligatory and align more with step_create_metapipeline. That worked fine and it solved the use case of being called from the pipeline runner. However, I then realized that this probably won't work with the interpreted mode. 

I saw issue #4314, and I agree that it would be much better if for the interpreted mode we not reuse the step_create_task command. I'd rather have the boot code create an (effective) pipeline directly and then add some capability to the pipeline to execute locally or generate a script.

**Comment by abayer** [comment]
Yeah, we should probably pivot to dealing with #4314 sooner than later.

**Pull request merged**
