### PR TITLE
chore: remove deprecated workflow controller

### PR DESCRIPTION
**Pull request by mrageh**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

The `controller workflow` command is now deprecated, we announced that it would be removed in [this PR](https://github.com/jenkins-x/jx/pull/6175).

### CODE REVIEW

**Comment by hferentschik** [comment]
@mrageh the unit test failures seem legit. Looks like you might have removed too much?

**Comment by hferentschik** [comment]
Not so sure about this one. TBH, I am not quite sure what this controller is supposed to do. @abayer, @daveconde  do you know? Was this not related to multi-cluster? 

Also, I would expect since this is a controller there is more to clean up than the code in the `jx` repo. Somewhere we probably have a Helm Chart of sorts which deploys this controller, right?

**Comment by hferentschik** [comment]
```
# github.com/jenkins-x/**/pkg/cmd/controller [github.com/jenkins-x/**/pkg/cmd/controller.test]
pkg/cmd/controller/controller_build_test.go:36:13: undefined: DigitSuffix
ok  	github.com/jenkins-x/**/pkg/cmd/config	0.131s
FAIL	github.com/jenkins-x/**/pkg/cmd/controller [build failed]
ok  	github.com/jenkins-x/**/pkg/cmd/controller/pipeline	0.099s
ok  	github.com/jenkins-x/**/pkg/cmd/create	0.128s
?   	github.com/jenkins-x/**/pkg/cmd/create/options	[no test files]
?   	github.com/jenkins-x/**/pkg/cmd/create/vault	[no test files]
ok  	github.com/jenkins-x/**/pkg/cmd/deletecmd	0.516s
?   	github.com/jenkins-x/**/pkg/cmd/deprecation	[no test files]
?   	github.com/jenkins-x/**/pkg/cmd/edit	[no test files]
ok  	github.com/jenkins-x/**/pkg/cmd/edit/requirements	0.184s
?   	github.com/jenkins-x/**/pkg/cmd/experimental	[no test files]
ok  	github.com/jenkins-x/**/pkg/cmd/gc	0.084s
ok  	github.com/jenkins-x/**/pkg/cmd/get	0.508s
?   	github.com/jenkins-x/**/pkg/cmd/helper	[no test files]
ok  	github.com/jenkins-x/**/pkg/cmd/importcmd	0.102s
?   	github.com/jenkins-x/**/pkg/cmd/initcmd	[no test files]
ok  	github.com/jenkins-x/**/pkg/cmd/namespace	0.089s
ok  	github.com/jenkins-x/**/pkg/cmd/opts	0.184s
?   	github.com/jenkins-x/**/pkg/cmd/opts/step	[no test files]
?   	github.com/jenkins-x/**/pkg/cmd/opts/upgrade	[no test files]
# github.com/jenkins-x/**/pkg/cmd/promote_test [github.com/jenkins-x/**/pkg/cmd/promote.test]
pkg/cmd/promote/promote_test.go:488:19: undefined: controller.ControllerWorkflowOptions
```

@mrageh ^^

**Comment by hferentschik** [comment]
@mrageh what's your plan with this PR?

**Comment by mrageh** [comment]
We'll be removing everything to do with workflows in another PR. Closing this for now

**Pull request closed without merging**
