### PR TITLE
Implements API mocking in Bitbucket tests, includes some test data 

### PR DESCRIPTION
**Pull request by wbrefvem**

### CODE REVIEW

**Comment by jstrachan** [comment]
TW @wbrefvem can you see the CI failure build above? Not sure if unauthenticated views are supported right now (we need to fix that...).

whoah never seen this error before...
```
+ make test

CGO_ENABLED=0 GO15VENDOREXPERIMENT=1 go test github.com/jenkins-x/jx github.com/jenkins-x/jx/cmd/jx github.com/jenkins-x/jx/cmd/jx/app github.com/jenkins-x/jx/pkg/addon github.com/jenkins-x/jx/pkg/apis/jenkins.io github.com/jenkins-x/jx/pkg/apis/jenkins.io/v1 github.com/jenkins-x/jx/pkg/auth github.com/jenkins-x/jx/pkg/client/clientset/versioned github.com/jenkins-x/jx/pkg/client/clientset/versioned/fake github.com/jenkins-x/jx/pkg/client/clientset/versioned/scheme github.com/jenkins-x/jx/pkg/client/clientset/versioned/typed/jenkins.io/v1 github.com/jenkins-x/jx/pkg/client/clientset/versioned/typed/jenkins.io/v1/fake github.com/jenkins-x/jx/pkg/client/informers/externalversions github.com/jenkins-x/jx/pkg/client/informers/externalversions/internalinterfaces github.com/jenkins-x/jx/pkg/client/informers/externalversions/jenkins.io github.com/jenkins-x/jx/pkg/client/informers/externalversions/jenkins.io/v1 github.com/jenkins-x/jx/pkg/client/listers/jenkins.io/v1 github.com/jenkins-x/jx/pkg/config github.com/jenkins-x/jx/pkg/draft github.com/jenkins-x/jx/pkg/gits github.com/jenkins-x/jx/pkg/helm github.com/jenkins-x/jx/pkg/issues github.com/jenkins-x/jx/pkg/jenkins github.com/jenkins-x/jx/pkg/jx/cmd github.com/jenkins-x/jx/pkg/jx/cmd/aks github.com/jenkins-x/jx/pkg/jx/cmd/gke github.com/jenkins-x/jx/pkg/jx/cmd/log github.com/jenkins-x/jx/pkg/jx/cmd/table github.com/jenkins-x/jx/pkg/jx/cmd/templates github.com/jenkins-x/jx/pkg/jx/cmd/util github.com/jenkins-x/jx/pkg/kube github.com/jenkins-x/jx/pkg/maven github.com/jenkins-x/jx/pkg/nodes github.com/jenkins-x/jx/pkg/quickstarts github.com/jenkins-x/jx/pkg/spring github.com/jenkins-x/jx/pkg/util github.com/jenkins-x/jx/pkg/version -test.v

?   	github.com/jenkins-x/jx	[no test files]

go build github.com/jenkins-x/jx/cmd/jx: /usr/local/go/pkg/tool/linux_amd64/link: signal: killed

make: *** [test] Error 1

script returned exit code 2
```

**Comment by wbrefvem** [comment]
@jstrachan No, I can't see anything but a Jenkins login screen.

**Comment by wbrefvem** [comment]
btw, was this an out of memory thing?

**Comment by jstrachan** [comment]
looks to have been temporary - rerunning the CI pipeline worked ;)

**Pull request merged**
