### PR TITLE
feat: add more reporting to ImportReporter

### LINKED ISSUE #7017: importcmd.ImportReporter should report state of import
ImportReporter methods currently only cover quickstart creation. 

ImportReporter should (at the least) cover

* Cloned repo
* Created Draft - and report back which one was used.
* Pushed updated repo

### PR DESCRIPTION
**Pull request by imeredith**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

Adds more reporting to importcmd.ImportReporter

#### Which issue this PR fixes

fixes #7017

### CODE REVIEW

**Comment by hferentschik** [comment]
@imeredith, would you mind opening an issue as well?

**Comment by hferentschik** [comment]
@imeredith another nitpick, but could you squash the two commits into a single one?

**Comment by imeredith** [comment]
Fixes #7017

**Pull request merged**
