### PR TITLE
fix(pipeline): introducing ListSelectedPipelineActivities to select by label and field

### LINKED ISSUE #5539: Wrong field selector for gitOwner in PipelineActivity
As part of issue #5515 the sourcerepository label got removed from PipelineActivity and replaced by field selectors. The specified selectors specify a wrong property path.

`metadata.spec.gitOwner` should just be `spec.gitOwner`

Error log:

```
{"branch":"PR-1","component":"pipelinerunner","context":"promotion-build","level":"info","meta":false,"msg":"triggering pipeline","revision":"6b965622c0ac650f717a3c6da239a828a8736a03","sourceURL":"https://github.com/jenkins-x-bot-test/environment-pr-512-32-boot-local-staging.git","time":"2019-09-19T12:22:20Z"}
{"level":"info","msg":"Deleting and cloning the Jenkins X versions repo","time":"2019-09-19T12:22:21Z"}
{"level":"info","msg":"Cloning the Jenkins X versions repo https://github.com/jenkins-x/jenkins-x-versions.git with revision f49da5ff40a3bbb40437c8adb86469227c5b1c9d to /root/.jx/jenkins-x-versions","time":"2019-09-19T12:22:21Z"}
From https://github.com/jenkins-x/jenkins-x-versions
 * branch            f49da5ff40a3bbb40437c8adb86469227c5b1c9d -> FETCH_HEAD
{"level":"info","msg":"shallow cloning repository https://github.com/jenkins-x-bot-test/environment-pr-512-32-boot-local-staging.git to temp dir /tmp/git079608617","time":"2019-09-19T12:22:24Z"}
{"level":"info","msg":"Merged SHA 6b965622c0ac650f717a3c6da239a828a8736a03 with commit message 'chore: Promote bdd-spring-1568895506 to version 0.0.1' into base branch master","time":"2019-09-19T12:22:27Z"}
{"level":"info","msg":"selected pack: /root/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/environment","time":"2019-09-19T12:22:29Z"}
{"level":"info","msg":"PipelineActivity for jenkins-x-bot-test-environment-pr-512-32-boot-local-staging-PR-1-2","time":"2019-09-19T12:22:31Z"}
{"level":"info","msg":"Applying changes ","time":"2019-09-19T12:22:31Z"}
{"level":"info","msg":"Checking if batch build reconciling is needed","time":"2019-09-19T12:22:32Z"}
{"level":"info","msg":"removing the temp directory /tmp/git079608617","time":"2019-09-19T12:22:32Z"}
{"component":"pipelinerunner","level":"info","msg":"error triggering the pipeline run: failed to apply Tekton CRDs: there was a problem reconciling batch build data: there was a problem listing all activities to reconcile a batch build: field label not supported: metadata.spec.gitOwner could not start pipeline: error triggering the pipeline run: failed to apply Tekton CRDs: there was a problem reconciling batch build data: there was a problem listing all activities to reconcile a batch build: field label not supported: metadata.spec.gitOwner","time":"2019-09-19T12:22:32Z"}
```

### PR DESCRIPTION
**Pull request by hferentschik**
fixes #5539

### CODE REVIEW

**Comment by hferentschik** [comment]
This will need a bit more doing. Turns out there is a limitation/bug on field selection on custom CRDs- https://github.com/jenkins-x/jx/issues/5539#issuecomment-533184099

**Comment by hferentschik** [comment]
New plan - https://github.com/jenkins-x/jx/issues/5539#issuecomment-533189589

**Comment by hferentschik** [comment]
@abayer I needed to push another update to a test. Need another lgtm

**Comment by abayer** [comment]
@hferentschik Test failure looks legit.

**Pull request merged**
