### PR TITLE
jx promote fails outside of a git working copy

### PR DESCRIPTION
**Pull request by carlossg**
`error: PromoteStepActivityKey was not valid`

In a git working dir (any git, not necessarily the same project we are promoting)

```
$ jx promote croc-hunter-jenkinsx --version 0.0.16 --env production
prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/jx/issues/2410
Promoting app croc-hunter-jenkinsx version 0.0.16 to namespace jx-production
No $BUILD_NUMBER environment variable found so cannot record promotion activities into the PipelineActivity resources in kubernetes
No changes made to the GitOps Environment source code. Code must be up to date!
```

Outside a git working copy

```
$ jx promote croc-hunter-jenkinsx --version 0.0.16 --env production
prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/jx/issues/2410
Promoting app croc-hunter-jenkinsx version 0.0.16 to namespace jx-production
Could not discover the Git repository info failed to parse Git URL  due to Invalid path  could not determine organisation and repository name
failed to get the git branch name in dir .
No $JOB_NAME environment variable found so cannot record promotion activities into the PipelineActivity resources in kubernetes
No changes made to the GitOps Environment source code. Code must be up to date!
Failed to update PipelineActivity: PromoteStepActivityKey was not valid
error: PromoteStepActivityKey was not valid
```

#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by carlossg** [comment]
Change introduced in https://github.com/jenkins-x/jx/pull/2716/files#diff-c4609832bc0758dac9fdf2a6df17d12aR451 by @mikecirioli 

If `jx promote` is ran in a git clone it will populate the `pipeline` using the git clone data, so if you are in another project git clone it will use that git project name, but it will succeed promoting anyway because that data is not used anyway.
https://github.com/jenkins-x/jx/blob/feceb56/pkg/jx/cmd/promote.go#L818

If it is not ran in a git clone it will set `pipeline=""` and fail the `isValid` check

IMHO the git data is not needed for `jx promote` as we are passing the application name, version and environment

**Comment by rawlingsj** [comment]
@carlossg hope you dont mind I'm going to force push to your branch to rebase.

**Comment by rawlingsj** [comment]
@carlossg sorry about the noise on this PR - I'm using it to test some triggers
/test lint

**Comment by garethjevans** [comment]
@rawlingsj this PR might need rebasing as I don't think its picking up the latest changes from master

**Comment by garethjevans** [comment]
or we could override the lint context to get around it?

**Comment by rawlingsj** [comment]
@garethjevans I rebased it last night, there's an issue with pipelinerunner so I'm using this PR as a test to trigger

**Comment by rawlingsj** [comment]
yay - all sorted!

**Pull request merged**
