### PR TITLE
fix: do not force external dns on GKE cluster with custom domain

### PR DESCRIPTION
**Pull request by aure-olli**
Resolves: https://github.com/jenkins-x/jx/issues/6128

Prior to this commit, `jx step ceate install values` forced external dns when detecting a GKE cluster with a custom domain.
This behavior could not be prevented by the user, and would lead to a failure if the service account did not have sufficient rights to configure the external dns.

Signed-off-by: Aurélien Lambert <aure@olli-ai.com>

#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

Prior to this commit, `jx step ceate install values` forced external dns when detecting a GKE cluster with a custom domain.
This behavior could not be prevented by the user, and would lead to a failure if the service account did not have sufficient rights to configure the external dns.

#### Which issue this PR fixes

fixes https://github.com/jenkins-x/jx/issues/6128

### CODE REVIEW

**Comment by aure-olli** [comment]
It's at least working in my case:
```
waiting for stage release : container step-create-install-values to start...

Showing logs for build olli-ai/environment-***-dev/master #31 promotion stage release and container step-create-install-values
using a custom domain and GKE, you can enable external dns and TLS

waiting for stage release : container step-install-external-dns to start...
```

**Comment by abayer** [comment]
/hold
holding briefly to avoid batch hell

**Pull request merged**
