### PR TITLE
fix: Removing duplicate jx chart

### LINKED ISSUE #5721: Duplicate presence of Charts.yaml
### Summary 
charts.yaml is present in jx/charts/jx and root.

### PR DESCRIPTION
**Pull request by nehagup**
Signed-off-by: neha gupta <gneha21@yahoo.in>

fixes #5721

### CODE REVIEW

**Comment by hferentschik** [comment]
@nehagup, thanks for the pull request. I agree this having to _Chart.yaml_. If possible I would also just like to have one.

That said, I somehow seem to recall that both files are actually used. I am not sure whether we can just delete it. It might not fail directly within `jx`, but there are several downstream repositories which need to get build as well.

@abayer, @pmuir - do you know where this _Chart.yaml_ is potentially used.

**Comment by hferentschik** [comment]
@ccojocar do you know whether _Chart.yaml_ is needed?

**Comment by ccojocar** [comment]
I am not sure where it is used, but if you check the `templates` folder there is only a Release CRD and a service. The release CRD contains a really old version of jx. 

I suppose that also the `templates` folder needs to be remove since it belongs to the Chart file defined in the root directory.

**Comment by hferentschik** [comment]
@nehagup, could you update the PR and also delete the template directory?

**Comment by nehagup** [comment]
@hferentschik  can we also remove values.yaml since we're removing charts.yaml from the root?

**Comment by hferentschik** [comment]
@nehagup, how it is going? Just wondering whether you need a hand getting this ready to be merged?

**Comment by nehagup** [comment]
hey @hferentschik apologies I couldn't catch up(was travelling). I'm working on this actively now.

**Comment by MarckK** [comment]
This looks great, @nehagup!  🎉
@hferentschik is off on PTO; let's ask @pmuir, @daveconde, @abayer for a review.

**Comment by nehagup** [comment]
Thank you all for the support. :)

**Pull request merged**
