### PR TITLE
Update the help & example with --git-api-token

### PR DESCRIPTION
**Pull request by abouchama**
Update the help & example with --git-api-token rather than --git-token
--git-token doesn't exist

### CODE REVIEW

**Comment by jstrachan** [comment]
@abouchama many thanks!

**Comment by rawlingsj** [comment]
yay - thanks @abouchama - good to see your PRs!

**Comment by abouchama** [comment]
Congrats Guys @jstrachan & @rawlingsj for this awesome & genius CI/CD platform, i'm honored to contribute ;-)

**Comment by jstrachan** [comment]
@abouchama you're most welcome!

**Pull request merged**
