### PR TITLE
fix: ensure the CommonOptions is set on setp next version and helm version

### PR DESCRIPTION
**Pull request by ccojocar**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

part of #1016
fixes #

### CODE REVIEW

**Comment by pmuir** [comment]
Looks like generation needs to be rerun

**Comment by jstrachan** [comment]
@ccojocar I wonder if you could rebase? we had some proxy/code generation/formatting issues fixed yesterday?

**Pull request merged**
