### PR TITLE
fix: skip the version tagging in the create task when the noReleasePrepare flag is configured in the project

### LINKED ISSUE #6804: Release tagging cannot be disabled using noReleasePrepare config flag
### Summary 

According to the documentation, there is an option to disable the release tagging in the meta-pipeline before running a release pipeline. See for details: https://jenkins-x.io/docs/reference/config/config/#config.jenkins.io/v1.PipelineConfig.

On a quick look, the meta-pipeline doesn't seem to honour this flag see:
https://github.com/jenkins-x/jx/blob/cbce4a77e72d5e57eb5b309cf0eb49c9df22c57c/pkg/tekton/metapipeline/client.go#L43

and 

https://github.com/jenkins-x/jx/blob/cbce4a77e72d5e57eb5b309cf0eb49c9df22c57c/pkg/cmd/controller/pipeline/pipelinerunner_controller.go#L322

### Steps to reproduce the behavior

Set at the top level of a pipeline config the `noReleasePrepare` flag as follows:
```YAML
buildPack: none
noReleasePrepare: true
pipelineConfig:
  pipelines:
    release:
      pipeline:
        agent:
```
Despite this, the version is still incremented and the git tag applied, see the-meta pipeline output logs:

```
Showing logs for build meta-ccojocar-org-golang-prodse-w4b4j-12 stage meta-pipeline and container step-create-tekton-crds
running command: ** step next-version --use-git-tag-only --tag
created new version: 0.0.8 and written to file: ./VERSION
Updating chart version in charts/golang-*******/Chart.yaml to 0.0.8
Updating repository in charts/golang-*******/values.yaml to gcr.io/**-development/golang-*******
Updating tag in charts/golang-*******/values.yaml to 0.0.8
error: Have you set up a git credential helper? See https://help.github.com/articles/caching-your-github-password-in-git/
: git output: To https://github.com/ccojocar-org/golang-*******.git
 ! [remote rejected] v0.0.8 -> v0.0.8 (cannot lock ref 'refs/tags/v0.0.8': reference already exists)
```
### Expected behavior

The meta-pipeline should stop incrementing the version and applying the git tag when the `noReleasePrepare` flag is configured to `true`. 

This will allow to run multiple release pipelines in parallel, while only one pipeline will create the tag. This is a very valid use case when running any security scan on `merge to master`.

### Actual behavior

The meta-pipeline does not honour the `noReleasePrepare` flag.

### PR DESCRIPTION
**Pull request by ccojocar**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #6804

### CODE REVIEW

**Comment by ccojocar** [comment]
Thanks @hferentschik! I fixed the unit test. Let's see if the BDD tests needs any adjustment.

**Comment by ccojocar** [comment]
@hferentschik all tests passed! Please could you have a look at the changes? Thanks!

**Comment by hferentschik** [comment]
> all tests passed! Please could you have a look at the changes? Thanks!

Sweet. Just saw it.

**Pull request merged**
