### PR TITLE
fix: support kube 1.16+ api

### PR DESCRIPTION
**Pull request by jiangytcn**
Signed-off-by: Jiang Yitao <jiangyt.cn@gmail.com>

#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description
support kube 1.16+ apis

#### Which issue this PR fixes

fixes
https://github.com/jenkins-x/jx/issues/6358
https://github.com/jenkins-x/jx/issues/6068

### CODE REVIEW

**Comment by jiangytcn** [comment]
jx ui also need to be updated, but cannot find the source repository. is it opensource or a property addon ?

**Comment by abayer** [comment]
Thanks! We should have done this a while ago. =)

**Comment by abayer** [comment]
cc @romainverduci @jstrachan re the UI needing to switch to `AppsV1` instead of `AppsV1beta1` as well.

**Comment by abayer** [comment]
Looks like a couple tests need to be updated too:
```
pkg/applications/applications_test.go:147:69: cannot use test.deployments (type map[string]map[string]"k8s.io/api/apps/v1beta1".Deployment) as type map[string]map[string]"k8s.io/api/apps/v1".Deployment in argument to test.list.appendMatchingDeployments
pkg/kube/activity_test.go:97:61: cannot use mockTektonDeployment (type *"k8s.io/api/apps/v1beta1".Deployment) as type *"k8s.io/api/apps/v1".Deployment in argument to mockKubeClient.AppsV1().Deployments(nsObj.ObjectMeta.Namespace).Create
```

**Comment by jiangytcn** [comment]
thanks @abayer  updated the test case

**Comment by zzguang520** [comment]
Hi team,
    I see #6068 has been fixed, why do I still have this problem  
[root@oc7778463706 ~]# jx version
NAME               VERSION
jx                 2.1.10
jenkins x platform 2.0.2171
Kubernetes cluster v1.18.1
kubectl            v1.16.9
helm client        2.16.6
git                2.18.4
Operating System   "Red Hat Enterprise Linux Workstation release 7.7 (Maipo)"


verifying packages

**Comment by jiangytcn** [comment]
@zzguang520 the PR only fixed the issue in `jx`, the issue you had are other components

**Pull request merged**
