### PR TITLE
refactor: extracting more functionality into pipelines.go 

### PR DESCRIPTION
**Pull request by hferentschik**
* Moving more code out of create_step_create
* Introducing a wrapper class for the Tekton CRDs

The motivation for the refactor is to have less code in the command class and the ability to share some of the code with the metapipleine stuff (#3342) I am working on.

### CODE REVIEW

**Comment by hferentschik** [comment]
@joseblas ^^

**Comment by abayer** [comment]
/assign @dwnusbaum 
Looks good so far!

**Comment by hferentschik** [comment]
Rebased.

**Comment by hferentschik** [comment]
@pmuir, I rebased. Given that it still has the 'approved' label should it not merge? Or does it need another lgtm label in which case what's the point of 'approve'?

**Pull request merged**
