### PR TITLE
fix: Adding brew config for goreleaser

### PR DESCRIPTION
**Pull request by cagiti**
Get goreleaser to generate the update for homebrew, should hopefully fix https://github.com/jenkins-x/jx/issues/4503
Signed-off-by: Cai Cooper <caicooper82@gmail.com>

### CODE REVIEW

**Comment by pmuir** [comment]
Can you also remove the `updatebot` command from the script file?

**Comment by cagiti** [comment]
> Can you also remove the `updatebot` command from the script file?

cheers @pmuir , missed that

**Comment by cagiti** [comment]
@pmuir : do all commits in a PR need "<type>:<commit msg>" as well as the PR title?

**Comment by cagiti** [comment]
/override Semantic Pull Request
All commits need to be in the fashion <type>:<message>

**Comment by cagiti** [comment]
manually merging due to issues auto merging

**Pull request merged**
