### PR TITLE
fix: use newer kaniko image

### LINKED ISSUE #7012: use new kaniko release
### Summary 

Use newer release of kaniko

### Expected behavior

`jx` uses a newer version of kaniko. Some relevant fixes I'm specifically after:
https://github.com/GoogleContainerTools/kaniko/issues/9
https://github.com/GoogleContainerTools/kaniko/issues/826

### Actual behavior

`jx` uses a `gcr.io/kaniko-project/executor:debug-9912ccbf8d22bbafbf971124600fbb0b13b9cbd6` which is apparently close to `gcr.io/kaniko-project/executor:debug-v0.10.0`

### Jx version

The output of `jx version` is:

`jxl version`
```
NAME               VERSION
jxl                0.0.158
Kubernetes cluster v1.14.9-eks-502bfb
kubectl            v1.17.3
helm client        3.1.2
git                2.25.1
Operating System   "Fedora release 31 (Thirty One)"
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Lighthouse)
- [ ] Classic Jenkins

### Kubernetes cluster

EKS created using `eksctl`

### Operating system / Environment

Fedora release 31 (Thirty One)

### PR DESCRIPTION
**Pull request by gazal-k**
Signed-off-by: Gazal K <mohamed.gazal@target.com.au>

#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #7012

### CODE REVIEW

**Comment by gazal-k** [comment]
I realise there's an effort to manage this in the version stream; #5063. But for now, this should help.

**Comment by gazal-k** [comment]
There were some more references to the old release in this repository. In jx pipeline files. Wasn't sure whether I should change those

**Comment by nodece** [comment]
I have a good idea. Let's define environment variables to replace the kaniko image.

**Comment by gazal-k** [comment]
> I have a good idea. Let's define environment variables to replace the kaniko image.

Sorry, I prefer @abayer's suggestion of specifying the kaniko image version in the version stream. This is just an interim fix

**Comment by gazal-k** [comment]
@abayer or anyone who has access to https://dashboard-jx.jenkins-x.live/teams/jx/projects/jenkins-x/jx/PR-7013/5, can you please share what's broken by this change. I checked the `jenkins-x-boot-vault.yml` pipeline and it looks quite tricky for me to verify that on my machine

**Comment by abayer** [comment]
/retest

It was just transient noise - rerunning.

**Comment by gazal-k** [comment]
Thanks @abayer. Can someone (perhaps @jstrachan or @rawlingsj) please apply this on `multicluster` branch for `jxl` and update the `jx` version referenced in `jxl`

**Pull request merged**
