### PR TITLE
fix: hack helm hooks on upgrade helm chart

### LINKED ISSUE #7531: jx add app on GitOps enviroment fails
### Summary

Enable GitOps, It doesn't work that Install an app that helm chart with `post-install` hooks, because `jx step helm apply` skip `post-install` hooks.

### Steps to reproduce the behavior

`jx add app jx-app-gloo`

### Expected behavior

the command can install gloo and knative to my cluster.

### Actual behavior

cannot install any application.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.1.62
Kubernetes cluster v1.14.10-gke.36
kubectl            v1.13.2
helm client        2.12.2
git                2.24.3 (Apple Git-128)
Operating System   Mac OS X 10.15.5 build 19F101
```

### PR DESCRIPTION
**Pull request by nodece**
Signed-off-by: Zixuan Liu <nodeces@gmail.com>

#### Which issue this PR fixes

fixes #7531

### CODE REVIEW

**Comment by ankitm123** [comment]
@nodece need an issue.

**Comment by nodece** [comment]
@ankitm123 I created an issues: #7531

**Comment by nodece** [comment]
@ankitm123 could you reset tf-boot?

**Comment by MarckK** [comment]
Not sure why tf-boot is failing.
Logs:

Verifying the CLI packages using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: v1.0.562
error: failed to parse semantic version for current version 820 for package kubectl: No Major.Minor.Patch elements found
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c ** step verify preinstall --provider-values-dir="kubeProviders"' command in directory '.', output: ''
Pipeline failed on stage 'e2e-tests' : container 'step-e2e-tests'. The execution of the pipeline has stopped.

**Pull request merged**
