### PR TITLE
new command to delete pipelines

### LINKED ISSUE #123: Need to be able to delete an app/pipeline

### PR DESCRIPTION
**Pull request by ndeloof**
close #123

Signed-off-by: Nicolas De Loof <nicolas.deloof@gmail.com>

### CODE REVIEW

**Comment by michaelneale** [comment]
nice!

I wasn't able to see it work though: 

```
./jx delete pipeline michaelneale/demo/master
```

returned success but pipeline remains

**Comment by ndeloof** [comment]
bug in golang-jenkins ?
isn't this a multibranch pipeline ? Will then be automatically re-created by branch indexing, right ?

**Comment by michaelneale** [comment]
@ndeloof it is multibranch - but I would think it wouldn't recreate it instantly, and only the branch. 

I guess this probably could be replaced by "delete app" given get app command is sort-of working. 
This would cover more than the pipeline - but the whole definition, the repo etc.. so not entirely clear what the scope of it is (as it is - I think deleteJob isn't working)

**Comment by jstrachan** [comment]
I wonder if we should even let folks delete pipelines inside a MultiBranchProject - as the MBP is just gonna recreate it next time it scans? Maybe we should warn the user or something?

Deleting the MBP sounds a nice idea though; for when folks want to remove projects from their jenkins

**Comment by michaelneale** [comment]
@jstrachan yeah, deleting a pipeline per se is probably not the right thing to delete. 
There is a desire I have to delete *something* - ie I made a new project, imported, but I no longer want to do it. How do I clean all that up so there is no trace of it, so it isn't using resources? I can delete the project repo, the environment repos, but the pipelines and any running apps/environments will stay running? Is what I am missing more like a cleanup command? Should things be deleted when repos are deleted?

**Comment by michaelneale** [comment]
Should we close this? 

There is still a need to remove things, like say you don't care about an app anymore, you will want to remove the pipeline, but also any other resources too.

**Pull request closed without merging**
