### PR TITLE
refactor: move the CommonOptions type and its associated methods in a separte package opts

### PR DESCRIPTION
**Pull request by ccojocar**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

part of #1016

### CODE REVIEW

**Comment by jstrachan** [comment]
@ccojocar not sure if this is a change getting merged before your PR but the integration tests fail with: 
```
go: finding k8s.io/metrics v0.0.0-20180620010437-b11cf31b380b
# github.com/jenkins-x/jx/pkg/jx/cmd
pkg/jx/cmd/step_git_merge.go:127:16: o.getCommandOutput undefined (type *StepGitMergeOptions has no field or method getCommandOutput)
pkg/jx/cmd/step_git_merge.go:129:11: o.runCommandFromDir undefined (type *StepGitMergeOptions has no field or method runCommandFromDir)
pkg/jx/cmd/step_git_merge.go:134:17: o.getCommandOutput undefined (type *StepGitMergeOptions has no field or method getCommandOutput)
pkg/jx/cmd/step_git_merge.go:136:11: o.runCommandFromDir undefined (type *StepGitMergeOptions has no field or method runCommandFromDir)
```

**Comment by ccojocar** [comment]
@jstrachan Thanks! I am looking into it. I rebased it this morning, and there were a few new changes.

**Comment by ccojocar** [comment]
@jstrachan I pushed a fix. Let's see if the tests will pass.

**Pull request merged**
