### PR TITLE
feat: adds a command to generate a helmfile.yaml from a j…

### PR DESCRIPTION
**Pull request by rawlingsj**
…x-apps.yml

this is an experimental feature which is isolated, if the idea matures then we may want to add the application types to a jx-requirements.yaml and remove the use of jx-apps.yml.  The reason that's not done here is so that we don't let the experiment affect existing core functionality.

I've also included a top level experiment command we can add these types of labs efforts to make it clear they are experimental and will likely change.

example usage:
```
jx step create helmfile --values ../secrets.yaml --values ../jx-requirements.values.yaml.gotmpl --outputDir ./apps
```

relates to the app extensions for boot [enhancement](https://github.com/jenkins-x/enhancements/pull/1) and issue #6442

Signed-off-by: James Rawlings <rawlingsj80@gmail.com>

### CODE REVIEW

**Comment by jstrachan** [comment]
@rawlingsj I guess the primary user of this command would be the `jx boot` pipelines for helmfile; so I wonder if its better to move this command inside `jx step create helmfile` so its with all the other pipeline steps; rather than a top level `jx create` which end users might see via tab completion etc?

**Comment by rawlingsj** [comment]
> I guess the primary user of this command would be the jx boot pipelines for helmfile; so I wonder if its better to move this command inside jx step create helmfile so its with all the other pipeline steps; rather than a top level jx create which end users might see via tab completion etc?

yeah good call, lemme do that now

**Pull request merged**
