### PR TITLE
Regen openapi schema

### PR DESCRIPTION
**Pull request by davidcurrie**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

Ran `make generate-openapi` to pick up changes from https://github.com/jenkins-x/jx/commit/74e3ff7902e7f0ba8d0c9882bf2d3c2e527e611c.

### CODE REVIEW

**Comment by davidcurrie** [comment]
I don't believe I have any visibility of the build logs any more so I have no idea why this might be causing tests to fail.

**Comment by davidcurrie** [comment]
/ test bdd

**Comment by rawlingsj** [comment]
just popping on hold so we can merge as a batch

**Comment by rawlingsj** [comment]
again holding to tie into a batch
/hold

**Pull request merged**
