### PR TITLE
feat(ingress): add option to wait for TLS certificates until are issued by cert-manager

### PR DESCRIPTION
**Pull request by ccojocar**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

- Add an option into `upgrade ingress` command which waits until the TLS certificates are issued by cert-manager
- Change slightly the `create vault` command to wait until the TLS certificate is issued
- Fix the `helm template` (no-tiller) to be able to install the cert-manager chart: handle the crd-install hook, split any YAML file
which contains multiple Kuberntes objects in separate files per object
- Reorganize the methods in the `Factory` interface and slightly rename some methods for consistency

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by rawlingsj** [comment]
CI passed but there's a conflict unfortunately

**Comment by ccojocar** [comment]
@rawlingsj It is rebased now! Needs only a `lgtm`.

**Pull request merged**
