### PR TITLE
fix: Use pipelineConfig.Env again, don't merge for later stages

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

#3585 nuked the usage of `PipelineConfig.Env` variables - this puts that back. We're still ignoring `ProjectConfig.Env`, since that was already being ignored by build packs using Knative Build, though. We also stop running `git merge` for stages after the one that actually needs to do the checkout, since we're reusing the workspace from the initial stage anyway.

#### Special notes for the reviewer(s)

/assign @rawlingsj 
/assign @jstrachan 
/assign @dwnusbaum 

#### Which issue this PR fixes

n/a

### CODE REVIEW

**Comment by abayer** [comment]
fwiw, unit tests passed on my first commit, then failed after I did nothing but add a comment, so I gotta assume it's something else wrong somewhere else. =)

**Comment by jstrachan** [comment]
@abayer think we have a flaky test :(

**Comment by abayer** [comment]
Fun fun fun...

**Comment by abayer** [comment]
@jstrachan Well, it passed this time. =)

**Comment by jstrachan** [comment]
@abayer phew! :)

**Comment by abayer** [comment]
@jstrachan Though it does still need a new lgtm. =)

**Pull request merged**
