### PR TITLE
fix: gcactivities should check for tekton rather than prow

### PR DESCRIPTION
**Pull request by sboardwell**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

We have the situation where prow is installed independently on a Jenkins X cluster. This was discussed with @rawlingsj in [this slack thread](https://kubernetes.slack.com/archives/C9LTHT2BB/p1562879271069500) 

This PR fixes the gcactivities pod which incorrectly assumed `tekton` was installed after finding `prow` on the system.

#### Special notes for the reviewer(s)

It works on our clusters. However, I have not tested this on a cluster running tekton. It was be great if someone could do this first. 
* A pre-compiled image is here: docker.io/sboardwell/builder-jx:dev 
* How to test was provided by James [here](https://kubernetes.slack.com/archives/C9LTHT2BB/p1563263288294100?thread_ts=1562879271.069500&cid=C9LTHT2BB)

cc: @jstrachan

### CODE REVIEW

**Comment by sboardwell** [comment]
Anything I can do @abayer?

**Comment by rawlingsj** [comment]
This looks like the integration test failure in the logs:

```
=== Failed
=== FAIL: pkg/cmd/gc TestGCPipelineActivitiesWithBatchAndPRBuilds (0.49s)
=== PAUSE TestGCPipelineActivitiesWithBatchAndPRBuilds
=== CONT  TestGCPipelineActivitiesWithBatchAndPRBuilds
    gc_activities_test.go:84: 
        	Error Trace:	gc_activities_test.go:84
        	Error:      	Received unexpected error:
        	            	secrets "jenkins" not found
        	Test:       	TestGCPipelineActivitiesWithBatchAndPRBuilds
    gc_activities_test.go:89: 
        	Error Trace:	gc_activities_test.go:89
        	Error:      	"[{{ } {1  jx    %!s(int64=0) 0001-01-01 00:00:00 +0000 UTC <nil> %!s(*int64=<nil>) map[branch:PR-1] map[] [] nil [] } {org/project/PR-1    <nil> 2019-07-20 22:10:32.260248548 +0000 UTC []                [] [] {  []}} {}} {{ } {2  jx    %!s(int64=0) 0001-01-01 00:00:00 +0000 UTC <nil> %!s(*int64=<nil>) map[branch:batch] map[] [] nil [] } {org/project/batch    <nil> 2019-07-20 22:10:32.260248548 +0000 UTC []                [] [] {  []}} {}} {{ } {3  jx    %!s(int64=0) 0001-01-01 00:00:00 +0000 UTC <nil> %!s(*int64=<nil>) map[branch:master] map[] [] nil [] } {org/project/master    <nil> 2019-07-20 22:10:32.260248548 +0000 UTC []                [] [] {  []}} {}}]" should have 2 item(s), but has 3
        	Test:       	TestGCPipelineActivitiesWithBatchAndPRBuilds
        	Messages:   	One of the activities should've been garbage collected
```

**Comment by sboardwell** [comment]
@rawlingsj / @pmuir: sorry, didn't realise the above message was for me.

```
    gc_activities_test.go:84: 
        	Error Trace:	gc_activities_test.go:84
        	Error:      	Received unexpected error:
        	            	secrets "jenkins" not found
        	Test:       	TestGCPipelineActivitiesWithBatchAndPRBuilds
```

I'm at a bit of a loss as to how my change could have caused this. It seems this error might also be the cause of the second "One of the activities should've been garbage collected" error.

How would I test this? Is there any documentation or best practives somewhere? I've tried things like
```
make get-test-deps
make test-integration1 TEST=TestGCPipelineActivitiesWithBatchAndPRBuilds
```
but it doesn't seem to work.

**Comment by pmuir** [comment]
I tend to run tests from the IDE - and they work for me

**Comment by pmuir** [comment]
BTW I would have thought the reason this is causing problems is because of this:

**Comment by sboardwell** [comment]
Thanks for these. Let me have another look.

**Comment by sboardwell** [comment]
Hi @pmuir, @rawlingsj,

sorry, but unless someone can supply me with a set of instructions as to how to run the tests I cannot move on here. The `make build` command works but I can't for the life in me get the integration tests to run.

Is there any documentation as to:
* clone jx repo
* set up GOPATH, GOROOT, etc
* run `make ....` to download dependencies
* run `go ...` to do this
* run `make ...` to do the other
* run test with ...


Here's how far I got...
```
/usr/local/opt/go/libexec/bin/go test -timeout 30s github.com/jenkins-x/jx/pkg/cmd/gc -run ^(TestGCPipelineActivitiesWithBatchAndPRBuilds)$

# github.com/jenkins-x/jx/pkg/tekton/syntax
/Users/sboardwell/.go/src/github.com/jenkins-x/jx/pkg/tekton/syntax/pipeline.go:1196:4: cannot use "k8s.io/apimachinery/pkg/apis/meta/v1".TypeMeta literal (type "k8s.io/apimachinery/pkg/apis/meta/v1".TypeMeta) as type "github.com/tektoncd/pipeline/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".TypeMeta in field value
/Users/sboardwell/.go/src/github.com/jenkins-x/jx/pkg/tekton/syntax/pipeline.go:1200:4: cannot use "k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type "k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "github.com/tektoncd/pipeline/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
/Users/sboardwell/.go/src/github.com/jenkins-x/jx/pkg/tekton/syntax/pipeline.go:1248:25: cannot use actualSteps (type []"k8s.io/api/core/v1".Container) as type []"github.com/tektoncd/pipeline/vendor/k8s.io/api/core/v1".Container in append
/Users/sboardwell/.go/src/github.com/jenkins-x/jx/pkg/tekton/syntax/pipeline.go:1262:27: cannot use volumes[v] (type "k8s.io/api/core/v1".Volume) as type "github.com/tektoncd/pipeline/vendor/k8s.io/api/core/v1".Volume in append
/Users/sboardwell/.go/src/github.com/jenkins-x/jx/pkg/tekton/syntax/pipeline.go:1511:3: cannot use "k8s.io/apimachinery/pkg/apis/meta/v1".TypeMeta literal (type "k8s.io/apimachinery/pkg/apis/meta/v1".TypeMeta) as type "github.com/tektoncd/pipeline/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".TypeMeta in field value
/Users/sboardwell/.go/src/github.com/jenkins-x/jx/pkg/tekton/syntax/pipeline.go:1515:3: cannot use "k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type "k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "github.com/tektoncd/pipeline/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
/Users/sboardwell/.go/src/github.com/jenkins-x/jx/pkg/tekton/syntax/pipeline.go:1833:3: cannot use []"k8s.io/api/core/v1".Container literal (type []"k8s.io/api/core/v1".Container) as type []"github.com/tektoncd/pipeline/vendor/k8s.io/api/core/v1".Container in field value
# github.com/knative/serving/pkg/apis/serving/v1alpha1
/Users/sboardwell/.go/src/github.com/knative/serving/pkg/apis/serving/v1alpha1/configuration_conversion.go:30:2: impossible type switch case: obj (type "github.com/knative/serving/vendor/knative.dev/pkg/apis".Convertible) cannot have dynamic type *"knative.dev/serving/pkg/apis/serving/v1beta1".Configuration (wrong type for ConvertDown method)
	have ConvertDown(context.Context, "knative.dev/serving/vendor/knative.dev/pkg/apis".Convertible) error
	want ConvertDown(context.Context, "github.com/knative/serving/vendor/knative.dev/pkg/apis".Convertible) error
/Users/sboardwell/.go/src/github.com/knative/serving/pkg/apis/serving/v1alpha1/configuration_conversion.go:31:19: cannot use source.ObjectMeta (type "github.com/knative/serving/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "knative.dev/serving/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in assignment
```


I did have a look at Goland btw but I'm only ever using Go for jx at the moment and the subscription wouldn't be worth it for me.

**Comment by sboardwell** [comment]
Regarding the test failures, I still can't see why they might fail with my changes. Unless, that is, there is an option to have prow without tekton (maybe knative, but I thought that was replaced by tekton). In which case I would need to re-introduce the `prowEnabled` for the latter conditions.

I can do that but I wouldn't  really understand it.

**Comment by sboardwell** [comment]
@pmuir , @rawlingsj, please do not merge this PR. 

Looking at the code there is something wrong here. The `tekton` vs `prow` thing should not make a difference since the `IsProw` method checks the TeamSettings which is Jenkins for us (even if we do have prow installed separately).
```
	return env.Spec.TeamSettings.PromotionEngine == jenkinsv1.PromotionEngineProw, nil
```

Saw the `jx diagnose` command completed successfully (wasn't sure what it did). 

So, with all else failing, I went at with it with a sledge hammer adding the good old "I'm here 1", "I'm here 2", etc before created an image to spin up myself and see where it was failing. 

Quick Kudos: the `TRACE_KUBE_API=on` option is awesome btw!!!

It looks like it is due to an incorrect `jenkins` secret, which throws an `error: 403 Forbidden`

I will check and get back to you. A couple of questions:
* is there any `jx` way of recreating the jenkins secret? 
* can it be placed in a values.yaml to be change on upgrade platform?
* is there any command to check/verify secrets such as this?

**Comment by sboardwell** [comment]
Ok, closing this PR. There were a number of small things leading up to this. Here's  a quick summary:

### Possible real bug - gcactivities trying to access the `jx-install-config`

During the debugging, I could see the gcactivities trying to access the `jx-install-config` configmap. It receives a `403 Forbidden` because the permission is missing. 

Is it needed? Or should the gcactivities pod not need to access the jx-install-config.

```
---
GET /api/v1/namespaces/jx/configmaps/jx-install-config HTTP/1.1
Host: 10.168.0.1:443
User-Agent: jx/v0.0.0 (linux/amd64) kubernetes/$Format
Accept: application/json, */*
Authorization: Bearer xxx
Accept-Encoding: gzip


HTTP/2.0 403 Forbidden
Content-Length: 353
Audit-Id: 34f93328-1565-42df-88e6-00cbf2f1047e
Content-Type: application/json
Date: Fri, 02 Aug 2019 10:57:55 GMT
X-Content-Type-Options: nosniff

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps \"jx-install-config\" is forbidden: User \"system:serviceaccount:jx:jenkins-x-gcactivities\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"jx\"","reason":"Forbidden","details":{"name":"jx-install-config","kind":"configmaps"},"code":403}
```

### Older Version of `jx` used in the gcactivities pod

The initial warning was initial source of confusion.

Looking at the code, the warning `{"level":"warning","msg":"no PipelineRun instances found: the server could not find the requested resource (get pipelineruns.tekton.dev)\n","time":"2019-07-11T21:00:54Z"}` in the gcactivities pod should never have been possible. Ok, found the problem:
* `2.0.330` - our jenkins x platform release version
*  `2.0.147` - the fix was introduced. See https://github.com/jenkins-x/jx/commit/468383534215c3b64fb00c4182d2a233814108bd
* `2.0.147` the `gcactivities` spec image of jx

Is it not possible to deploy the same version of jx with the release? 
Is there anywhere we can see the various component versions? 

### Jenkins secrets was not up to date

This was due to us changing from GitHub OAuth (github username) to Google OAuth (email) for our static jenkins server. I will check to see how we can keep that configured in the `myvalues.yaml`

### Final piece of the puzzle

We have a VPC enabled GKE cluster with an IP white-list enabled nginx-controller (as in my post here: https://medium.com/@sboardwell/jenkins-x-securing-the-cluster-e1b9fcd8dd05).

The pod range was not in the white-list and was thus being blocked, returning the `403 Forbidden` 🤦‍♂

Adding the pod range finally solved the problem.

**Comment by sboardwell** [comment]
@rawlingsj or @pmuir - I'll close this now, but if you get time, maybe you could say something to the following: 

* Is it not possible to deploy the same version of jx with the release?
* Is there anywhere we can see the various component versions?

**Pull request closed without merging**
