### PR TITLE
WIP refactor: refactor services and handle error

### LINKED ISSUE #7372: Refactor services package
### Summary 
* Add tests for the service package
* Improve error handling:
```
url, _ = FindServiceURL(client, namespace, svc.Name)
```
* Make functions which are not used outside the package private

Came across these issues when trying to debug #7340

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description
This PR
* Adds tests for the `jx get urls` command, which also helps to test many of the underlying service functions
* Adds basic tests for majority of the service functions (more test cases can be added subsequently, but this is a start) and refactors them
* Fixes minor bugs (discovered from running the unit tests)
* Improves error handling

#### Special notes for the reviewer(s)
The pattern for testing used is this:
* top level command should be tested to check the flags work, and some basic cases (basic success and fail) - get url command test
* The underlying functions can be checked with more test cases (more exhaustive) - services package test.

#### Which issue this PR fixes

fixes #7372

### CODE REVIEW

**Comment by mrageh** [comment]
Were all the functions you removed in this PR unused?

**Comment by ankitm123** [comment]
I checked for those functions in the codebase, did not see a reference. I still need to add some tests. Do you some function that was removed by mistake?

**Pull request closed without merging**
