### PR TITLE
Get last message from mono repo and put it in the commit message

### PR DESCRIPTION
**Pull request by ssathi**
Description

When using jx step split, to split a mono repo, it puts a default message ''generated by: jx step split monorepo". I'm trying to get the commit message from the mono repo and add it instead.

This applies to an existing GitHub mono repo. There is a new argument added 'reponame' to make split step to retrieve last message from the repo.

Issue related:
#3203

### CODE REVIEW

**Comment by ssathi** [comment]
@jstrachan

I'm sorry. I made a mess with the previous PR by rebasing it to upstream/master and got lot of commits. So I created this pull request again. I this has the code changes requested as well. Please ok to test.

**Comment by ssathi** [comment]
@ccojocar
Could you please resolve and merge this PR? Thanks.

**Comment by ccojocar** [comment]
@ssathi Please could you rebase this PR and solve the conflicting files? Thanks

**Comment by ssathi** [comment]
@ccojocar 
Could you please let me know why this fails? formats and test all work ok.

**Comment by rawlingsj** [comment]
Sorry about the bad CI - we're currently in the process of moving to the new Tekton pipeline engine which is improving CI massively.  We plan to move the jx repo to this new engine and infra next week.

**Comment by ssathi** [comment]
@rawlingsj
Thank you for letting me know. Please merge this asap.

**Comment by ssathi** [comment]
@rawlingsj
This is taking so long. Could you please let me know if I can do anything from my side.

**Comment by rawlingsj** [comment]
while we move releases to new infra
/hold

**Pull request merged**
