### PR TITLE
feat: adding ability to create namespace via 'jx ns --create <name>

### PR DESCRIPTION
**Pull request by hferentschik**
fixes issue #3846

#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

Adds a `--create` option to `jx ns <name>` and adds some tests around the namespace command.

### CODE REVIEW

**Comment by ccojocar** [comment]
I am wondering why not using the `kubectl create ns <name> instead of the --create option. Are there any benefits in duplicating it in jx CLI?

**Comment by hferentschik** [comment]
> I am wondering why not using the kubectl create ns <name> instead of the --create option. Are there any benefits in duplicating it in jx CLI?

Would the "what for" argument not apply for the namespace command in general? I am a bit concerned in general about the various non-core helper commands in `jx`. I'd argue the whole command should maybe not be there. This might also reduce potential confusion for users between concepts of pure Kubernetes namespaces and a jx environment. 

That said, I see how `jx ns` is a bit more convenient to use compared to plain kubectl and I added the flag for completeness and because I missed ` kubectl create ns <name>`. I thought for creating
a namespace I need to use the `-f` option and provide a namespace spec. Compared to this the additional flag on `jx` was much easier. 

I feel the flag does not hurt and I did a bit of code cleanup as well and added some tests.

**Comment by ccojocar** [comment]
It sounds good to me! I just wanted to raise awareness when some functionality gets duplicated form kubectl or from some other popular CLI. It is fine If there is a good reason, otherwise all these features will require some maintenance and bug fixing.

**Comment by hferentschik** [comment]
> I just wanted to raise awareness when some functionality gets duplicated form kubectl or from some other popular CLI. It is fine If there is a good reason, otherwise all these features will require some maintenance and bug fixing.

Completely agree. I was wondering whether for the sake of clarity it would make sense to move this pure helper commands (for example `jx ns`) into a CLI extension app. Something like `jx-kubectl-helpers`. This would reduce the scope of `jx` and increases the clarity imo. AFAIU the capabilities to extend the CLI via Apps is there. This might be a use case for it.  That's a different discussion though. Just putting out the idea.

**Pull request merged**
