### PR TITLE
[wip] fix: making sure FakeGitProvider is properly configured

### LINKED ISSUE #3625: Integration tests are failing
### Summary 

The integration tests run by `make test-slow-integration` are failing. This failure also occurs on CI and lets the _integration_ status check fail. 

### Steps to reproduce the behavior

Run (multiple times if necessary):

```bash
$ make test-slow-integration
```

### Expected behavior

Tests pass

### Actual behavior

The test logs:
```
...
 FAIL: TestImportProjectNextGenPipeline (27.84s)
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/custom_jenkins from source test_data/import_projects/custom_jenkins
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/docker from source test_data/import_projects/docker
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/docker-helm from source test_data/import_projects/docker-helm
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/gradle_no_files from source test_data/import_projects/gradle_no_files
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/helm from source test_data/import_projects/helm
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/maven_camel from source test_data/import_projects/maven_camel
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/maven_custom_build_pack from source test_data/import_projects/maven_custom_build_pack
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/maven_no_files from source test_data/import_projects/maven_no_files
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/maven_old_jenkinsfile from source test_data/import_projects/maven_old_jenkinsfile
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-import-ng-projects395871307-DefaultJenkinsfile/maven_old_jenkinsfile_with_git from source test_data/import_projects/maven_old_jenkinsfile_with_git
    import_integration_test.go:154: 
        	Error Trace:	import_integration_test.go:154
        	            				import_integration_test.go:103
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Failed with no Git provider server URL found
    import_integration_test.go:104: 
        	Error Trace:	import_integration_test.go:104
        	            				import_integration_test.go:81
        	Error:      	Received unexpected error:
        	            	no Git provider server URL found
        	Test:       	TestImportProjectNextGenPipeline
        	Messages:   	Importing dir /var/folders/25/wrys45bs1jscckzb3lj9rtb40000gn/T/test-

...

FAIL	github.com/jenkins-x/jx/pkg/jx/cmd	338.772s
?   	github.com/jenkins-x/jx/pkg/jx/cmd/bdd	[no test files]
?   	github.com/jenkins-x/jx/pkg/jx/cmd/clients	[no test files]
?   	github.com/jenkins-x/jx/pkg/jx/cmd/clients/mocks	[no test files]
?   	github.com/jenkins-x/jx/pkg/jx/cmd/cmd_test_helpers	[no test files]
ok  	github.com/jenkins-x/jx/pkg/jx/cmd/opts	39.340s	coverage: 3.3% of statements
?   	github.com/jenkins-x/jx/pkg/jx/cmd/templates	[no test files]
?   	github.com/jenkins-x/jx/pkg/kserving	[no test files]
ok  	github.com/jenkins-x/jx/pkg/kube	1.653s	coverage: 31.0% of statements
ok  	github.com/jenkins-x/jx/pkg/kube/cluster	0.289s	coverage: 76.0% of statements
?   	github.com/jenkins-x/jx/pkg/kube/mocks	[no test files]
?   	github.com/jenkins-x/jx/pkg/kube/mocks/matchers	[no test files]
ok  	github.com/jenkins-x/jx/pkg/kube/pki	10.226s	coverage: 20.9% of statements
?   	github.com/jenkins-x/jx/pkg/kube/resources	[no test files]
?   	github.com/jenkins-x/jx/pkg/kube/resources/mocks	[no test files]
?   	github.com/jenkins-x/jx/pkg/kube/serviceaccount	[no test files]
?   	github.com/jenkins-x/jx/pkg/kube/services	[no test files]
ok  	github.com/jenkins-x/jx/pkg/kube/vault	0.547s	coverage: 57.6% of statements
?   	github.com/jenkins-x/jx/pkg/log	[no test files]
?   	github.com/jenkins-x/jx/pkg/maven	[no test files]
?   	github.com/jenkins-x/jx/pkg/nodes	[no test files]
ok  	github.com/jenkins-x/jx/pkg/packages	0.052s	coverage: 38.8% of statements
?   	github.com/jenkins-x/jx/pkg/pipeline_events	[no test files]
ok  	github.com/jenkins-x/jx/pkg/pipelinescheduler	0.201s	coverage: 43.4% of statements
ok  	github.com/jenkins-x/jx/pkg/pipelinescheduler/prow	0.225s	coverage: 89.7% of statements
?   	github.com/jenkins-x/jx/pkg/pipelinescheduler/testhelpers	[no test files]
ok  	github.com/jenkins-x/jx/pkg/prow	0.305s	coverage: 78.4% of statements
ok  	github.com/jenkins-x/jx/pkg/prow/config	0.248s	coverage: 9.6% of statements
ok  	github.com/jenkins-x/jx/pkg/quickstarts	0.215s	coverage: 18.4% of statements
ok  	github.com/jenkins-x/jx/pkg/reports	0.056s	coverage: 39.7% of statements
?   	github.com/jenkins-x/jx/pkg/spring	[no test files]
ok  	github.com/jenkins-x/jx/pkg/surveyutils	0.366s	coverage: 64.3% of statements
?   	github.com/jenkins-x/jx/pkg/table	[no test files]
ok  	github.com/jenkins-x/jx/pkg/tekton	0.323s	coverage: 38.9% of statements
ok  	github.com/jenkins-x/jx/pkg/tekton/syntax	0.254s	coverage: 89.7% of statements
?   	github.com/jenkins-x/jx/pkg/tekton/tekton_helpers_test	[no test files]
ok  	github.com/jenkins-x/jx/pkg/terraform	0.054s	coverage: 6.8% of statements
?   	github.com/jenkins-x/jx/pkg/testkube	[no test files]
?   	github.com/jenkins-x/jx/pkg/tests	[no test files]
ok  	github.com/jenkins-x/jx/pkg/users	0.522s	coverage: 43.6% of statements
ok  	github.com/jenkins-x/jx/pkg/util	10.208s	coverage: 25.2% of statements
ok  	github.com/jenkins-x/jx/pkg/util/json	0.178s	coverage: 72.7% of statements
?   	github.com/jenkins-x/jx/pkg/util/mocks	[no test files]
ok  	github.com/jenkins-x/jx/pkg/util/system	0.083s	coverage: 78.9% of statements
ok  	github.com/jenkins-x/jx/pkg/vault	0.178s	coverage: 4.3% of statements
?   	github.com/jenkins-x/jx/pkg/vault/mocks	[no test files]
?   	github.com/jenkins-x/jx/pkg/vault/mocks/matchers	[no test files]
ok  	github.com/jenkins-x/jx/pkg/version	0.053s	coverage: 53.0% of statements
?   	github.com/jenkins-x/jx/pkg/workflow	[no test files]
make: *** [test-slow-integration] Error 1

```

Full log [here](https://gist.github.com/hferentschik/c1d22ad7f58ee4a2310a06f39c6ebbe2).

### PR DESCRIPTION
**Pull request by hferentschik**
fixes #3625

### CODE REVIEW

**Comment by hferentschik** [comment]
Hi, this is an attempt to fix the integration tests. For all, I can tell it has to do with the fact that during the test execution the ImportOption.GitProvider is not properly wired up.

As a quick fix, I create a fake provider and that seems to work. I am not sure whether this is the right approach, especially since there is code dealing with a fake provider. For example, there is `ConfigureTestOptionsWithResources` which takes _nil_ as a parameter for a fake provider. And there is also `CommonOptions.fakeGitProvider`. TBH, I am not sure what the intention is here and how this should fit together. 

AFAICT you guys have refactored this code recently. You might be in a better position to work this out properly.

Feel free to close this pull request if it is not useful or you have something better. I just wanted to see whether it would also pass the `integration` status checks.

**Comment by rawlingsj** [comment]
@hferentschik if you're happy with this too then just remove the "wip" prefix from the PR description and tide will merge this.

**Comment by hferentschik** [comment]
> if you're happy with this too then just remove the "wip" prefix from the PR description and tide will merge this.

What I can say is that this solved the failures for me, but I am not so happy about how it is done. For example, there was a fake git provider set before I made the changes, but the tests failed because all fields were empty/nil. I somehow feel there is a bit more cleanup needed to sort this out properly. Also, I am not sure what business a _fakeGitsProvider_ has in _CommonOptions_. I was hoping @pmuir could shine some light on this. 

If we just want to get the tests passing again, this pull request probably does that, but I fear we are opening us for even more unwanted surprises further down the line.

**Comment by abayer** [comment]
/lgtm

Like I said over on the ticket, I *thought* this was due to the lack of isolation of `JX_HOME` and `KUBECONFIG`, but now I don't think that's the case. Regardless, we shouldn't be using `JX_HOME` at all here if we can avoid it.

**Comment by abayer** [comment]
Closing this since it was subsumed into #3651

**Pull request closed without merging**
