### PR TITLE
fix: Allow all crds with hooks to be processed

### LINKED ISSUE #6344: Velero installation failing
### Summary 

Since upgrading to Velero 1.2 the installation is failing because all the required CRD's are not getting installed.

### PR DESCRIPTION
**Pull request by cagiti**
#### Submitter checklist
- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description
This change allows the helm apply function to iterate and apply all crd part files

#### Which issue this PR fixes
fixes #6344

### CODE REVIEW

**Comment by hferentschik** [comment]
@abayer my turn

/test all

**Comment by hferentschik** [comment]
@cagiti, does that ring a bell:

```
ERROR: error creating cluster installing the Jenkins X platform: failed to install/upgrade the jenkins-x platform chart: failed to run 'kubectl apply -f /tmp/helm-template-workdir-621175791/jenkins-x/helmHooks/post-install,post-upgrade/jenkins-x-platform/charts/expose/templates/part0-job.yaml --namespace ** --validate=false' command in directory '', output: 'the path "/tmp/helm-template-workdir-621175791/jenkins-x/helmHooks/post-install" does not exist
the path "post-upgrade/jenkins-x-platform/charts/expose/templates/part0-job.yaml" does not exist'
```

**Comment by cagiti** [comment]
Cheers @hferentschik, doesn’t ring a bell at the moment... but it’s most likely something I’ve introduced

**Comment by hferentschik** [comment]
what's about squashing this into a single commit now?

**Comment by hferentschik** [comment]
@cagiti what was your issue with squashing your commits?

**Comment by hferentschik** [comment]
Given that we are all about gitops I am surprised how little attention we give to a well crafted git history.

**Pull request merged**
