### PR TITLE
feat:(step_verify) add a commands which verifies the state of the pods of an application after deployment

### PR DESCRIPTION
**Pull request by ccojocar**

### CODE REVIEW

**Comment by i0n** [comment]
This looks awesome. Could use this in the tests.

**Comment by ccojocar** [comment]
We can use it. I am testing it right now within a pipeline.

**Comment by ccojocar** [comment]
I got it working within a pipeline. See the definition here the https://github.com/jenkins-x/sso-operator/blob/master/Jenkinsfile.

**Comment by rawlingsj** [comment]
code lgtm, I've not got a chance to test it now though if that's what you want before merging @ccojocar - if it's been tested then merge away else I can take a look early next week.

**Comment by ccojocar** [comment]
@rawlingsj I have been testing it in the https://github.com/jenkins-x/sso-operator/blob/master/Jenkinsfile since 2 days. I have done couple of deployments with this step enabled. It seems to work fine so far.

**Pull request merged**
