### PR TITLE
chore: test creation of PipelineRunInfo from resources

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

Basically a followup to #3164 - making sure we have tests to validate expected behavior and all that jazz.

#### Which issue this PR fixes

n/a

### CODE REVIEW

**Comment by jstrachan** [comment]
@abayer I see a format issue in the pipeline - wonder if a rebase & `make generate` helps? Probably just a `make fmt` will do

BTW if you use IDEA you can click the `go fmt` on commit option to keep everything formatted

**Comment by abayer** [comment]
@jstrachan Done and done - thanks!

**Pull request merged**
