### PR TITLE
fix: ask the user for a quickstart first before the git repo

### LINKED ISSUE #5307: `jx create quickstart` should ask the user for a quickstart first
right now it asks for a git owner + repo name before we've picked a kind of quickstart which is a slightly confusing UX. It would be nicer to pick a quickstart first, then the owner/repo name after that

e.g. the user might be thinking of making a spring boot app, but then see a nodejs quickstart and pick that - but they've already gone with a name of `myboot`.

### PR DESCRIPTION
**Pull request by jstrachan**
to simplify the UX a little

fixes #5307

Signed-off-by: James Strachan <james.strachan@gmail.com>

### CODE REVIEW

**Comment by abayer** [comment]
@jstrachan - looks like a legit failure:
```
[batch] quickstart golang-http
 Create a quickstart by running ** create quickstart golang-http
  creates a new source repository and promotes it to staging
  /tmp/jenkins-x/bdd-**/test/quickstart/helpers.go:77
      Creating application bdd-gh-1567522430 in dir /tmp/bdd-111262223
      Using Git provider URL https://github.com
STEP: calling ** create quickstart -b --org cb-kubecd -p bdd-gh-1567522430 -f golang-http --git-provider-url https://github.com
error: Missing option: --
      FAILED got unexpected error:

expected exit code 0 but got 1 whilst running command ** create quickstart -b --org cb-kubecd -p bdd-gh-1567522430 -f golang-http --git-provider-url https://github.com

• Failure [1.152 seconds]
[batch] quickstart golang-http

/tmp/jenkins-x/bdd-**/test/quickstart/helpers.go:55
  Create a quickstart
  /tmp/jenkins-x/bdd-**/test/quickstart/helpers.go:75
    by running ** create quickstart golang-http
    /tmp/jenkins-x/bdd-**/test/quickstart/helpers.go:76
      creates a new source repository and promotes it to staging [It]
      /tmp/jenkins-x/bdd-**/test/quickstart/helpers.go:77

      error is printed in log
      Unexpected error:
          <*errors.fundamental | 0xc0001f6760>: {
              msg: "expected exit code 0 but got 1 whilst running command ** create quickstart -b --org cb-kubecd -p bdd-gh-1567522430 -f golang-http --git-provider-url https://github.com",
              stack: [0x80f390, 0x80ef0d, 0x812c76, 0x81813f, 0x760f90, 0x81872e, 0x75097c, 0x7505ef, 0x74fa84, 0x756a56, 0x756304, 0x75c24f, 0x75bd64, 0x75b5a7, 0x75dbee, 0x7605c7, 0x76030d, 0x80feed, 0x819e70, 0x4fa6e0, 0x45e811],
          }
          expected exit code 0 but got 1 whilst running command ** create quickstart -b --org cb-kubecd -p bdd-gh-1567522430 -f golang-http --git-provider-url https://github.com
      occurred

      /tmp/jenkins-x/bdd-**/test/utils/expects.go:13
------------------------------
[batch] quickstart golang-http
 Create a quickstart with invalid parameters when -p param (project name) is missing
  exits with signal 1
  /tmp/jenkins-x/bdd-**/test/quickstart/helpers.go:135
      Creating application bdd-gh-1567522430 in dir /tmp/bdd-111262223
STEP: calling ** create quickstart -b --org cb-kubecd -f golang-http
error: Missing option: --
•
------------------------------
[batch] quickstart golang-http
 Create a quickstart with invalid parameters when -f param (filter) does not match any quickstart
  exits with signal 1
  /tmp/jenkins-x/bdd-**/test/quickstart/helpers.go:144
      Creating application bdd-gh-1567522430 in dir /tmp/bdd-111262223
STEP: calling ** create quickstart -b --org cb-kubecd -p bdd-gh-1567522430 -f the_derek_zoolander_app_for_being_really_really_good_looking
error: No quickstarts match filter
```

**Comment by jstrachan** [comment]
@abayer thanks for the head up! hopefully this fixes it...

**Pull request merged**
