### PR TITLE
refactor: enable codeql alerts

### PR DESCRIPTION
**Pull request by osamamagdy**

### CODE REVIEW

**Comment by ankitm123** [comment]
need to sign DCO. See: https://jenkins-x.io/community/code/#signoff
Would be good to have this on all repos someday.

**Comment by osamamagdy** [comment]
@ankitm123  In this case, should I push another empty commit to sign or revert the commit and push it again with the signature?

**Comment by ankitm123** [comment]
> @ankitm123 In this case, should I push another empty commit to sign or revert the commit and push it again with the signature?

No, you can amend ur commit, and do a force push
```
git commit --amend --no-edit
git push -f origin branch
```

**Comment by osamamagdy** [comment]
@ankitm123 Done

**Pull request merged**
