### PR TITLE
fix: return tekton pipeline runs instead of prow releasejobs

### LINKED ISSUE #7470: jx stop pipeline doesn't find pipeline
### Summary 
After starting a pipeline and having it hang (or go unresolved in some way), trying to use `jx stop pipeline` doesn't work.

### Steps to reproduce the behavior
Start pipeline (either through webhook or `jx start pipeline owner/environment-staging-dev/master`)
Try to stop pipeline:
 ```
jx get pipeline
Name                                          URL LAST_BUILD STATUS DURATION
owner/environment-staging-dev/master        N/A N/A        N/A    N/A

jx stop pipeline owner/environment-staging-dev/master
error: no PipelineRun found for name owner/environment-staging-dev/master
```
### Expected behavior
pipeline aborts

### Actual behavior
Error seen above

### Jx version
The output of `jx version` is:
```
Version        2.1.93
Commit         729fc2b
Build date     2020-06-30T16:56:20Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose version` is:

```
Running in namespace: jx
Version        2.1.93
Commit         729fc2b
Build date     2020-06-30T16:56:20Z
Go version     1.13.8
Git tree state clean
NAME                          VERSION
Kubernetes cluster            v1.15.11-eks-af3caf
kubectl (installed in JX_BIN) v1.15.12
helm client                   2.16.7
git                           2.25.1
Operating System              Ubuntu 20.04 LTS

Please visit https://jenkins-x.io/faq/issues/ for any known issues.

Finished printing diagnostic information.

```

### Kubernetes cluster

AWS EKS, using terraform to create

### Kubectl version
The output of `kubectl version --client` is:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:17:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

### Operating system / Environment
Ubuntu 20.04LTS

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description
Apart from fixing the bug with `jx get pipeline`, changed the names of some structs to fix issues with naming conventions.

#### Which issue this PR fixes
fixes #7470

### CODE REVIEW

**Comment by MarckK** [comment]
Hi @ankitm123, thank you for your PR. 
Logs for some of the tests:
```
--- FAIL: TestGetPipelinesWithProw (0.06s)
    get_pipeline_test.go:55: 
        	Error Trace:	get_pipeline_test.go:55
        	Error:      	"Name   
```

```
--- FAIL: TestGenerateTektonCRDs (0.20s)
    --- FAIL: TestGenerateTektonCRDs/js_build_pack (0.20s)
        step_create_task_test.go:597: Generated Tasks did not match expected: 
              &v1alpha1.TaskList{
              	TypeMeta: v1.TypeMeta{},
              	ListMeta: v1.ListMeta{},
              	Items: []v1alpha1.Task{
              		{
              			TypeMeta:   v1.TypeMeta{Kind: "Task", APIVersion: "tekton.dev/v1alpha1"},
              			ObjectMeta: v1.ObjectMeta{Name: "abayer-js-test-repo-build-pack-9l9zj-from-build-pack-1", Namespace: "**", Labels: map[string]string{"branch": "build-pack", "build": "1", "jenkins.io/pipelineType": "build", "jenkins.io/task-stage-name": "from-build-pack", "owner": "abayer", "repository": "js.test.repo"}},
              			Spec: v1alpha1.TaskSpec{
              				TaskSpec: v1beta1.TaskSpec{
              					Resources:   nil,
              					Params:      nil,
              					Description: "",
              					Steps: []v1beta1.Step{
              						{
              							Container: v1.Container{
              								... // 5 identical fields
              								Ports:   nil,
              								EnvFrom: nil,
              								Env: []v1.EnvVar{
              									... // 6 identical elements
              									{Name: "TILLER_NAMESPACE", Value: "kube-system"},
              									{Name: "XDG_CONFIG_HOME", Value: "/workspace/xdg_config"},
              									{
              										Name:      "DOCKER_REGISTRY_ORG",
            - 										Value:     "abayer",
	                                                                                Value:     "jenkins-x-infra",
              										ValueFrom: nil,
              									},
              									{Name: "BUILD_NUMBER", Value: "1"},
              									{Name: "PIPELINE_KIND", Value: "release"},
              									... // 8 identical elements
              								},
              								Resources:    v1.ResourceRequirements{...},
              								VolumeMounts: []v1.VolumeMount{{Name: "workspace-volume", MountPath: "/home/jenkins"}, {Name: "docker-daemon", MountPath: "/var/run/docker.sock"}, {Name: "volume-0", MountPath: "/home/jenkins/.docker"}, {Name: "podinfo", ReadOnly: true, MountPath: "/etc/podinfo"}},
              								... // 12 identical fields
              							},
              							Script: "",
              						},
              						{
              							Container: v1.Container{
              								... // 5 identical fields
              								Ports:   nil,
              								EnvFrom: nil,
              								Env: []v1.EnvVar{
              									... // 6 identical elements
              									{Name: "TILLER_NAMESPACE", Value: "kube-system"},
              									{Name: "XDG_CONFIG_HOME", Value: "/workspace/xdg_config"},
              									{
              										Name:      "DOCKER_REGISTRY_ORG",
            - 										Value:     "abayer",
            + 										Value:     "jenkins-x-infra",
              										ValueFrom: nil,
```

There's more, especially re the second test logs, but hopefully these logs help you move forward. Let me know if you need anything else and @abayer might have advice as well.

**Comment by ankitm123** [comment]
So it fails cuz of the old tests, if I remove them, they will pass.

**Comment by MarckK** [comment]
Hi @ankitm123, thank you for your PR.
Logs: 

Screenshot 2020-07-28 at 12 30 30

Screenshot 2020-07-28 at 12 31 01

**Comment by ankitm123** [comment]
I see why the tests failed. I changed the naming convention from `prow.ProwPluginsXXX` to `prow.PluginsXXX` to avoid stutter. But the changes were present in the test files, which were not caught when running `make build`.

**Pull request merged**
