### PR TITLE
chore: allow LoadRequirements to be a little less restrictive loading.

### PR DESCRIPTION
**Pull request by garethjevans**
This is useful downstream where we use this function to load requirements
from the file system and we're not guarrenteed to have exactly the same
version of JX.

#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by garethjevans** [comment]
helps fix cloudbees/arcalos#1135

**Comment by hferentschik** [comment]
Could we create an issue as well and maybe squash the commits?

**Pull request merged**
