### PR TITLE
feat: added pre-commit configuration and secrets basline

### PR DESCRIPTION
**Pull request by cagiti**
Signed-off-by: Cai Cooper <caicooper82@gmail.com>

### CODE REVIEW

**Comment by rawlingsj** [comment]
This is awesome @cagiti 

BTW what happens if someone doesn’t install the pre-commit hooks?  I'm just wondering if there's any checks we could but in place or do we expect if folks want the protection then they should install the pre-commit hooks?  I guess if this works nicely then we could roll out to all repos?  I'm happy to take that on, maybe a few of us can blitz it.

**Comment by cagiti** [comment]
> This is awesome @cagiti
> 
> BTW what happens if someone doesn’t install the pre-commit hooks? I'm just wondering if there's any checks we could but in place or do we expect if folks want the protection then they should install the pre-commit hooks? I guess if this works nicely then we could roll out to all repos? I'm happy to take that on, maybe a few of us can blitz it.

Hey @rawlingsj, unfortunately the users would have to install the hook into their git repo using `pre-commit install` - they would also need pre-commit installed locally... however this is pre-installed into the [dev-env](https://github.com/jenkins-x/dev-env). The hook is installed into the repository local `.git/hooks/` directory

**Comment by cagiti** [comment]
> > This is awesome @cagiti
> > BTW what happens if someone doesn’t install the pre-commit hooks? I'm just wondering if there's any checks we could but in place or do we expect if folks want the protection then they should install the pre-commit hooks? I guess if this works nicely then we could roll out to all repos? I'm happy to take that on, maybe a few of us can blitz it.
> 
> Hey @rawlingsj, unfortunately the users would have to install the hook into their git repo using `pre-commit install` - they would also need pre-commit installed locally... however this is pre-installed into the [dev-env](https://github.com/jenkins-x/dev-env). The hook is installed into the local `.git/hooks/` directory within their copy of the repository.

We could create/update a `jx step` command to clone and install the git hooks?

**Pull request merged**
