### PR TITLE
Fix: Making a few more commands possible to run w/o being cluster admin

### PR DESCRIPTION
**Pull request by msvticket**
#### Submitter checklist

- [x] Change is covered by existing or new tests.

#### Description

Here a are a few more fixes to enable a non cluster admin running commands that would be common or at least reasonable for such user to run.

#### Special notes for the reviewer(s)

Since all CRDs are registered in install.go, step_env_apply.go and upgrade_platform.go it should be safe to stop doing it elsewhere. I haven't written any new tests since no new functionality is added.

### CODE REVIEW

**Comment by rawlingsj** [comment]
Looks like an integration test failure:
```
Found pipeline YAML /builder/home/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/maven/pipeline.yaml and template file /builder/home/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-classic/packs/Jenkinsfile.tmpl
--- FAIL: TestStepBuildPackApply (1.91s)
    require.go:794:
        	Error Trace:	step_buildpack_apply_integration_test.go:74
        	Error:      	Received unexpected error:
        	            	template: myJenkinsfile:42:17: executing "myJenkinsfile" at <.Pipelines.Post.Groo...>: can't evaluate field Post in type jenkinsfile.Pipelines
        	            	failed to write file /tmp/test-step-buildpack-apply517403180/Jenkinsfile
        	            	github.com/jenkins-x/jx/pkg/jenkinsfile.(*CreateJenkinsfileArguments).GenerateJenkinsfile
        	            		/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jenkinsfile/pipeline.go:473
        	            	github.com/jenkins-x/jx/pkg/jx/cmd.(*CommonOptions).invokeDraftPack
        	            		/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/common_buildpacks.go:241
        	            	github.com/jenkins-x/jx/pkg/jx/cmd.(*StepBuildPackApplyOptions).Run
        	            		/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/step_buildpack_apply.go:103
        	            	github.com/jenkins-x/jx/pkg/jx/cmd_test.TestStepBuildPackApply
        	            		/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/step_buildpack_apply_integration_test.go:73
        	            	testing.tRunner
        	            		/usr/local/go/src/testing/testing.go:827
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestStepBuildPackApply
        	Messages:   	failed to run step
helm installed and configured
```

**Comment by msvticket** [comment]
The integration tests have gone through a couple of times now.

**Pull request merged**
