### PR TITLE
Refactor Helmer creation from CommonOptions to Factory.

### PR DESCRIPTION
**Pull request by markawm**
So that I can write unit tests around jx preview and have Factory return a mock Helmer
implementation.

#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

Whilst writing unit tests around jx preview, I was not able to inject a mock Helmer because although Helmer is already an interface, the
creation happens in CommonOptions so didn't allow a mock implementation to be returned. This is mostly a lift-and-shift of the same code out of
CommonOptions and into Factory.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by i0n** [comment]
@markawm Been trying to get this merged today. We've hit a conflict now, but my merge is causing a failure. Would you mind rebasing your branch and pushing?

**Comment by i0n** [comment]
Never mind you've just done it!

**Comment by markawm** [comment]
Cheers @i0n, just pushed an update a minute or so ago! Waiting for it to build (fine locally).

**Pull request merged**
